SETestKCL: QCPBars Class Reference
QCPBars Class Reference
#include <qcustomplot.h>
Public Types
enum WidthType { wtAbsolute, wtAxisRectRatio, wtPlotCoords }
Public Member Functions
QCPBars (QCPAxis *keyAxis, QCPAxis *valueAxis)
virtual ~QCPBars ()
double width () const
WidthType widthType () const
QCPBarsGroup * barsGroup () const
double baseValue () const
QCPBars * barBelow () const
QCPBars * barAbove () const
QCPBarDataMap * data () const
void setWidth (double width)
void setWidthType (WidthType widthType)
void setBarsGroup (QCPBarsGroup *barsGroup)
void setBaseValue (double baseValue)
void setData (QCPBarDataMap *data, bool copy=false)
void setData (const QVector< double > &key, const QVector< double > &value)
void moveBelow (QCPBars *bars)
void moveAbove (QCPBars *bars)
void addData (const QCPBarDataMap &dataMap)
void addData (const QCPBarData &data)
void addData (double key, double value)
void addData (const QVector< double > &keys, const QVector< double > &values)
void removeDataBefore (double key)
void removeDataAfter (double key)
void removeData (double fromKey, double toKey)
void removeData (double key)
virtual void clearData ()
virtual double selectTest (const QPointF &pos, bool onlySelectable, QVariant *details=0) const
Public Member Functions inherited from QCPAbstractPlottable
QCPAbstractPlottable (QCPAxis *keyAxis, QCPAxis *valueAxis)
QString name () const
bool antialiasedFill () const
bool antialiasedScatters () const
bool antialiasedErrorBars () const
QPen pen () const
QPen selectedPen () const
QBrush brush () const
QBrush selectedBrush () const
QCPAxis * keyAxis () const
QCPAxis * valueAxis () const
bool selectable () const
bool selected () const
void setName (const QString &name)
void setAntialiasedFill (bool enabled)
void setAntialiasedScatters (bool enabled)
void setAntialiasedErrorBars (bool enabled)
void setPen (const QPen &pen)
void setSelectedPen (const QPen &pen)
void setBrush (const QBrush &brush)
void setSelectedBrush (const QBrush &brush)
void setKeyAxis (QCPAxis *axis)
void setValueAxis (QCPAxis *axis)
Q_SLOT void setSelectable (bool selectable)
Q_SLOT void setSelected (bool selected)
virtual bool addToLegend ()
virtual bool removeFromLegend () const
void rescaleAxes (bool onlyEnlarge=false) const
void rescaleKeyAxis (bool onlyEnlarge=false) const
void rescaleValueAxis (bool onlyEnlarge=false) const
Public Member Functions inherited from QCPLayerable
QCPLayerable (QCustomPlot *plot, QString targetLayer=QString(), QCPLayerable *parentLayerable=0)
~QCPLayerable ()
bool visible () const
QCustomPlot * parentPlot () const
QCPLayerable * parentLayerable () const
QCPLayer * layer () const
bool antialiased () const
void setVisible (bool on)
Q_SLOT bool setLayer (QCPLayer *layer)
bool setLayer (const QString &layerName)
void setAntialiased (bool enabled)
bool realVisibility () const
Protected Member Functions
virtual void draw (QCPPainter *painter)
virtual void drawLegendIcon (QCPPainter *painter, const QRectF &rect) const
virtual QCPRange getKeyRange (bool &foundRange, SignDomain inSignDomain=sdBoth) const
virtual QCPRange getValueRange (bool &foundRange, SignDomain inSignDomain=sdBoth) const
void getVisibleDataBounds (QCPBarDataMap::const_iterator &lower, QCPBarDataMap::const_iterator &upperEnd) const
QPolygonF getBarPolygon (double key, double value) const
void getPixelWidth (double key, double &lower, double &upper) const
double getStackedBaseValue (double key, bool positive) const
Protected Member Functions inherited from QCPAbstractPlottable
virtual QRect clipRect () const
virtual QCP::Interaction selectionCategory () const
void applyDefaultAntialiasingHint (QCPPainter *painter) const
virtual void selectEvent (QMouseEvent *event, bool additive, const QVariant &details, bool *selectionStateChanged)
virtual void deselectEvent (bool *selectionStateChanged)
void coordsToPixels (double key, double value, double &x, double &y) const
const QPointF coordsToPixels (double key, double value) const
void pixelsToCoords (double x, double y, double &key, double &value) const
void pixelsToCoords (const QPointF &pixelPos, double &key, double &value) const
QPen mainPen () const
QBrush mainBrush () const
void applyFillAntialiasingHint (QCPPainter *painter) const
void applyScattersAntialiasingHint (QCPPainter *painter) const
void applyErrorBarsAntialiasingHint (QCPPainter *painter) const
double distSqrToLine (const QPointF &start, const QPointF &end, const QPointF &point) const
Protected Member Functions inherited from QCPLayerable
virtual void parentPlotInitialized (QCustomPlot *parentPlot)
void initializeParentPlot (QCustomPlot *parentPlot)
void setParentLayerable (QCPLayerable *parentLayerable)
bool moveToLayer (QCPLayer *layer, bool prepend)
void applyAntialiasingHint (QCPPainter *painter, bool localAntialiased, QCP::AntialiasedElement overrideElement) const
Static Protected Member Functions
static void connectBars (QCPBars *lower, QCPBars *upper)
Protected Attributes
QCPBarDataMap * mData
double mWidth
WidthType mWidthType
QCPBarsGroup * mBarsGroup
double mBaseValue
QPointer< QCPBars > mBarBelow
QPointer< QCPBars > mBarAbove
Protected Attributes inherited from QCPAbstractPlottable
QString mName
bool mAntialiasedFill
bool mAntialiasedScatters
bool mAntialiasedErrorBars
QPen mPen
QPen mSelectedPen
QBrush mBrush
QBrush mSelectedBrush
QPointer< QCPAxis > mKeyAxis
QPointer< QCPAxis > mValueAxis
bool mSelectable
bool mSelected
Protected Attributes inherited from QCPLayerable
bool mVisible
QCustomPlot * mParentPlot
QPointer< QCPLayerable > mParentLayerable
QCPLayer * mLayer
bool mAntialiased
Friends
class QCustomPlot
class QCPLegend
class QCPBarsGroup
Additional Inherited Members
Signals inherited from QCPAbstractPlottable
void selectionChanged (bool selected)
void selectableChanged (bool selectable)
Signals inherited from QCPLayerable
void layerChanged (QCPLayer *newLayer)
Protected Types inherited from QCPAbstractPlottable
enum SignDomain { sdNegative, sdBoth, sdPositive }
Detailed Description
A plottable representing a bar chart in a plot.
To plot data, assign it with the setData or addData functions.
Changing the appearance
The appearance of the bars is determined by the pen and the brush (setPen, setBrush). The width of the individual bars can be controlled with setWidthType and setWidth.
Bar charts are stackable. This means, two QCPBars plottables can be placed on top of each other (see QCPBars::moveAbove). So when two bars are at the same key position, they will appear stacked.
If you would like to group multiple QCPBars plottables together so they appear side by side as shown below, use QCPBarsGroup.
Usage
Like all data representing objects in QCustomPlot, the QCPBars is a plottable (QCPAbstractPlottable). So the plottable-interface of QCustomPlot applies (QCustomPlot::plottable, QCustomPlot::addPlottable, QCustomPlot::removePlottable, etc.)
Usually, you first create an instance:
add it to the customPlot with QCustomPlot::addPlottable:
and then modify the properties of the newly created plottable, e.g.:
Definition at line 2823 of file qcustomplot.h.
Member Enumeration Documentation
enum WidthType
Defines the ways the width of the bar can be specified. Thus it defines what the number passed to setWidth actually means.
See Also
setWidthType, setWidth
Enumerator
wtAbsolute
Bar width is in absolute pixels.
wtAxisRectRatio
Bar width is given by a fraction of the axis rect size.
wtPlotCoords
Bar width is in key coordinates and thus scales with the key axis range.
Definition at line 2841 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPBars (QCPAxis * keyAxis, QCPAxis * valueAxis) explicit
Constructs a bar chart which uses keyAxis as its key axis ("x") and valueAxis as its value axis ("y"). keyAxis and valueAxis must reside in the same QCustomPlot instance and not have the same orientation. If either of these restrictions is violated, a corresponding message is printed to the debug output (qDebug), the construction is not aborted, though.
The constructed QCPBars can be added to the plot with QCustomPlot::addPlottable, QCustomPlot then takes ownership of the bar chart.
Definition at line 18456 of file qcustomplot.cpp.
References QCPAbstractPlottable::mBrush, QCPAbstractPlottable::mPen, QCPAbstractPlottable::mSelectedBrush, and QCPAbstractPlottable::mSelectedPen.
~QCPBars () virtual
Definition at line 18475 of file qcustomplot.cpp.
References connectBars(), mBarAbove, mBarBelow, mData, and setBarsGroup().
Member Function Documentation
void addData (const QCPBarDataMap & dataMap)
Adds the provided data points in dataMap to the current data.
See Also
removeData
Definition at line 18655 of file qcustomplot.cpp.
References mData.
void addData (const QCPBarData & data)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Adds the provided single data point in data to the current data.
See Also
removeData
Definition at line 18664 of file qcustomplot.cpp.
References QCPBarData::key, and mData.
void addData (double key, double value)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Adds the provided single data point as key and value tuple to the current data
See Also
removeData
Definition at line 18673 of file qcustomplot.cpp.
References QCPBarData::key, mData, and QCPBarData::value.
void addData (const QVector< double > & keys, const QVector< double > & values)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Adds the provided data points as key and value tuples to the current data.
See Also
removeData
Definition at line 18685 of file qcustomplot.cpp.
References QCPBarData::key, and mData.
QCPBars * barAbove () const inline
Returns the bars plottable that is directly above this bars plottable. If there is no such plottable, returns 0.
See Also
barBelow, moveBelow, moveAbove
Definition at line 2856 of file qcustomplot.h.
References data().
QCPBars * barBelow () const inline
Returns the bars plottable that is directly below this bars plottable. If there is no such plottable, returns 0.
See Also
barAbove, moveBelow, moveAbove
Definition at line 2855 of file qcustomplot.h.
References data().
Referenced by QCPBarsGroup::keyPixelOffset().
QCPBarsGroup* barsGroup () const inline
Definition at line 2853 of file qcustomplot.h.
Referenced by setBarsGroup().
double baseValue () const inline
Definition at line 2854 of file qcustomplot.h.
Referenced by setBaseValue().
void clearData () virtual
Removes all data points.
See Also
removeData, removeDataAfter, removeDataBefore
Implements QCPAbstractPlottable.
Definition at line 18754 of file qcustomplot.cpp.
References mData.
void connectBars (QCPBars * lower, QCPBars * upper) static protected
Definition at line 19018 of file qcustomplot.cpp.
References mBarAbove, and mBarBelow.
Referenced by moveAbove(), moveBelow(), and ~QCPBars().
QCPBarDataMap* data () const inline
Definition at line 2857 of file qcustomplot.h.
Referenced by barAbove(), barBelow(), and setData().
void draw (QCPPainter * painter) protected virtual
Implements QCPAbstractPlottable.
Definition at line 18780 of file qcustomplot.cpp.
References QCPAbstractPlottable::applyDefaultAntialiasingHint(), QCPAbstractPlottable::applyFillAntialiasingHint(), getBarPolygon(), getVisibleDataBounds(), QCP::isInvalidData(), QCPAbstractPlottable::mainBrush(), QCPAbstractPlottable::mainPen(), mData, QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::mValueAxis, QCPAbstractPlottable::name(), and QCPPainter::setPen().
void drawLegendIcon (QCPPainter * painter, const QRectF & rect) const protected virtual
Implements QCPAbstractPlottable.
Definition at line 18815 of file qcustomplot.cpp.
References QCPAbstractPlottable::applyDefaultAntialiasingHint(), QCPAbstractPlottable::mBrush, QCPAbstractPlottable::mPen, and QCPPainter::setPen().
QPolygonF getBarPolygon (double key, double value) const protected
Definition at line 18894 of file qcustomplot.cpp.
References QCPAxis::coordToPixel(), getPixelWidth(), getStackedBaseValue(), QCPAbstractPlottable::keyAxis(), QCPBarsGroup::keyPixelOffset(), mBarsGroup, QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::mValueAxis, QCPAxis::orientation(), and QCPAbstractPlottable::valueAxis().
Referenced by draw(), getVisibleDataBounds(), and selectTest().
QCPRange getKeyRange (bool & foundRange, SignDomain inSignDomain = sdBoth) const protected virtual
Implements QCPAbstractPlottable.
Definition at line 19048 of file qcustomplot.cpp.
References getPixelWidth(), QCPBarsGroup::keyPixelOffset(), QCPRange::lower, mBarsGroup, mData, QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::sdBoth, QCPAbstractPlottable::sdNegative, QCPAbstractPlottable::sdPositive, and QCPRange::upper.
void getPixelWidth (double key, double & lower, double & upper) const protected
Definition at line 18934 of file qcustomplot.cpp.
References QCPAbstractPlottable::mKeyAxis, mWidth, mWidthType, wtAbsolute, wtAxisRectRatio, and wtPlotCoords.
Referenced by getBarPolygon(), and getKeyRange().
double getStackedBaseValue (double key, bool positive) const protected
Definition at line 18986 of file qcustomplot.cpp.
References mBarBelow, and mBaseValue.
Referenced by getBarPolygon(), and getValueRange().
QCPRange getValueRange (bool & foundRange, SignDomain inSignDomain = sdBoth) const protected virtual
Implements QCPAbstractPlottable.
Definition at line 19098 of file qcustomplot.cpp.
References getStackedBaseValue(), QCPRange::lower, mBaseValue, mData, QCPAbstractPlottable::sdBoth, QCPAbstractPlottable::sdNegative, QCPAbstractPlottable::sdPositive, and QCPRange::upper.
void getVisibleDataBounds (QCPBarDataMap::const_iterator & lower, QCPBarDataMap::const_iterator & upperEnd) const protected
Definition at line 18840 of file qcustomplot.cpp.
References getBarPolygon(), mData, and QCPAbstractPlottable::mKeyAxis.
Referenced by draw().
void moveAbove (QCPBars * bars)
Moves this bars plottable above bars. In other words, the bars of this plottable will appear above the bars of bars. The move target bars must use the same key and value axis as this plottable.
Inserting into and removing from existing bar stacking is handled gracefully. If bars already has a bars object above itself, this bars object is inserted between the two. If this bars object is already between two other bars, the two other bars will be stacked on top of each other after the operation.
To remove this bars plottable from any stacking, set bars to 0.
See Also
moveBelow, barBelow, barAbove
Definition at line 18632 of file qcustomplot.cpp.
References connectBars(), QCPAbstractPlottable::keyAxis(), mBarAbove, mBarBelow, QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::mValueAxis, and QCPAbstractPlottable::valueAxis().
void moveBelow (QCPBars * bars)
Moves this bars plottable below bars. In other words, the bars of this plottable will appear below the bars of bars. The move target bars must use the same key and value axis as this plottable.
Inserting into and removing from existing bar stacking is handled gracefully. If bars already has a bars object below itself, this bars object is inserted between the two. If this bars object is already between two other bars, the two other bars will be stacked on top of each other after the operation.
To remove this bars plottable from any stacking, set bars to 0.
See Also
moveBelow, barAbove, barBelow
Definition at line 18599 of file qcustomplot.cpp.
References connectBars(), QCPAbstractPlottable::keyAxis(), mBarAbove, mBarBelow, QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::mValueAxis, and QCPAbstractPlottable::valueAxis().
void removeData (double fromKey, double toKey)
Removes all data points with key between fromKey and toKey. if fromKey is greater or equal to toKey, the function does nothing. To remove a single data point with known key, use removeData(double key).
See Also
addData, clearData
Definition at line 18728 of file qcustomplot.cpp.
References mData.
void removeData (double key)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Removes a single data point at key. If the position is not known with absolute precision, consider using removeData(double fromKey, double toKey) with a small fuzziness interval around the suspected position, depeding on the precision with which the key is known.
See Also
addData, clearData
Definition at line 18745 of file qcustomplot.cpp.
References mData.
void removeDataAfter (double key)
Removes all data points with key greater than key.
See Also
addData, clearData
Definition at line 18713 of file qcustomplot.cpp.
References mData.
void removeDataBefore (double key)
Removes all data points with key smaller than key.
See Also
addData, clearData
Definition at line 18702 of file qcustomplot.cpp.
References mData.
double selectTest (const QPointF & pos, bool onlySelectable, QVariant * details = 0) const virtual
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
You may pass 0 as details to indicate that you are not interested in those selection details.
See Also
selectEvent, deselectEvent, QCustomPlot::setInteractions
Implements QCPAbstractPlottable.
Definition at line 18760 of file qcustomplot.cpp.
References getBarPolygon(), mData, QCPAbstractPlottable::mKeyAxis, QCPLayerable::mParentPlot, QCPAbstractPlottable::mSelectable, QCPAbstractPlottable::mValueAxis, and QCustomPlot::selectionTolerance().
void setBarsGroup (QCPBarsGroup * barsGroup)
Sets to which QCPBarsGroup this QCPBars instance belongs to. Alternatively, you can also use QCPBarsGroup::append.
To remove this QCPBars from any group, set barsGroup to 0.
Definition at line 18513 of file qcustomplot.cpp.
References barsGroup(), mBarsGroup, QCPBarsGroup::registerBars(), and QCPBarsGroup::unregisterBars().
Referenced by QCPBarsGroup::append(), QCPBarsGroup::clear(), QCPBarsGroup::insert(), QCPBarsGroup::remove(), and ~QCPBars().
void setBaseValue (double baseValue)
Sets the base value of this bars plottable.
The base value defines where on the value coordinate the bars start. How far the bars extend from the base value is given by their individual value data. For example, if the base value is set to 1, a bar with data value 2 will have its lowest point at value coordinate 1 and highest point at 3.
For stacked bars, only the base value of the bottom-most QCPBars has meaning.
The default base value is 0.
Definition at line 18536 of file qcustomplot.cpp.
References baseValue(), and mBaseValue.
void setData (QCPBarDataMap * data, bool copy = false)
Replaces the current data with the provided data.
If copy is set to true, data points in data will only be copied. if false, the plottable takes ownership of the passed data and replaces the internal data pointer with it. This is significantly faster than copying for large datasets.
Definition at line 18548 of file qcustomplot.cpp.
References data(), and mData.
void setData (const QVector< double > & key, const QVector< double > & value)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Replaces the current data with the provided points in key and value tuples. The provided vectors should have equal length. Else, the number of added points will be the size of the smallest vector.
Definition at line 18571 of file qcustomplot.cpp.
References QCPBarData::key, and mData.
void setWidth (double width)
Sets the width of the bars.
How the number passed as width is interpreted (e.g. screen pixels, plot coordinates,...), depends on the currently set width type, see setWidthType and WidthType.
Definition at line 18489 of file qcustomplot.cpp.
References mWidth, and width().
void setWidthType (QCPBars::WidthType widthType)
Sets how the width of the bars is defined. See the documentation of WidthType for an explanation of the possible values for widthType.
The default value is wtPlotCoords.
See Also
setWidth
Definition at line 18502 of file qcustomplot.cpp.
References mWidthType, and widthType().
double width () const inline
Definition at line 2851 of file qcustomplot.h.
Referenced by setWidth().
WidthType widthType () const inline
Definition at line 2852 of file qcustomplot.h.
Referenced by setWidthType().
Friends And Related Function Documentation
friend class QCPBarsGroup friend
Definition at line 2907 of file qcustomplot.h.
friend class QCPLegend friend
Definition at line 2906 of file qcustomplot.h.
friend class QCustomPlot friend
Definition at line 2905 of file qcustomplot.h.
Member Data Documentation
QPointer<QCPBars> mBarAbove protected
Definition at line 2890 of file qcustomplot.h.
Referenced by connectBars(), moveAbove(), moveBelow(), and ~QCPBars().
QPointer<QCPBars> mBarBelow protected
Definition at line 2890 of file qcustomplot.h.
Referenced by connectBars(), getStackedBaseValue(), moveAbove(), moveBelow(), and ~QCPBars().
QCPBarsGroup* mBarsGroup protected
Definition at line 2888 of file qcustomplot.h.
Referenced by getBarPolygon(), getKeyRange(), and setBarsGroup().
double mBaseValue protected
Definition at line 2889 of file qcustomplot.h.
Referenced by getStackedBaseValue(), getValueRange(), and setBaseValue().
QCPBarDataMap* mData protected
Definition at line 2885 of file qcustomplot.h.
Referenced by addData(), clearData(), draw(), getKeyRange(), getValueRange(), getVisibleDataBounds(), removeData(), removeDataAfter(), removeDataBefore(), selectTest(), setData(), and ~QCPBars().
double mWidth protected
Definition at line 2886 of file qcustomplot.h.
Referenced by getPixelWidth(), and setWidth().
WidthType mWidthType protected
Definition at line 2887 of file qcustomplot.h.
Referenced by getPixelWidth(), and setWidthType().
The documentation for this class was generated from the following files:
qcustomplot.h
qcustomplot.cpp