SETestKCL: QCPAbstractLegendItem Class Reference
QCPAbstractLegendItem Class Reference abstract
#include <qcustomplot.h>
Signals
void selectionChanged (bool selected)
void selectableChanged (bool selectable)
Signals inherited from QCPLayerable
void layerChanged (QCPLayer *newLayer)
Public Member Functions
QCPAbstractLegendItem (QCPLegend *parent)
QCPLegend * parentLegend () const
QFont font () const
QColor textColor () const
QFont selectedFont () const
QColor selectedTextColor () const
bool selectable () const
bool selected () const
void setFont (const QFont &font)
void setTextColor (const QColor &color)
void setSelectedFont (const QFont &font)
void setSelectedTextColor (const QColor &color)
Q_SLOT void setSelectable (bool selectable)
Q_SLOT void setSelected (bool selected)
virtual double selectTest (const QPointF &pos, bool onlySelectable, QVariant *details=0) const
Public Member Functions inherited from QCPLayoutElement
QCPLayoutElement (QCustomPlot *parentPlot=0)
virtual ~QCPLayoutElement ()
QCPLayout * layout () const
QRect rect () const
QRect outerRect () const
QMargins margins () const
QMargins minimumMargins () const
QCP::MarginSides autoMargins () const
QSize minimumSize () const
QSize maximumSize () const
QCPMarginGroup * marginGroup (QCP::MarginSide side) const
QHash< QCP::MarginSide,
QCPMarginGroup * > marginGroups () const
void setOuterRect (const QRect &rect)
void setMargins (const QMargins &margins)
void setMinimumMargins (const QMargins &margins)
void setAutoMargins (QCP::MarginSides sides)
void setMinimumSize (const QSize &size)
void setMinimumSize (int width, int height)
void setMaximumSize (const QSize &size)
void setMaximumSize (int width, int height)
void setMarginGroup (QCP::MarginSides sides, QCPMarginGroup *group)
virtual void update (UpdatePhase phase)
virtual QSize minimumSizeHint () const
virtual QSize maximumSizeHint () const
virtual QList< QCPLayoutElement * > elements (bool recursive) const
Public Member Functions inherited from QCPLayerable
QCPLayerable (QCustomPlot *plot, QString targetLayer=QString(), QCPLayerable *parentLayerable=0)
~QCPLayerable ()
bool visible () const
QCustomPlot * parentPlot () const
QCPLayerable * parentLayerable () const
QCPLayer * layer () const
bool antialiased () const
void setVisible (bool on)
Q_SLOT bool setLayer (QCPLayer *layer)
bool setLayer (const QString &layerName)
void setAntialiased (bool enabled)
bool realVisibility () const
Protected Member Functions
virtual QCP::Interaction selectionCategory () const
virtual void applyDefaultAntialiasingHint (QCPPainter *painter) const
virtual QRect clipRect () const
virtual void draw (QCPPainter *painter)=0
virtual void selectEvent (QMouseEvent *event, bool additive, const QVariant &details, bool *selectionStateChanged)
virtual void deselectEvent (bool *selectionStateChanged)
Protected Member Functions inherited from QCPLayoutElement
virtual int calculateAutoMargin (QCP::MarginSide side)
virtual void mousePressEvent (QMouseEvent *event)
virtual void mouseMoveEvent (QMouseEvent *event)
virtual void mouseReleaseEvent (QMouseEvent *event)
virtual void mouseDoubleClickEvent (QMouseEvent *event)
virtual void wheelEvent (QWheelEvent *event)
virtual void parentPlotInitialized (QCustomPlot *parentPlot)
Protected Member Functions inherited from QCPLayerable
void initializeParentPlot (QCustomPlot *parentPlot)
void setParentLayerable (QCPLayerable *parentLayerable)
bool moveToLayer (QCPLayer *layer, bool prepend)
void applyAntialiasingHint (QCPPainter *painter, bool localAntialiased, QCP::AntialiasedElement overrideElement) const
Protected Attributes
QCPLegend * mParentLegend
QFont mFont
QColor mTextColor
QFont mSelectedFont
QColor mSelectedTextColor
bool mSelectable
bool mSelected
Protected Attributes inherited from QCPLayoutElement
QCPLayout * mParentLayout
QSize mMinimumSize
QSize mMaximumSize
QRect mRect
QRect mOuterRect
QMargins mMargins
QMargins mMinimumMargins
QCP::MarginSides mAutoMargins
QHash< QCP::MarginSide,
QCPMarginGroup * > mMarginGroups
Protected Attributes inherited from QCPLayerable
bool mVisible
QCustomPlot * mParentPlot
QPointer< QCPLayerable > mParentLayerable
QCPLayer * mLayer
bool mAntialiased
Friends
class QCPLegend
Additional Inherited Members
Public Types inherited from QCPLayoutElement
enum UpdatePhase { upPreparation, upMargins, upLayout }
Detailed Description
The abstract base class for all entries in a QCPLegend.
It defines a very basic interface for entries in a QCPLegend. For representing plottables in the legend, the subclass QCPPlottableLegendItem is more suitable.
Only derive directly from this class when you need absolute freedom (e.g. a custom legend entry that's not even associated with a plottable).
You must implement the following pure virtual functions:
draw (from QCPLayerable)
You inherit the following members you may use:
QCPLegend *mParentLegend A pointer to the parent QCPLegend.
QFont mFont The generic font of the item. You should use this font for all or at least the most prominent text of the item.
Definition at line 2081 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPAbstractLegendItem (QCPLegend * parent) explicit
Constructs a QCPAbstractLegendItem and associates it with the QCPLegend parent. This does not cause the item to be added to parent, so QCPLegend::addItem must be called separately.
Definition at line 12647 of file qcustomplot.cpp.
References QCPLayerable::setLayer(), and QCPLayoutElement::setMargins().
Member Function Documentation
void applyDefaultAntialiasingHint (QCPPainter * painter) const protected virtual
Reimplemented from QCPLayoutElement.
Definition at line 12749 of file qcustomplot.cpp.
References QCP::aeLegendItems, QCPLayerable::applyAntialiasingHint(), and QCPLayerable::mAntialiased.
QRect clipRect () const protected virtual
Reimplemented from QCPLayerable.
Definition at line 12755 of file qcustomplot.cpp.
References QCPLayoutElement::mOuterRect.
void deselectEvent (bool * selectionStateChanged) protected virtual
Reimplemented from QCPLayerable.
Definition at line 12775 of file qcustomplot.cpp.
References mParentLegend, mSelectable, mSelected, QCPLegend::selectableParts(), setSelected(), and QCPLegend::spItems.
virtual void draw (QCPPainter * painter) protected pure virtual
Reimplemented from QCPLayoutElement.
Implemented in QCPPlottableLegendItem.
QFont font () const inline
Definition at line 2098 of file qcustomplot.h.
Referenced by setFont(), and setSelectedFont().
QCPLegend* parentLegend () const inline
Definition at line 2097 of file qcustomplot.h.
bool selectable () const inline
Definition at line 2102 of file qcustomplot.h.
Referenced by setSelectable().
void selectableChanged (bool selectable) signal
Referenced by setSelectable().
bool selected () const inline
Definition at line 2103 of file qcustomplot.h.
Referenced by QCPLegend::selectedParts(), and setSelected().
QFont selectedFont () const inline
Definition at line 2100 of file qcustomplot.h.
QColor selectedTextColor () const inline
Definition at line 2101 of file qcustomplot.h.
void selectEvent (QMouseEvent * event, bool additive, const QVariant & details, bool * selectionStateChanged) protected virtual
Reimplemented from QCPLayerable.
Definition at line 12761 of file qcustomplot.cpp.
References mParentLegend, mSelectable, mSelected, QCPLegend::selectableParts(), setSelected(), and QCPLegend::spItems.
QCP::Interaction selectionCategory () const protected virtual
Reimplemented from QCPLayerable.
Definition at line 13465 of file qcustomplot.cpp.
References QCP::iSelectLegend.
void selectionChanged (bool selected) signal
This signal is emitted when the selection state of this legend item has changed, either by user interaction or by a direct call to setSelected.
Referenced by setSelected().
double selectTest (const QPointF & pos, bool onlySelectable, QVariant * details = 0) const virtual
Layout elements are sensitive to events inside their outer rect. If pos is within the outer rect, this method returns a value corresponding to 0.99 times the parent plot's selection tolerance. However, layout elements are not selectable by default. So if onlySelectable is true, -1.0 is returned.
See QCPLayerable::selectTest for a general explanation of this virtual method.
QCPLayoutElement subclasses may reimplement this method to provide more specific selection test behaviour.
Reimplemented from QCPLayoutElement.
Definition at line 12735 of file qcustomplot.cpp.
References mParentLegend, QCPLayerable::mParentPlot, QCPLayoutElement::mRect, mSelectable, QCPLegend::selectableParts(), QCustomPlot::selectionTolerance(), and QCPLegend::spItems.
void setFont (const QFont & font)
Sets the default font of this specific legend item to font.
See Also
setTextColor, QCPLegend::setFont
Definition at line 12666 of file qcustomplot.cpp.
References font(), and mFont.
Referenced by QCPLegend::setFont().
void setSelectable (bool selectable)
Sets whether this specific legend item is selectable.
See Also
setSelectedParts, QCustomPlot::setInteractions
Definition at line 12708 of file qcustomplot.cpp.
References mSelectable, selectable(), and selectableChanged().
void setSelected (bool selected)
Sets whether this specific legend item is selected.
It is possible to set the selection state of this item by calling this function directly, even if setSelectable is set to false.
See Also
setSelectableParts, QCustomPlot::setInteractions
Definition at line 12725 of file qcustomplot.cpp.
References mSelected, selected(), and selectionChanged().
Referenced by deselectEvent(), selectEvent(), and QCPLegend::setSelectedParts().
void setSelectedFont (const QFont & font)
When this legend item is selected, font is used to draw generic text, instead of the normal font set with setFont.
See Also
setFont, QCPLegend::setSelectedFont
Definition at line 12687 of file qcustomplot.cpp.
References font(), and mSelectedFont.
Referenced by QCPLegend::setSelectedFont().
void setSelectedTextColor (const QColor & color)
When this legend item is selected, color is used to draw generic text, instead of the normal color set with setTextColor.
See Also
setTextColor, QCPLegend::setSelectedTextColor
Definition at line 12698 of file qcustomplot.cpp.
References mSelectedTextColor.
Referenced by QCPLegend::setSelectedTextColor().
void setTextColor (const QColor & color)
Sets the default text color of this specific legend item to color.
See Also
setFont, QCPLegend::setTextColor
Definition at line 12676 of file qcustomplot.cpp.
References mTextColor.
Referenced by QCPLegend::setTextColor().
QColor textColor () const inline
Definition at line 2099 of file qcustomplot.h.
Friends And Related Function Documentation
friend class QCPLegend friend
Definition at line 2141 of file qcustomplot.h.
Member Data Documentation
QFont mFont protected
Definition at line 2123 of file qcustomplot.h.
Referenced by QCPPlottableLegendItem::getFont(), and setFont().
QCPLegend* mParentLegend protected
Definition at line 2122 of file qcustomplot.h.
Referenced by deselectEvent(), QCPPlottableLegendItem::draw(), QCPPlottableLegendItem::getIconBorderPen(), QCPPlottableLegendItem::minimumSizeHint(), selectEvent(), and selectTest().
bool mSelectable protected
Definition at line 2127 of file qcustomplot.h.
Referenced by deselectEvent(), selectEvent(), selectTest(), and setSelectable().
bool mSelected protected
Definition at line 2127 of file qcustomplot.h.
Referenced by deselectEvent(), QCPPlottableLegendItem::getFont(), QCPPlottableLegendItem::getIconBorderPen(), QCPPlottableLegendItem::getTextColor(), selectEvent(), and setSelected().
QFont mSelectedFont protected
Definition at line 2125 of file qcustomplot.h.
Referenced by QCPPlottableLegendItem::getFont(), and setSelectedFont().
QColor mSelectedTextColor protected
Definition at line 2126 of file qcustomplot.h.
Referenced by QCPPlottableLegendItem::getTextColor(), and setSelectedTextColor().
QColor mTextColor protected
Definition at line 2124 of file qcustomplot.h.
Referenced by QCPPlottableLegendItem::getTextColor(), and setTextColor().
The documentation for this class was generated from the following files:
qcustomplot.h
qcustomplot.cpp