SETestKCL: QCPFinancial Class Reference
QCPFinancial Class Reference
#include <qcustomplot.h>
Public Types
enum ChartStyle { csOhlc, csCandlestick }
Public Member Functions
QCPFinancial (QCPAxis *keyAxis, QCPAxis *valueAxis)
virtual ~QCPFinancial ()
QCPFinancialDataMap * data () const
ChartStyle chartStyle () const
double width () const
bool twoColored () const
QBrush brushPositive () const
QBrush brushNegative () const
QPen penPositive () const
QPen penNegative () const
void setData (QCPFinancialDataMap *data, bool copy=false)
void setData (const QVector< double > &key, const QVector< double > &open, const QVector< double > &high, const QVector< double > &low, const QVector< double > &close)
void setChartStyle (ChartStyle style)
void setWidth (double width)
void setTwoColored (bool twoColored)
void setBrushPositive (const QBrush &brush)
void setBrushNegative (const QBrush &brush)
void setPenPositive (const QPen &pen)
void setPenNegative (const QPen &pen)
void addData (const QCPFinancialDataMap &dataMap)
void addData (const QCPFinancialData &data)
void addData (double key, double open, double high, double low, double close)
void addData (const QVector< double > &key, const QVector< double > &open, const QVector< double > &high, const QVector< double > &low, const QVector< double > &close)
void removeDataBefore (double key)
void removeDataAfter (double key)
void removeData (double fromKey, double toKey)
void removeData (double key)
virtual void clearData ()
virtual double selectTest (const QPointF &pos, bool onlySelectable, QVariant *details=0) const
Public Member Functions inherited from QCPAbstractPlottable
QCPAbstractPlottable (QCPAxis *keyAxis, QCPAxis *valueAxis)
QString name () const
bool antialiasedFill () const
bool antialiasedScatters () const
bool antialiasedErrorBars () const
QPen pen () const
QPen selectedPen () const
QBrush brush () const
QBrush selectedBrush () const
QCPAxis * keyAxis () const
QCPAxis * valueAxis () const
bool selectable () const
bool selected () const
void setName (const QString &name)
void setAntialiasedFill (bool enabled)
void setAntialiasedScatters (bool enabled)
void setAntialiasedErrorBars (bool enabled)
void setPen (const QPen &pen)
void setSelectedPen (const QPen &pen)
void setBrush (const QBrush &brush)
void setSelectedBrush (const QBrush &brush)
void setKeyAxis (QCPAxis *axis)
void setValueAxis (QCPAxis *axis)
Q_SLOT void setSelectable (bool selectable)
Q_SLOT void setSelected (bool selected)
virtual bool addToLegend ()
virtual bool removeFromLegend () const
void rescaleAxes (bool onlyEnlarge=false) const
void rescaleKeyAxis (bool onlyEnlarge=false) const
void rescaleValueAxis (bool onlyEnlarge=false) const
Public Member Functions inherited from QCPLayerable
QCPLayerable (QCustomPlot *plot, QString targetLayer=QString(), QCPLayerable *parentLayerable=0)
~QCPLayerable ()
bool visible () const
QCustomPlot * parentPlot () const
QCPLayerable * parentLayerable () const
QCPLayer * layer () const
bool antialiased () const
void setVisible (bool on)
Q_SLOT bool setLayer (QCPLayer *layer)
bool setLayer (const QString &layerName)
void setAntialiased (bool enabled)
bool realVisibility () const
Static Public Member Functions
static QCPFinancialDataMap timeSeriesToOhlc (const QVector< double > &time, const QVector< double > &value, double timeBinSize, double timeBinOffset=0)
Protected Member Functions
virtual void draw (QCPPainter *painter)
virtual void drawLegendIcon (QCPPainter *painter, const QRectF &rect) const
virtual QCPRange getKeyRange (bool &foundRange, SignDomain inSignDomain=sdBoth) const
virtual QCPRange getValueRange (bool &foundRange, SignDomain inSignDomain=sdBoth) const
void drawOhlcPlot (QCPPainter *painter, const QCPFinancialDataMap::const_iterator &begin, const QCPFinancialDataMap::const_iterator &end)
void drawCandlestickPlot (QCPPainter *painter, const QCPFinancialDataMap::const_iterator &begin, const QCPFinancialDataMap::const_iterator &end)
double ohlcSelectTest (const QPointF &pos, const QCPFinancialDataMap::const_iterator &begin, const QCPFinancialDataMap::const_iterator &end) const
double candlestickSelectTest (const QPointF &pos, const QCPFinancialDataMap::const_iterator &begin, const QCPFinancialDataMap::const_iterator &end) const
void getVisibleDataBounds (QCPFinancialDataMap::const_iterator &lower, QCPFinancialDataMap::const_iterator &upper) const
Protected Member Functions inherited from QCPAbstractPlottable
virtual QRect clipRect () const
virtual QCP::Interaction selectionCategory () const
void applyDefaultAntialiasingHint (QCPPainter *painter) const
virtual void selectEvent (QMouseEvent *event, bool additive, const QVariant &details, bool *selectionStateChanged)
virtual void deselectEvent (bool *selectionStateChanged)
void coordsToPixels (double key, double value, double &x, double &y) const
const QPointF coordsToPixels (double key, double value) const
void pixelsToCoords (double x, double y, double &key, double &value) const
void pixelsToCoords (const QPointF &pixelPos, double &key, double &value) const
QPen mainPen () const
QBrush mainBrush () const
void applyFillAntialiasingHint (QCPPainter *painter) const
void applyScattersAntialiasingHint (QCPPainter *painter) const
void applyErrorBarsAntialiasingHint (QCPPainter *painter) const
double distSqrToLine (const QPointF &start, const QPointF &end, const QPointF &point) const
Protected Member Functions inherited from QCPLayerable
virtual void parentPlotInitialized (QCustomPlot *parentPlot)
void initializeParentPlot (QCustomPlot *parentPlot)
void setParentLayerable (QCPLayerable *parentLayerable)
bool moveToLayer (QCPLayer *layer, bool prepend)
void applyAntialiasingHint (QCPPainter *painter, bool localAntialiased, QCP::AntialiasedElement overrideElement) const
Protected Attributes
QCPFinancialDataMap * mData
ChartStyle mChartStyle
double mWidth
bool mTwoColored
QBrush mBrushPositive
QBrush mBrushNegative
QPen mPenPositive
QPen mPenNegative
Protected Attributes inherited from QCPAbstractPlottable
QString mName
bool mAntialiasedFill
bool mAntialiasedScatters
bool mAntialiasedErrorBars
QPen mPen
QPen mSelectedPen
QBrush mBrush
QBrush mSelectedBrush
QPointer< QCPAxis > mKeyAxis
QPointer< QCPAxis > mValueAxis
bool mSelectable
bool mSelected
Protected Attributes inherited from QCPLayerable
bool mVisible
QCustomPlot * mParentPlot
QPointer< QCPLayerable > mParentLayerable
QCPLayer * mLayer
bool mAntialiased
Friends
class QCustomPlot
class QCPLegend
Additional Inherited Members
Signals inherited from QCPAbstractPlottable
void selectionChanged (bool selected)
void selectableChanged (bool selectable)
Signals inherited from QCPLayerable
void layerChanged (QCPLayer *newLayer)
Protected Types inherited from QCPAbstractPlottable
enum SignDomain { sdNegative, sdBoth, sdPositive }
Detailed Description
A plottable representing a financial stock chart.
This plottable represents time series data binned to certain intervals, mainly used for stock charts. The two common representations OHLC (Open-High-Low-Close) bars and Candlesticks can be set via setChartStyle.
The data is passed via setData as a set of open/high/low/close values at certain keys (typically times). This means the data must be already binned appropriately. If data is only available as a series of values (e.g. price against time), you can use the static convenience function timeSeriesToOhlc to generate binned OHLC-data which can then be passed to setData.
The width of the OHLC bars/candlesticks can be controlled with setWidth and is given in plot key coordinates. A typical choice is to set it to (or slightly less than) one bin interval width.
Changing the appearance
Charts can be either single- or two-colored (setTwoColored). If set to be single-colored, lines are drawn with the plottable's pen (setPen) and fills with the brush (setBrush).
If set to two-colored, positive changes of the value during an interval (close >= open) are represented with a different pen and brush than negative changes (close < open). These can be configured with setPenPositive, setPenNegative, setBrushPositive, and setBrushNegative. In two-colored mode, the normal plottable pen/brush is ignored. Upon selection however, the normal selected pen/brush (setSelectedPen, setSelectedBrush) is used, irrespective of whether the chart is single- or two-colored.
Definition at line 3145 of file qcustomplot.h.
Member Enumeration Documentation
enum ChartStyle
Defines the possible representations of OHLC data in the plot.
See Also
setChartStyle
Enumerator
csOhlc
Open-High-Low-Close bar representation.
csCandlestick
Candlestick representation.
Definition at line 3163 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPFinancial (QCPAxis * keyAxis, QCPAxis * valueAxis) explicit
Constructs a financial chart which uses keyAxis as its key axis ("x") and valueAxis as its value axis ("y"). keyAxis and valueAxis must reside in the same QCustomPlot instance and not have the same orientation. If either of these restrictions is violated, a corresponding message is printed to the debug output (qDebug), the construction is not aborted, though.
The constructed QCPFinancial can be added to the plot with QCustomPlot::addPlottable, QCustomPlot then takes ownership of the financial chart.
Definition at line 20637 of file qcustomplot.cpp.
References mData, QCPAbstractPlottable::setSelectedBrush(), and QCPAbstractPlottable::setSelectedPen().
~QCPFinancial () virtual
Definition at line 20654 of file qcustomplot.cpp.
References mData.
Member Function Documentation
void addData (const QCPFinancialDataMap & dataMap)
Adds the provided data points in dataMap to the current data.
Alternatively, you can also access and modify the data via the data method, which returns a pointer to the internal QCPFinancialDataMap.
See Also
removeData
Definition at line 20805 of file qcustomplot.cpp.
References mData.
void addData (const QCPFinancialData & data)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Adds the provided single data point in data to the current data.
Alternatively, you can also access and modify the data via the data method, which returns a pointer to the internal QCPFinancialData.
See Also
removeData
Definition at line 20819 of file qcustomplot.cpp.
References QCPFinancialData::key, and mData.
void addData (double key, double open, double high, double low, double close)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Adds the provided single data point given by key, open, high, low, and close to the current data.
Alternatively, you can also access and modify the data via the data method, which returns a pointer to the internal QCPFinancialData.
See Also
removeData
Definition at line 20834 of file qcustomplot.cpp.
References mData.
void addData (const QVector< double > & key, const QVector< double > & open, const QVector< double > & high, const QVector< double > & low, const QVector< double > & close)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Adds the provided open/high/low/close data to the current data.
Alternatively, you can also access and modify the data via the data method, which returns a pointer to the internal QCPFinancialData.
See Also
removeData
Definition at line 20848 of file qcustomplot.cpp.
References mData.
QBrush brushNegative () const inline
Definition at line 3177 of file qcustomplot.h.
QBrush brushPositive () const inline
Definition at line 3176 of file qcustomplot.h.
double candlestickSelectTest (const QPointF & pos, const QCPFinancialDataMap::const_iterator & begin, const QCPFinancialDataMap::const_iterator & end) const protected
Definition at line 21359 of file qcustomplot.cpp.
References QCPRange::contains(), QCPAxis::coordToPixel(), QCPAbstractPlottable::distSqrToLine(), QCPAbstractPlottable::keyAxis(), QCPAbstractPlottable::mKeyAxis, QCPLayerable::mParentPlot, QCPAbstractPlottable::mValueAxis, mWidth, QCPAxis::orientation(), QCPAbstractPlottable::pixelsToCoords(), QCustomPlot::selectionTolerance(), and QCPAbstractPlottable::valueAxis().
Referenced by selectTest().
ChartStyle chartStyle () const inline
Definition at line 3173 of file qcustomplot.h.
void clearData () virtual
Removes all data points.
See Also
removeData, removeDataAfter, removeDataBefore
Implements QCPAbstractPlottable.
Definition at line 20920 of file qcustomplot.cpp.
References mData.
QCPFinancialDataMap * data () const inline
Returns a pointer to the internal data storage of type QCPFinancialDataMap. You may use it to directly manipulate the data, which may be more convenient and faster than using the regular setData or addData methods, in certain situations.
Definition at line 3172 of file qcustomplot.h.
Referenced by setData().
void draw (QCPPainter * painter) protected virtual
Implements QCPAbstractPlottable.
Definition at line 21005 of file qcustomplot.cpp.
References csCandlestick, csOhlc, drawCandlestickPlot(), drawOhlcPlot(), getVisibleDataBounds(), mChartStyle, and mData.
void drawCandlestickPlot (QCPPainter * painter, const QCPFinancialDataMap::const_iterator & begin, const QCPFinancialDataMap::const_iterator & end) protected
Definition at line 21230 of file qcustomplot.cpp.
References QCPAxis::coordToPixel(), QCPPainter::drawLine(), QCPAbstractPlottable::keyAxis(), QCPAbstractPlottable::mBrush, mBrushNegative, mBrushPositive, QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::mPen, mPenNegative, mPenPositive, QCPAbstractPlottable::mSelected, QCPAbstractPlottable::mSelectedBrush, QCPAbstractPlottable::mSelectedPen, mTwoColored, QCPAbstractPlottable::mValueAxis, mWidth, QCPAxis::orientation(), QCPPainter::setPen(), and QCPAbstractPlottable::valueAxis().
Referenced by draw().
void drawLegendIcon (QCPPainter * painter, const QRectF & rect) const protected virtual
Implements QCPAbstractPlottable.
Definition at line 21024 of file qcustomplot.cpp.
References csCandlestick, csOhlc, QCPPainter::drawLine(), QCPAbstractPlottable::mBrush, mBrushNegative, mBrushPositive, mChartStyle, QCPAbstractPlottable::mPen, mPenNegative, mPenPositive, mTwoColored, QCPPainter::setAntialiasing(), and QCPPainter::setPen().
void drawOhlcPlot (QCPPainter * painter, const QCPFinancialDataMap::const_iterator & begin, const QCPFinancialDataMap::const_iterator & end) protected
Definition at line 21169 of file qcustomplot.cpp.
References QCPAxis::coordToPixel(), QCPPainter::drawLine(), QCPAbstractPlottable::keyAxis(), QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::mPen, mPenNegative, mPenPositive, QCPAbstractPlottable::mSelected, QCPAbstractPlottable::mSelectedPen, mTwoColored, QCPAbstractPlottable::mValueAxis, mWidth, QCPAxis::orientation(), QCPPainter::setPen(), and QCPAbstractPlottable::valueAxis().
Referenced by draw().
QCPRange getKeyRange (bool & foundRange, QCPAbstractPlottable::SignDomain inSignDomain = sdBoth) const protected virtual
Implements QCPAbstractPlottable.
Definition at line 21083 of file qcustomplot.cpp.
References QCPRange::lower, mData, QCPAbstractPlottable::mKeyAxis, mWidth, QCPAbstractPlottable::sdBoth, QCPAbstractPlottable::sdNegative, QCPAbstractPlottable::sdPositive, and QCPRange::upper.
QCPRange getValueRange (bool & foundRange, QCPAbstractPlottable::SignDomain inSignDomain = sdBoth) const protected virtual
Implements QCPAbstractPlottable.
Definition at line 21119 of file qcustomplot.cpp.
References QCPRange::lower, mData, QCPAbstractPlottable::sdBoth, QCPAbstractPlottable::sdNegative, QCPAbstractPlottable::sdPositive, and QCPRange::upper.
void getVisibleDataBounds (QCPFinancialDataMap::const_iterator & lower, QCPFinancialDataMap::const_iterator & upper) const protected
Definition at line 21435 of file qcustomplot.cpp.
References mData, and QCPAbstractPlottable::mKeyAxis.
Referenced by draw(), and selectTest().
double ohlcSelectTest (const QPointF & pos, const QCPFinancialDataMap::const_iterator & begin, const QCPFinancialDataMap::const_iterator & end) const protected
Definition at line 21321 of file qcustomplot.cpp.
References QCPAxis::coordToPixel(), QCPAbstractPlottable::distSqrToLine(), QCPAbstractPlottable::keyAxis(), QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::mValueAxis, QCPAxis::orientation(), and QCPAbstractPlottable::valueAxis().
Referenced by selectTest().
QPen penNegative () const inline
Definition at line 3179 of file qcustomplot.h.
QPen penPositive () const inline
Definition at line 3178 of file qcustomplot.h.
void removeData (double fromKey, double toKey)
Removes all data points with keys between fromKey and toKey. if fromKey is greater or equal to toKey, the function does nothing. To remove a single data point with known key, use removeData(double key).
See Also
addData, clearData
Definition at line 20893 of file qcustomplot.cpp.
References mData.
void removeData (double key)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Removes a single data point at key. If the position is not known with absolute precision, consider using removeData(double fromKey, double toKey) with a small fuzziness interval around the suspected position, depeding on the precision with which the key is known.
See Also
addData, clearData
Definition at line 20910 of file qcustomplot.cpp.
References mData.
void removeDataAfter (double key)
Removes all data points with keys greater than key.
See Also
addData, clearData
Definition at line 20878 of file qcustomplot.cpp.
References mData.
void removeDataBefore (double key)
Removes all data points with keys smaller than key.
See Also
addData, clearData
Definition at line 20866 of file qcustomplot.cpp.
References mData.
double selectTest (const QPointF & pos, bool onlySelectable, QVariant * details = 0) const virtual
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
You may pass 0 as details to indicate that you are not interested in those selection details.
See Also
selectEvent, deselectEvent, QCustomPlot::setInteractions
Implements QCPAbstractPlottable.
Definition at line 20926 of file qcustomplot.cpp.
References candlestickSelectTest(), csCandlestick, csOhlc, getVisibleDataBounds(), mChartStyle, mData, QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::mSelectable, QCPAbstractPlottable::mValueAxis, and ohlcSelectTest().
void setBrushNegative (const QBrush & brush)
If setTwoColored is set to true, this function controls the brush that is used to draw fills of data points with a negative trend (i.e. bars/candlesticks with close < open).
If twoColored is false, the normal plottable's pen and brush are used (setPen, setBrush).
See Also
setBrushPositive, setPenNegative, setPenPositive
Definition at line 20764 of file qcustomplot.cpp.
References QCPAbstractPlottable::brush(), and mBrushNegative.
void setBrushPositive (const QBrush & brush)
If setTwoColored is set to true, this function controls the brush that is used to draw fills of data points with a positive trend (i.e. bars/candlesticks with close >= open).
If twoColored is false, the normal plottable's pen and brush are used (setPen, setBrush).
See Also
setBrushNegative, setPenPositive, setPenNegative
Definition at line 20750 of file qcustomplot.cpp.
References QCPAbstractPlottable::brush(), and mBrushPositive.
void setChartStyle (QCPFinancial::ChartStyle style)
Sets which representation style shall be used to display the OHLC data.
Definition at line 20712 of file qcustomplot.cpp.
References mChartStyle.
void setData (QCPFinancialDataMap * data, bool copy = false)
Replaces the current data with the provided data.
If copy is set to true, data points in data will only be copied. if false, the plottable takes ownership of the passed data and replaces the internal data pointer with it. This is significantly faster than copying for large datasets.
Alternatively, you can also access and modify the plottable's data via the data method, which returns a pointer to the internal QCPFinancialDataMap.
See Also
timeSeriesToOhlc
Definition at line 20671 of file qcustomplot.cpp.
References data(), and mData.
void setData (const QVector< double > & key, const QVector< double > & open, const QVector< double > & high, const QVector< double > & low, const QVector< double > & close)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Replaces the current data with the provided open/high/low/close data. The provided vectors should have equal length. Else, the number of added points will be the size of the smallest vector.
See Also
timeSeriesToOhlc
Definition at line 20695 of file qcustomplot.cpp.
References mData.
void setPenNegative (const QPen & pen)
If setTwoColored is set to true, this function controls the pen that is used to draw outlines of data points with a negative trend (i.e. bars/candlesticks with close < open).
If twoColored is false, the normal plottable's pen and brush are used (setPen, setBrush).
See Also
setPenPositive, setBrushNegative, setBrushPositive
Definition at line 20792 of file qcustomplot.cpp.
References mPenNegative, and QCPAbstractPlottable::pen().
void setPenPositive (const QPen & pen)
If setTwoColored is set to true, this function controls the pen that is used to draw outlines of data points with a positive trend (i.e. bars/candlesticks with close >= open).
If twoColored is false, the normal plottable's pen and brush are used (setPen, setBrush).
See Also
setPenNegative, setBrushPositive, setBrushNegative
Definition at line 20778 of file qcustomplot.cpp.
References mPenPositive, and QCPAbstractPlottable::pen().
void setTwoColored (bool twoColored)
Sets whether this chart shall contrast positive from negative trends per data point by using two separate colors to draw the respective bars/candlesticks.
If twoColored is false, the normal plottable's pen and brush are used (setPen, setBrush).
See Also
setPenPositive, setPenNegative, setBrushPositive, setBrushNegative
Definition at line 20736 of file qcustomplot.cpp.
References mTwoColored, and twoColored().
void setWidth (double width)
Sets the width of the individual bars/candlesticks to width in plot key coordinates.
A typical choice is to set it to (or slightly less than) one bin interval width.
Definition at line 20722 of file qcustomplot.cpp.
References mWidth, and width().
QCPFinancialDataMap timeSeriesToOhlc (const QVector< double > & time, const QVector< double > & value, double timeBinSize, double timeBinOffset = 0) static
A convenience function that converts time series data (value against time) to OHLC binned data points. The return value can then be passed on to setData.
The size of the bins can be controlled with timeBinSize in the same units as time is given. For example, if the unit of time is seconds and single OHLC/Candlesticks should span an hour each, set timeBinSize to 3600.
timeBinOffset allows to control precisely at what time coordinate a bin should start. The value passed as timeBinOffset doesn't need to be in the range encompassed by the time keys. It merely defines the mathematical offset/phase of the bins that will be used to process the data.
Definition at line 20965 of file qcustomplot.cpp.
bool twoColored () const inline
Definition at line 3175 of file qcustomplot.h.
Referenced by setTwoColored().
double width () const inline
Definition at line 3174 of file qcustomplot.h.
Referenced by setWidth().
Friends And Related Function Documentation
friend class QCPLegend friend
Definition at line 3233 of file qcustomplot.h.
friend class QCustomPlot friend
Definition at line 3232 of file qcustomplot.h.
Member Data Documentation
QBrush mBrushNegative protected
Definition at line 3216 of file qcustomplot.h.
Referenced by drawCandlestickPlot(), drawLegendIcon(), and setBrushNegative().
QBrush mBrushPositive protected
Definition at line 3216 of file qcustomplot.h.
Referenced by drawCandlestickPlot(), drawLegendIcon(), and setBrushPositive().
ChartStyle mChartStyle protected
Definition at line 3213 of file qcustomplot.h.
Referenced by draw(), drawLegendIcon(), selectTest(), and setChartStyle().
QCPFinancialDataMap* mData protected
Definition at line 3212 of file qcustomplot.h.
Referenced by addData(), clearData(), draw(), getKeyRange(), getValueRange(), getVisibleDataBounds(), QCPFinancial(), removeData(), removeDataAfter(), removeDataBefore(), selectTest(), setData(), and ~QCPFinancial().
QPen mPenNegative protected
Definition at line 3217 of file qcustomplot.h.
Referenced by drawCandlestickPlot(), drawLegendIcon(), drawOhlcPlot(), and setPenNegative().
QPen mPenPositive protected
Definition at line 3217 of file qcustomplot.h.
Referenced by drawCandlestickPlot(), drawLegendIcon(), drawOhlcPlot(), and setPenPositive().
bool mTwoColored protected
Definition at line 3215 of file qcustomplot.h.
Referenced by drawCandlestickPlot(), drawLegendIcon(), drawOhlcPlot(), and setTwoColored().
double mWidth protected
Definition at line 3214 of file qcustomplot.h.
Referenced by candlestickSelectTest(), drawCandlestickPlot(), drawOhlcPlot(), getKeyRange(), and setWidth().
The documentation for this class was generated from the following files:
qcustomplot.h
qcustomplot.cpp