SETestKCL: QCPCurve Class Reference
QCPCurve Class Reference
#include <qcustomplot.h>
Public Types
enum LineStyle { lsNone, lsLine }
Public Member Functions
QCPCurve (QCPAxis *keyAxis, QCPAxis *valueAxis)
virtual ~QCPCurve ()
QCPCurveDataMap * data () const
QCPScatterStyle scatterStyle () const
LineStyle lineStyle () const
void setData (QCPCurveDataMap *data, bool copy=false)
void setData (const QVector< double > &t, const QVector< double > &key, const QVector< double > &value)
void setData (const QVector< double > &key, const QVector< double > &value)
void setScatterStyle (const QCPScatterStyle &style)
void setLineStyle (LineStyle style)
void addData (const QCPCurveDataMap &dataMap)
void addData (const QCPCurveData &data)
void addData (double t, double key, double value)
void addData (double key, double value)
void addData (const QVector< double > &ts, const QVector< double > &keys, const QVector< double > &values)
void removeDataBefore (double t)
void removeDataAfter (double t)
void removeData (double fromt, double tot)
void removeData (double t)
virtual void clearData ()
virtual double selectTest (const QPointF &pos, bool onlySelectable, QVariant *details=0) const
Public Member Functions inherited from QCPAbstractPlottable
QCPAbstractPlottable (QCPAxis *keyAxis, QCPAxis *valueAxis)
QString name () const
bool antialiasedFill () const
bool antialiasedScatters () const
bool antialiasedErrorBars () const
QPen pen () const
QPen selectedPen () const
QBrush brush () const
QBrush selectedBrush () const
QCPAxis * keyAxis () const
QCPAxis * valueAxis () const
bool selectable () const
bool selected () const
void setName (const QString &name)
void setAntialiasedFill (bool enabled)
void setAntialiasedScatters (bool enabled)
void setAntialiasedErrorBars (bool enabled)
void setPen (const QPen &pen)
void setSelectedPen (const QPen &pen)
void setBrush (const QBrush &brush)
void setSelectedBrush (const QBrush &brush)
void setKeyAxis (QCPAxis *axis)
void setValueAxis (QCPAxis *axis)
Q_SLOT void setSelectable (bool selectable)
Q_SLOT void setSelected (bool selected)
virtual bool addToLegend ()
virtual bool removeFromLegend () const
void rescaleAxes (bool onlyEnlarge=false) const
void rescaleKeyAxis (bool onlyEnlarge=false) const
void rescaleValueAxis (bool onlyEnlarge=false) const
Public Member Functions inherited from QCPLayerable
QCPLayerable (QCustomPlot *plot, QString targetLayer=QString(), QCPLayerable *parentLayerable=0)
~QCPLayerable ()
bool visible () const
QCustomPlot * parentPlot () const
QCPLayerable * parentLayerable () const
QCPLayer * layer () const
bool antialiased () const
void setVisible (bool on)
Q_SLOT bool setLayer (QCPLayer *layer)
bool setLayer (const QString &layerName)
void setAntialiased (bool enabled)
bool realVisibility () const
Protected Member Functions
virtual void draw (QCPPainter *painter)
virtual void drawLegendIcon (QCPPainter *painter, const QRectF &rect) const
virtual QCPRange getKeyRange (bool &foundRange, SignDomain inSignDomain=sdBoth) const
virtual QCPRange getValueRange (bool &foundRange, SignDomain inSignDomain=sdBoth) const
virtual void drawScatterPlot (QCPPainter *painter, const QVector< QPointF > *pointData) const
void getCurveData (QVector< QPointF > *lineData) const
int getRegion (double x, double y, double rectLeft, double rectTop, double rectRight, double rectBottom) const
QPointF getOptimizedPoint (int prevRegion, double prevKey, double prevValue, double key, double value, double rectLeft, double rectTop, double rectRight, double rectBottom) const
QVector< QPointF > getOptimizedCornerPoints (int prevRegion, int currentRegion, double prevKey, double prevValue, double key, double value, double rectLeft, double rectTop, double rectRight, double rectBottom) const
bool mayTraverse (int prevRegion, int currentRegion) const
bool getTraverse (double prevKey, double prevValue, double key, double value, double rectLeft, double rectTop, double rectRight, double rectBottom, QPointF &crossA, QPointF &crossB) const
void getTraverseCornerPoints (int prevRegion, int currentRegion, double rectLeft, double rectTop, double rectRight, double rectBottom, QVector< QPointF > &beforeTraverse, QVector< QPointF > &afterTraverse) const
double pointDistance (const QPointF &pixelPoint) const
Protected Member Functions inherited from QCPAbstractPlottable
virtual QRect clipRect () const
virtual QCP::Interaction selectionCategory () const
void applyDefaultAntialiasingHint (QCPPainter *painter) const
virtual void selectEvent (QMouseEvent *event, bool additive, const QVariant &details, bool *selectionStateChanged)
virtual void deselectEvent (bool *selectionStateChanged)
void coordsToPixels (double key, double value, double &x, double &y) const
const QPointF coordsToPixels (double key, double value) const
void pixelsToCoords (double x, double y, double &key, double &value) const
void pixelsToCoords (const QPointF &pixelPos, double &key, double &value) const
QPen mainPen () const
QBrush mainBrush () const
void applyFillAntialiasingHint (QCPPainter *painter) const
void applyScattersAntialiasingHint (QCPPainter *painter) const
void applyErrorBarsAntialiasingHint (QCPPainter *painter) const
double distSqrToLine (const QPointF &start, const QPointF &end, const QPointF &point) const
Protected Member Functions inherited from QCPLayerable
virtual void parentPlotInitialized (QCustomPlot *parentPlot)
void initializeParentPlot (QCustomPlot *parentPlot)
void setParentLayerable (QCPLayerable *parentLayerable)
bool moveToLayer (QCPLayer *layer, bool prepend)
void applyAntialiasingHint (QCPPainter *painter, bool localAntialiased, QCP::AntialiasedElement overrideElement) const
Protected Attributes
QCPCurveDataMap * mData
QCPScatterStyle mScatterStyle
LineStyle mLineStyle
Protected Attributes inherited from QCPAbstractPlottable
QString mName
bool mAntialiasedFill
bool mAntialiasedScatters
bool mAntialiasedErrorBars
QPen mPen
QPen mSelectedPen
QBrush mBrush
QBrush mSelectedBrush
QPointer< QCPAxis > mKeyAxis
QPointer< QCPAxis > mValueAxis
bool mSelectable
bool mSelected
Protected Attributes inherited from QCPLayerable
bool mVisible
QCustomPlot * mParentPlot
QPointer< QCPLayerable > mParentLayerable
QCPLayer * mLayer
bool mAntialiased
Friends
class QCustomPlot
class QCPLegend
Additional Inherited Members
Signals inherited from QCPAbstractPlottable
void selectionChanged (bool selected)
void selectableChanged (bool selectable)
Signals inherited from QCPLayerable
void layerChanged (QCPLayer *newLayer)
Protected Types inherited from QCPAbstractPlottable
enum SignDomain { sdNegative, sdBoth, sdPositive }
Detailed Description
A plottable representing a parametric curve in a plot.
Unlike QCPGraph, plottables of this type may have multiple points with the same key coordinate, so their visual representation can have loops. This is realized by introducing a third coordinate t, which defines the order of the points described by the other two coordinates x and y.
To plot data, assign it with the setData or addData functions.
Gaps in the curve can be created by adding data points with NaN as key and value (qQNaN() or std::numeric_limits<double>::quiet_NaN()) in between the two data points that shall be separated.
Changing the appearance
The appearance of the curve is determined by the pen and the brush (setPen, setBrush).
Usage
Like all data representing objects in QCustomPlot, the QCPCurve is a plottable (QCPAbstractPlottable). So the plottable-interface of QCustomPlot applies (QCustomPlot::plottable, QCustomPlot::addPlottable, QCustomPlot::removePlottable, etc.)
Usually, you first create an instance and add it to the customPlot:
and then modify the properties of the newly created plottable, e.g.:
Definition at line 2660 of file qcustomplot.h.
Member Enumeration Documentation
enum LineStyle
Defines how the curve's line is represented visually in the plot. The line is drawn with the current pen of the curve (setPen).
See Also
setLineStyle
Enumerator
lsNone
No line is drawn between data points (e.g. only scatters)
lsLine
Data points are connected with a straight line.
Definition at line 2673 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPCurve (QCPAxis * keyAxis, QCPAxis * valueAxis) explicit
Constructs a curve which uses keyAxis as its key axis ("x") and valueAxis as its value axis ("y"). keyAxis and valueAxis must reside in the same QCustomPlot instance and not have the same orientation. If either of these restrictions is violated, a corresponding message is printed to the debug output (qDebug), the construction is not aborted, though.
The constructed QCPCurve can be added to the plot with QCustomPlot::addPlottable, QCustomPlot then takes ownership of the graph.
Definition at line 16812 of file qcustomplot.cpp.
References lsLine, QCPAbstractPlottable::mBrush, mData, QCPAbstractPlottable::mPen, QCPAbstractPlottable::mSelectedBrush, QCPAbstractPlottable::mSelectedPen, setLineStyle(), and setScatterStyle().
~QCPCurve () virtual
Definition at line 16829 of file qcustomplot.cpp.
References mData.
Member Function Documentation
void addData (const QCPCurveDataMap & dataMap)
Adds the provided data points in dataMap to the current data.
See Also
removeData
Definition at line 16928 of file qcustomplot.cpp.
References mData.
void addData (const QCPCurveData & data)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Adds the provided single data point in data to the current data.
See Also
removeData
Definition at line 16937 of file qcustomplot.cpp.
References mData, and QCPCurveData::t.
void addData (double t, double key, double value)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Adds the provided single data point as t, key and value tuple to the current data
See Also
removeData
Definition at line 16946 of file qcustomplot.cpp.
References QCPCurveData::key, mData, QCPCurveData::t, and QCPCurveData::value.
void addData (double key, double value)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Adds the provided single data point as key and value pair to the current data The t parameter of the data point is set to the t of the last data point plus 1. If there is no last data point, t will be set to 0.
See Also
removeData
Definition at line 16963 of file qcustomplot.cpp.
References QCPCurveData::key, mData, QCPCurveData::t, and QCPCurveData::value.
void addData (const QVector< double > & ts, const QVector< double > & keys, const QVector< double > & values)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Adds the provided data points as t, key and value tuples to the current data.
See Also
removeData
Definition at line 16979 of file qcustomplot.cpp.
References mData, and QCPCurveData::t.
void clearData () virtual
Removes all data points.
See Also
removeData, removeDataAfter, removeDataBefore
Implements QCPAbstractPlottable.
Definition at line 17051 of file qcustomplot.cpp.
References mData.
QCPCurveDataMap* data () const inline
Definition at line 2680 of file qcustomplot.h.
Referenced by setData().
void draw (QCPPainter * painter) protected virtual
Implements QCPAbstractPlottable.
Definition at line 17071 of file qcustomplot.cpp.
References QCPAbstractPlottable::applyDefaultAntialiasingHint(), QCPAbstractPlottable::applyFillAntialiasingHint(), QCPPainter::drawLine(), drawScatterPlot(), getCurveData(), QCP::isInvalidData(), QCPScatterStyle::isNone(), lsNone, QCPAbstractPlottable::mainBrush(), QCPAbstractPlottable::mainPen(), mData, mLineStyle, QCPPainter::modes(), QCPLayerable::mParentPlot, mScatterStyle, QCPAbstractPlottable::name(), QCP::phFastPolylines, QCustomPlot::plottingHints(), QCPPainter::pmNoCaching, QCPPainter::pmVectorized, and QCPPainter::setPen().
void drawLegendIcon (QCPPainter * painter, const QRectF & rect) const protected virtual
Implements QCPAbstractPlottable.
Definition at line 17159 of file qcustomplot.cpp.
References QCPAbstractPlottable::applyDefaultAntialiasingHint(), QCPAbstractPlottable::applyFillAntialiasingHint(), QCPAbstractPlottable::applyScattersAntialiasingHint(), QCPScatterStyle::applyTo(), QCPPainter::drawLine(), QCPScatterStyle::drawShape(), QCPScatterStyle::isNone(), lsNone, QCPAbstractPlottable::mBrush, mLineStyle, QCPAbstractPlottable::mPen, mScatterStyle, QCPScatterStyle::pixmap(), QCPPainter::setPen(), QCPScatterStyle::setPixmap(), QCPScatterStyle::shape(), and QCPScatterStyle::ssPixmap.
void drawScatterPlot (QCPPainter * painter, const QVector< QPointF > * pointData) const protected virtual
Definition at line 17198 of file qcustomplot.cpp.
References QCPAbstractPlottable::applyScattersAntialiasingHint(), QCPScatterStyle::applyTo(), QCPScatterStyle::drawShape(), QCPAbstractPlottable::mPen, and mScatterStyle.
Referenced by draw().
void getCurveData (QVector< QPointF > * lineData) const protected
Definition at line 17221 of file qcustomplot.cpp.
References QCPAbstractPlottable::coordsToPixels(), QCPAxis::coordToPixel(), getOptimizedCornerPoints(), getOptimizedPoint(), getRegion(), getTraverse(), getTraverseCornerPoints(), QCPScatterStyle::isNone(), QCPAbstractPlottable::keyAxis(), QCPRange::lower, QCPAbstractPlottable::mainPen(), mayTraverse(), mData, QCPAbstractPlottable::mKeyAxis, mScatterStyle, QCPAbstractPlottable::mValueAxis, QCPAxis::orientation(), QCPAxis::pixelToCoord(), QCPAxis::range(), QCPAxis::rangeReversed(), QCPScatterStyle::size(), QCPRange::upper, and QCPAbstractPlottable::valueAxis().
Referenced by draw(), and pointDistance().
QCPRange getKeyRange (bool & foundRange, SignDomain inSignDomain = sdBoth) const protected virtual
Implements QCPAbstractPlottable.
Definition at line 17943 of file qcustomplot.cpp.
References QCPRange::lower, mData, QCPAbstractPlottable::sdBoth, QCPAbstractPlottable::sdNegative, QCPAbstractPlottable::sdPositive, and QCPRange::upper.
QVector< QPointF > getOptimizedCornerPoints (int prevRegion, int currentRegion, double prevKey, double prevValue, double key, double value, double rectLeft, double rectTop, double rectRight, double rectBottom) const protected
Definition at line 17462 of file qcustomplot.cpp.
References QCPAbstractPlottable::coordsToPixels().
Referenced by getCurveData().
QPointF getOptimizedPoint (int prevRegion, double prevKey, double prevValue, double key, double value, double rectLeft, double rectTop, double rectRight, double rectBottom) const protected
Definition at line 17362 of file qcustomplot.cpp.
References QCPAbstractPlottable::coordsToPixels().
Referenced by getCurveData().
int getRegion (double x, double y, double rectLeft, double rectTop, double rectRight, double rectBottom) const protected
Definition at line 17318 of file qcustomplot.cpp.
Referenced by getCurveData().
bool getTraverse (double prevKey, double prevValue, double key, double value, double rectLeft, double rectTop, double rectRight, double rectBottom, QPointF & crossA, QPointF & crossB) const protected
Definition at line 17729 of file qcustomplot.cpp.
References QCPAbstractPlottable::coordsToPixels().
Referenced by getCurveData().
void getTraverseCornerPoints (int prevRegion, int currentRegion, double rectLeft, double rectTop, double rectRight, double rectBottom, QVector< QPointF > & beforeTraverse, QVector< QPointF > & afterTraverse) const protected
Definition at line 17825 of file qcustomplot.cpp.
References QCPAbstractPlottable::coordsToPixels().
Referenced by getCurveData().
QCPRange getValueRange (bool & foundRange, SignDomain inSignDomain = sdBoth) const protected virtual
Implements QCPAbstractPlottable.
Definition at line 17979 of file qcustomplot.cpp.
References QCPRange::lower, mData, QCPAbstractPlottable::sdBoth, QCPAbstractPlottable::sdNegative, QCPAbstractPlottable::sdPositive, and QCPRange::upper.
LineStyle lineStyle () const inline
Definition at line 2682 of file qcustomplot.h.
bool mayTraverse (int prevRegion, int currentRegion) const protected
Definition at line 17626 of file qcustomplot.cpp.
Referenced by getCurveData().
double pointDistance (const QPointF & pixelPoint) const protected
Definition at line 17915 of file qcustomplot.cpp.
References QCPAbstractPlottable::coordsToPixels(), QCPAbstractPlottable::distSqrToLine(), getCurveData(), mData, and QCPAbstractPlottable::mName.
Referenced by selectTest().
void removeData (double fromt, double tot)
Removes all data points with curve parameter t between fromt and tot. if fromt is greater or equal to tot, the function does nothing. To remove a single data point with known t, use removeData(double t).
See Also
addData, clearData
Definition at line 17024 of file qcustomplot.cpp.
References mData.
void removeData (double t)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Removes a single data point at curve parameter t. If the position is not known with absolute precision, consider using removeData(double fromt, double tot) with a small fuzziness interval around the suspected position, depeding on the precision with which the curve parameter is known.
See Also
addData, clearData
Definition at line 17042 of file qcustomplot.cpp.
References mData.
void removeDataAfter (double t)
Removes all data points with curve parameter t greater than t.
See Also
addData, clearData
Definition at line 17009 of file qcustomplot.cpp.
References mData.
void removeDataBefore (double t)
Removes all data points with curve parameter t smaller than t.
See Also
addData, clearData
Definition at line 16998 of file qcustomplot.cpp.
References mData.
QCPScatterStyle scatterStyle () const inline
Definition at line 2681 of file qcustomplot.h.
double selectTest (const QPointF & pos, bool onlySelectable, QVariant * details = 0) const virtual
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
You may pass 0 as details to indicate that you are not interested in those selection details.
See Also
selectEvent, deselectEvent, QCustomPlot::setInteractions
Implements QCPAbstractPlottable.
Definition at line 17057 of file qcustomplot.cpp.
References mData, QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::mSelectable, QCPAbstractPlottable::mValueAxis, and pointDistance().
void setData (QCPCurveDataMap * data, bool copy = false)
Replaces the current data with the provided data.
If copy is set to true, data points in data will only be copied. if false, the plottable takes ownership of the passed data and replaces the internal data pointer with it. This is significantly faster than copying for large datasets.
Definition at line 16841 of file qcustomplot.cpp.
References data(), and mData.
void setData (const QVector< double > & t, const QVector< double > & key, const QVector< double > & value)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Replaces the current data with the provided points in t, key and value tuples. The provided vectors should have equal length. Else, the number of added points will be the size of the smallest vector.
Definition at line 16864 of file qcustomplot.cpp.
References mData, and QCPCurveData::t.
void setData (const QVector< double > & key, const QVector< double > & value)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Replaces the current data with the provided key and value pairs. The t parameter of each data point will be set to the integer index of the respective key/value pair.
Definition at line 16885 of file qcustomplot.cpp.
References mData, and QCPCurveData::t.
void setLineStyle (QCPCurve::LineStyle style)
Sets how the single data points are connected in the plot or how they are represented visually apart from the scatter symbol. For scatter-only plots, set style to lsNone and setScatterStyle to the desired scatter style.
See Also
setScatterStyle
Definition at line 16919 of file qcustomplot.cpp.
References mLineStyle.
Referenced by QCPCurve().
void setScatterStyle (const QCPScatterStyle & style)
Sets the visual appearance of single data points in the plot. If set to QCPScatterStyle::ssNone, no scatter points are drawn (e.g. for line-only plots with appropriate line style).
See Also
QCPScatterStyle, setLineStyle
Definition at line 16907 of file qcustomplot.cpp.
References mScatterStyle.
Referenced by QCPCurve().
Friends And Related Function Documentation
friend class QCPLegend friend
Definition at line 2732 of file qcustomplot.h.
friend class QCustomPlot friend
Definition at line 2731 of file qcustomplot.h.
Member Data Documentation
QCPCurveDataMap* mData protected
Definition at line 2708 of file qcustomplot.h.
Referenced by addData(), clearData(), draw(), getCurveData(), getKeyRange(), getValueRange(), pointDistance(), QCPCurve(), removeData(), removeDataAfter(), removeDataBefore(), selectTest(), setData(), and ~QCPCurve().
LineStyle mLineStyle protected
Definition at line 2710 of file qcustomplot.h.
Referenced by draw(), drawLegendIcon(), and setLineStyle().
QCPScatterStyle mScatterStyle protected
Definition at line 2709 of file qcustomplot.h.
Referenced by draw(), drawLegendIcon(), drawScatterPlot(), getCurveData(), and setScatterStyle().
The documentation for this class was generated from the following files:
qcustomplot.h
qcustomplot.cpp