SETestKCL: QCPGrid Class Reference
QCPGrid Class Reference
#include <qcustomplot.h>
Public Member Functions
QCPGrid (QCPAxis *parentAxis)
bool subGridVisible () const
bool antialiasedSubGrid () const
bool antialiasedZeroLine () const
QPen pen () const
QPen subGridPen () const
QPen zeroLinePen () const
void setSubGridVisible (bool visible)
void setAntialiasedSubGrid (bool enabled)
void setAntialiasedZeroLine (bool enabled)
void setPen (const QPen &pen)
void setSubGridPen (const QPen &pen)
void setZeroLinePen (const QPen &pen)
Public Member Functions inherited from QCPLayerable
QCPLayerable (QCustomPlot *plot, QString targetLayer=QString(), QCPLayerable *parentLayerable=0)
~QCPLayerable ()
bool visible () const
QCustomPlot * parentPlot () const
QCPLayerable * parentLayerable () const
QCPLayer * layer () const
bool antialiased () const
void setVisible (bool on)
Q_SLOT bool setLayer (QCPLayer *layer)
bool setLayer (const QString &layerName)
void setAntialiased (bool enabled)
virtual double selectTest (const QPointF &pos, bool onlySelectable, QVariant *details=0) const
bool realVisibility () const
Protected Member Functions
virtual void applyDefaultAntialiasingHint (QCPPainter *painter) const
virtual void draw (QCPPainter *painter)
void drawGridLines (QCPPainter *painter) const
void drawSubGridLines (QCPPainter *painter) const
Protected Member Functions inherited from QCPLayerable
virtual void parentPlotInitialized (QCustomPlot *parentPlot)
virtual QCP::Interaction selectionCategory () const
virtual QRect clipRect () const
virtual void selectEvent (QMouseEvent *event, bool additive, const QVariant &details, bool *selectionStateChanged)
virtual void deselectEvent (bool *selectionStateChanged)
void initializeParentPlot (QCustomPlot *parentPlot)
void setParentLayerable (QCPLayerable *parentLayerable)
bool moveToLayer (QCPLayer *layer, bool prepend)
void applyAntialiasingHint (QCPPainter *painter, bool localAntialiased, QCP::AntialiasedElement overrideElement) const
Protected Attributes
bool mSubGridVisible
bool mAntialiasedSubGrid
bool mAntialiasedZeroLine
QPen mPen
QPen mSubGridPen
QPen mZeroLinePen
QCPAxis * mParentAxis
Protected Attributes inherited from QCPLayerable
bool mVisible
QCustomPlot * mParentPlot
QPointer< QCPLayerable > mParentLayerable
QCPLayer * mLayer
bool mAntialiased
Friends
class QCPAxis
Additional Inherited Members
Signals inherited from QCPLayerable
void layerChanged (QCPLayer *newLayer)
Detailed Description
Responsible for drawing the grid of a QCPAxis.
This class is tightly bound to QCPAxis. Every axis owns a grid instance and uses it to draw the grid lines, sub grid lines and zero-line. You can interact with the grid of an axis via QCPAxis::grid. Normally, you don't need to create an instance of QCPGrid yourself.
The axis and grid drawing was split into two classes to allow them to be placed on different layers (both QCPAxis and QCPGrid inherit from QCPLayerable). Thus it is possible to have the grid in the background and the axes in the foreground, and any plottables/items in between. This described situation is the default setup, see the QCPLayer documentation.
Definition at line 930 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPGrid (QCPAxis * parentAxis)
Creates a QCPGrid instance and sets default values.
You shouldn't instantiate grids on their own, since every QCPAxis brings its own QCPGrid.
Definition at line 3673 of file qcustomplot.cpp.
References QCPLayerable::setAntialiased(), setAntialiasedSubGrid(), setAntialiasedZeroLine(), setPen(), setSubGridPen(), setSubGridVisible(), and setZeroLinePen().
Member Function Documentation
bool antialiasedSubGrid () const inline
Definition at line 946 of file qcustomplot.h.
bool antialiasedZeroLine () const inline
Definition at line 947 of file qcustomplot.h.
void applyDefaultAntialiasingHint (QCPPainter * painter) const protected virtual
Implements QCPLayerable.
Definition at line 3754 of file qcustomplot.cpp.
References QCP::aeGrid, QCPLayerable::applyAntialiasingHint(), and QCPLayerable::mAntialiased.
Referenced by drawGridLines().
void draw (QCPPainter * painter) protected virtual
Implements QCPLayerable.
Definition at line 3764 of file qcustomplot.cpp.
References drawGridLines(), drawSubGridLines(), mParentAxis, and mSubGridVisible.
void drawGridLines (QCPPainter * painter) const protected
Definition at line 3779 of file qcustomplot.cpp.
References QCP::aeZeroLine, QCPLayerable::applyAntialiasingHint(), applyDefaultAntialiasingHint(), QCPAxisRect::bottom(), QCPAxis::coordToPixel(), QCPPainter::drawLine(), QCPAxisRect::left(), QCPRange::lower, mAntialiasedZeroLine, QCPAxis::mAxisRect, QCPAxis::mHighestVisibleTick, QCPAxis::mLowestVisibleTick, mParentAxis, mPen, QCPAxis::mRange, QCPAxis::mTickVector, mZeroLinePen, QCPAxis::orientation(), QCPAxis::range(), QCPAxisRect::right(), QCPPainter::setPen(), QCPRange::size(), QCPAxisRect::top(), and QCPRange::upper.
Referenced by draw().
void drawSubGridLines (QCPPainter * painter) const protected
Definition at line 3853 of file qcustomplot.cpp.
References QCP::aeSubGrid, QCPLayerable::applyAntialiasingHint(), QCPAxisRect::bottom(), QCPAxis::coordToPixel(), QCPPainter::drawLine(), QCPAxisRect::left(), mAntialiasedSubGrid, QCPAxis::mAxisRect, mParentAxis, mSubGridPen, QCPAxis::mSubTickVector, QCPAxis::orientation(), QCPAxisRect::right(), QCPPainter::setPen(), and QCPAxisRect::top().
Referenced by draw().
QPen pen () const inline
Definition at line 948 of file qcustomplot.h.
Referenced by setPen(), setSubGridPen(), and setZeroLinePen().
void setAntialiasedSubGrid (bool enabled)
Sets whether sub grid lines are drawn antialiased.
Definition at line 3701 of file qcustomplot.cpp.
References mAntialiasedSubGrid.
Referenced by QCPGrid().
void setAntialiasedZeroLine (bool enabled)
Sets whether zero lines are drawn antialiased.
Definition at line 3709 of file qcustomplot.cpp.
References mAntialiasedZeroLine.
Referenced by QCPGrid().
void setPen (const QPen & pen)
Sets the pen with which (major) grid lines are drawn.
Definition at line 3717 of file qcustomplot.cpp.
References mPen, and pen().
Referenced by QCPGrid().
void setSubGridPen (const QPen & pen)
Sets the pen with which sub grid lines are drawn.
Definition at line 3725 of file qcustomplot.cpp.
References mSubGridPen, and pen().
Referenced by QCPGrid().
void setSubGridVisible (bool visible)
Sets whether grid lines at sub tick marks are drawn.
See Also
setSubGridPen
Definition at line 3693 of file qcustomplot.cpp.
References mSubGridVisible, and QCPLayerable::visible().
Referenced by QCPGrid().
void setZeroLinePen (const QPen & pen)
Sets the pen with which zero lines are drawn.
Zero lines are lines at value coordinate 0 which may be drawn with a different pen than other grid lines. To disable zero lines and just draw normal grid lines at zero, set pen to Qt::NoPen.
Definition at line 3736 of file qcustomplot.cpp.
References mZeroLinePen, and pen().
Referenced by QCPAxisRect::QCPAxisRect(), and QCPGrid().
QPen subGridPen () const inline
Definition at line 949 of file qcustomplot.h.
bool subGridVisible () const inline
Definition at line 945 of file qcustomplot.h.
QPen zeroLinePen () const inline
Definition at line 950 of file qcustomplot.h.
Friends And Related Function Documentation
friend class QCPAxis friend
Definition at line 976 of file qcustomplot.h.
Member Data Documentation
bool mAntialiasedSubGrid protected
Definition at line 963 of file qcustomplot.h.
Referenced by drawSubGridLines(), and setAntialiasedSubGrid().
bool mAntialiasedZeroLine protected
Definition at line 963 of file qcustomplot.h.
Referenced by drawGridLines(), and setAntialiasedZeroLine().
QCPAxis* mParentAxis protected
Definition at line 966 of file qcustomplot.h.
Referenced by draw(), drawGridLines(), and drawSubGridLines().
QPen mPen protected
Definition at line 964 of file qcustomplot.h.
Referenced by drawGridLines(), and setPen().
QPen mSubGridPen protected
Definition at line 964 of file qcustomplot.h.
Referenced by drawSubGridLines(), and setSubGridPen().
bool mSubGridVisible protected
Definition at line 962 of file qcustomplot.h.
Referenced by draw(), and setSubGridVisible().
QPen mZeroLinePen protected
Definition at line 964 of file qcustomplot.h.
Referenced by drawGridLines(), and setZeroLinePen().
The documentation for this class was generated from the following files:
qcustomplot.h
qcustomplot.cpp