SETestKCL: BinomialCalculator Class Reference
BinomialCalculator Class Reference
#include <BinomialCalculator.h>
Public Member Functions
BinomialCalculator ()
~BinomialCalculator ()
void SetNumberOfExperiments (unsigned int n)
unsigned int GetNumberOfExperiments (void) const
void SetProbabilityOfSuccess (float p)
float GetProbabilityOfSuccess (void) const
float GetProbabilityMassFunction (unsigned int k) const
Detailed Description
This class is a simple helper that embeds probability functionalities for a binomial distribution.
Two parameters for this class: NumberOfExperiments and ProbabilityOfSuccess
The class uses the Boost library (http://www.boost.org/) to retrieve the binomial coefficients needed for the calculation of the Mass function of a binomial distribution.
Note that for high value of N (typically N > 100), the binomial distribution is approximated to a Normal distribution.
The main method to retrieve the Mass function is GetProbabilityMassFunction() taking the number of successes as parameter
You can set the two parameters
Author
Nicolas Toussaint
Definition at line 29 of file BinomialCalculator.h.
Constructor & Destructor Documentation
BinomialCalculator (void)
Definition at line 8 of file BinomialCalculator.cpp.
~BinomialCalculator () inline
Definition at line 34 of file BinomialCalculator.h.
Member Function Documentation
unsigned int GetNumberOfExperiments (void) const inline
Get the number of experiments (parameter N of the binomial distribution)
Definition at line 47 of file BinomialCalculator.h.
Referenced by BinomialCalculatorTest().
float GetProbabilityMassFunction (unsigned int k) const
Get the probability mass function value for value k
Parameters
k The number of success amongst the experiments
Definition at line 15 of file BinomialCalculator.cpp.
Referenced by BinomialCalculatorTest(), and MainWindow::UpdateSummary().
float GetProbabilityOfSuccess (void) const inline
Get the probability of success (parameter p of the binomial distribution)
Definition at line 63 of file BinomialCalculator.h.
Referenced by BinomialCalculatorTest().
void SetNumberOfExperiments (unsigned int n) inline
Set the number of experiments (parameter N of the binomial distribution)
Definition at line 39 of file BinomialCalculator.h.
Referenced by BinomialCalculatorTest(), and MainWindow::UpdateSummary().
void SetProbabilityOfSuccess (float p) inline
Set the probability of success (parameter p of the binomial distribution)
Definition at line 54 of file BinomialCalculator.h.
Referenced by BinomialCalculatorTest(), and MainWindow::UpdateSummary().
The documentation for this class was generated from the following files:
BinomialCalculator.h
BinomialCalculator.cpp