SETestKCL: QCPLineEnding Class Reference
QCPLineEnding Class Reference
#include <qcustomplot.h>
Public Types
enum EndingStyle {
esNone, esFlatArrow, esSpikeArrow, esLineArrow,
esDisc, esSquare, esDiamond, esBar,
esHalfBar, esSkewedBar
}
Public Member Functions
QCPLineEnding ()
QCPLineEnding (EndingStyle style, double width=8, double length=10, bool inverted=false)
EndingStyle style () const
double width () const
double length () const
bool inverted () const
void setStyle (EndingStyle style)
void setWidth (double width)
void setLength (double length)
void setInverted (bool inverted)
double boundingDistance () const
double realLength () const
void draw (QCPPainter *painter, const QVector2D &pos, const QVector2D &dir) const
void draw (QCPPainter *painter, const QVector2D &pos, double angle) const
Protected Attributes
EndingStyle mStyle
double mWidth
double mLength
bool mInverted
Detailed Description
Handles the different ending decorations for line-like items.
The various ending styles currently supported
For every ending a line-like item has, an instance of this class exists. For example, QCPItemLine has two endings which can be set with QCPItemLine::setHead and QCPItemLine::setTail.
The styles themselves are defined via the enum QCPLineEnding::EndingStyle. Most decorations can be modified regarding width and length, see setWidth and setLength. The direction of the ending decoration (e.g. direction an arrow is pointing) is controlled by the line-like item. For example, when both endings of a QCPItemLine are set to be arrows, they will point to opposite directions, e.g. "outward". This can be changed by setInverted, which would make the respective arrow point inward.
Note that due to the overloaded QCPLineEnding constructor, you may directly specify a QCPLineEnding::EndingStyle where actually a QCPLineEnding is expected, e.g.
Definition at line 872 of file qcustomplot.h.
Member Enumeration Documentation
enum EndingStyle
Defines the type of ending decoration for line-like items, e.g. an arrow.
The width and length of these decorations can be controlled with the functions setWidth and setLength. Some decorations like esDisc, esSquare, esDiamond and esBar only support a width, the length property is ignored.
See Also
QCPItemLine::setHead, QCPItemLine::setTail, QCPItemCurve::setHead, QCPItemCurve::setTail, QCPAxis::setLowerEnding, QCPAxis::setUpperEnding
Enumerator
esNone
No ending decoration.
esFlatArrow
A filled arrow head with a straight/flat back (a triangle)
esSpikeArrow
A filled arrow head with an indented back.
esLineArrow
A non-filled arrow head with open back.
esDisc
A filled circle.
esSquare
A filled square.
esDiamond
A filled diamond (45° rotated square)
esBar
A bar perpendicular to the line.
esHalfBar
A bar perpendicular to the line, pointing out to only one side (to which side can be changed with setInverted)
esSkewedBar
A bar that is skewed (skew controllable via setLength)
Definition at line 888 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPLineEnding ()
Creates a QCPLineEnding instance with default values (style esNone).
Definition at line 3381 of file qcustomplot.cpp.
QCPLineEnding (QCPLineEnding::EndingStyle style, double width = 8, double length = 10, bool inverted = false)
Creates a QCPLineEnding instance with the specified values.
Definition at line 3392 of file qcustomplot.cpp.
Member Function Documentation
double boundingDistance () const
Definition at line 3452 of file qcustomplot.cpp.
References esBar, esDiamond, esDisc, esFlatArrow, esHalfBar, esLineArrow, esNone, esSkewedBar, esSpikeArrow, esSquare, mLength, mStyle, and mWidth.
Referenced by QCPItemLine::draw().
void draw (QCPPainter * painter, const QVector2D & pos, const QVector2D & dir) const
Definition at line 3517 of file qcustomplot.cpp.
References QCPPainter::drawLine(), esBar, esDiamond, esDisc, esFlatArrow, esHalfBar, esLineArrow, esNone, esSkewedBar, esSpikeArrow, esSquare, mInverted, mLength, QCPPainter::modes(), mStyle, mWidth, QCPPainter::pmNonCosmetic, and QCPPainter::setPen().
Referenced by draw(), QCPAxisPainterPrivate::draw(), QCPItemLine::draw(), and QCPItemCurve::draw().
void draw (QCPPainter * painter, const QVector2D & pos, double angle) const
Definition at line 3645 of file qcustomplot.cpp.
References draw().
bool inverted () const inline
Definition at line 907 of file qcustomplot.h.
Referenced by QCPAxisPainterPrivate::draw(), and setInverted().
double length () const inline
Definition at line 906 of file qcustomplot.h.
Referenced by setLength().
double realLength () const
Starting from the origin of this line ending (which is style specific), returns the length covered by the line ending symbol, in backward direction.
For example, the esSpikeArrow has a shorter real length than a esFlatArrow, even if both have the same setLength value, because the spike arrow has an inward curved back, which reduces the length along its center axis (the drawing origin for arrows is at the tip).
This function is used for precise, style specific placement of line endings, for example in QCPAxes.
Definition at line 3487 of file qcustomplot.cpp.
References esBar, esDiamond, esDisc, esFlatArrow, esHalfBar, esLineArrow, esNone, esSkewedBar, esSpikeArrow, esSquare, mLength, mStyle, and mWidth.
Referenced by QCPAxisPainterPrivate::draw().
void setInverted (bool inverted)
Sets whether the ending decoration shall be inverted. For example, an arrow decoration will point inward when inverted is set to true.
Note that also the width direction is inverted. For symmetrical ending styles like arrows or discs, this doesn't make a difference. However, asymmetric styles like esHalfBar are affected by it, which can be used to control to which side the half bar points to.
Definition at line 3438 of file qcustomplot.cpp.
References inverted(), and mInverted.
void setLength (double length)
Sets the length of the ending decoration, if the style supports it. On arrows, for example, the length defines the size in pointing direction.
See Also
setWidth
Definition at line 3425 of file qcustomplot.cpp.
References length(), and mLength.
void setStyle (QCPLineEnding::EndingStyle style)
Sets the style of the ending decoration.
Definition at line 3403 of file qcustomplot.cpp.
References mStyle, and style().
void setWidth (double width)
Sets the width of the ending decoration, if the style supports it. On arrows, for example, the width defines the size perpendicular to the arrow's pointing direction.
See Also
setLength
Definition at line 3414 of file qcustomplot.cpp.
References mWidth, and width().
EndingStyle style () const inline
Definition at line 904 of file qcustomplot.h.
Referenced by QCPAxisPainterPrivate::draw(), QCPItemLine::draw(), QCPItemCurve::draw(), and setStyle().
double width () const inline
Definition at line 905 of file qcustomplot.h.
Referenced by setWidth().
Member Data Documentation
bool mInverted protected
Definition at line 925 of file qcustomplot.h.
Referenced by draw(), and setInverted().
double mLength protected
Definition at line 924 of file qcustomplot.h.
Referenced by boundingDistance(), draw(), realLength(), and setLength().
EndingStyle mStyle protected
Definition at line 923 of file qcustomplot.h.
Referenced by boundingDistance(), draw(), realLength(), and setStyle().
double mWidth protected
Definition at line 924 of file qcustomplot.h.
Referenced by boundingDistance(), draw(), realLength(), and setWidth().
The documentation for this class was generated from the following files:
qcustomplot.h
qcustomplot.cpp