SETestKCL: QCPAbstractPlottable Class Reference
QCPAbstractPlottable Class Reference abstract
#include <qcustomplot.h>
Signals
void selectionChanged (bool selected)
void selectableChanged (bool selectable)
Signals inherited from QCPLayerable
void layerChanged (QCPLayer *newLayer)
Public Member Functions
QCPAbstractPlottable (QCPAxis *keyAxis, QCPAxis *valueAxis)
QString name () const
bool antialiasedFill () const
bool antialiasedScatters () const
bool antialiasedErrorBars () const
QPen pen () const
QPen selectedPen () const
QBrush brush () const
QBrush selectedBrush () const
QCPAxis * keyAxis () const
QCPAxis * valueAxis () const
bool selectable () const
bool selected () const
void setName (const QString &name)
void setAntialiasedFill (bool enabled)
void setAntialiasedScatters (bool enabled)
void setAntialiasedErrorBars (bool enabled)
void setPen (const QPen &pen)
void setSelectedPen (const QPen &pen)
void setBrush (const QBrush &brush)
void setSelectedBrush (const QBrush &brush)
void setKeyAxis (QCPAxis *axis)
void setValueAxis (QCPAxis *axis)
Q_SLOT void setSelectable (bool selectable)
Q_SLOT void setSelected (bool selected)
virtual void clearData ()=0
virtual double selectTest (const QPointF &pos, bool onlySelectable, QVariant *details=0) const =0
virtual bool addToLegend ()
virtual bool removeFromLegend () const
void rescaleAxes (bool onlyEnlarge=false) const
void rescaleKeyAxis (bool onlyEnlarge=false) const
void rescaleValueAxis (bool onlyEnlarge=false) const
Public Member Functions inherited from QCPLayerable
QCPLayerable (QCustomPlot *plot, QString targetLayer=QString(), QCPLayerable *parentLayerable=0)
~QCPLayerable ()
bool visible () const
QCustomPlot * parentPlot () const
QCPLayerable * parentLayerable () const
QCPLayer * layer () const
bool antialiased () const
void setVisible (bool on)
Q_SLOT bool setLayer (QCPLayer *layer)
bool setLayer (const QString &layerName)
void setAntialiased (bool enabled)
bool realVisibility () const
Protected Types
enum SignDomain { sdNegative, sdBoth, sdPositive }
Protected Member Functions
virtual QRect clipRect () const
virtual void draw (QCPPainter *painter)=0
virtual QCP::Interaction selectionCategory () const
void applyDefaultAntialiasingHint (QCPPainter *painter) const
virtual void selectEvent (QMouseEvent *event, bool additive, const QVariant &details, bool *selectionStateChanged)
virtual void deselectEvent (bool *selectionStateChanged)
virtual void drawLegendIcon (QCPPainter *painter, const QRectF &rect) const =0
virtual QCPRange getKeyRange (bool &foundRange, SignDomain inSignDomain=sdBoth) const =0
virtual QCPRange getValueRange (bool &foundRange, SignDomain inSignDomain=sdBoth) const =0
void coordsToPixels (double key, double value, double &x, double &y) const
const QPointF coordsToPixels (double key, double value) const
void pixelsToCoords (double x, double y, double &key, double &value) const
void pixelsToCoords (const QPointF &pixelPos, double &key, double &value) const
QPen mainPen () const
QBrush mainBrush () const
void applyFillAntialiasingHint (QCPPainter *painter) const
void applyScattersAntialiasingHint (QCPPainter *painter) const
void applyErrorBarsAntialiasingHint (QCPPainter *painter) const
double distSqrToLine (const QPointF &start, const QPointF &end, const QPointF &point) const
Protected Member Functions inherited from QCPLayerable
virtual void parentPlotInitialized (QCustomPlot *parentPlot)
void initializeParentPlot (QCustomPlot *parentPlot)
void setParentLayerable (QCPLayerable *parentLayerable)
bool moveToLayer (QCPLayer *layer, bool prepend)
void applyAntialiasingHint (QCPPainter *painter, bool localAntialiased, QCP::AntialiasedElement overrideElement) const
Protected Attributes
QString mName
bool mAntialiasedFill
bool mAntialiasedScatters
bool mAntialiasedErrorBars
QPen mPen
QPen mSelectedPen
QBrush mBrush
QBrush mSelectedBrush
QPointer< QCPAxis > mKeyAxis
QPointer< QCPAxis > mValueAxis
bool mSelectable
bool mSelected
Protected Attributes inherited from QCPLayerable
bool mVisible
QCustomPlot * mParentPlot
QPointer< QCPLayerable > mParentLayerable
QCPLayer * mLayer
bool mAntialiased
Friends
class QCustomPlot
class QCPAxis
class QCPPlottableLegendItem
Detailed Description
The abstract base class for all data representing objects in a plot.
It defines a very basic interface like name, pen, brush, visibility etc. Since this class is abstract, it can't be instantiated. Use one of the subclasses or create a subclass yourself to create new ways of displaying data (see "Creating own plottables" below).
All further specifics are in the subclasses, for example:
A normal graph with possibly a line, scatter points and error bars: QCPGraph (typically created with QCustomPlot::addGraph)
A parametric curve: QCPCurve
A bar chart: QCPBars
A statistical box plot: QCPStatisticalBox
A color encoded two-dimensional map: QCPColorMap
An OHLC/Candlestick chart: QCPFinancial
Creating own plottables
To create an own plottable, you implement a subclass of QCPAbstractPlottable. These are the pure virtual functions, you must implement:
clearData
selectTest
draw
drawLegendIcon
getKeyRange
getValueRange
See the documentation of those functions for what they need to do.
For drawing your plot, you can use the coordsToPixels functions to translate a point in plot coordinates to pixel coordinates. This function is quite convenient, because it takes the orientation of the key and value axes into account for you (x and y are swapped when the key axis is vertical and the value axis horizontal). If you are worried about performance (i.e. you need to translate many points in a loop like QCPGraph), you can directly use QCPAxis::coordToPixel. However, you must then take care about the orientation of the axis yourself.
Here are some important members you inherit from QCPAbstractPlottable:
QCustomPlot *mParentPlot A pointer to the parent QCustomPlot instance. The parent plot is inferred from the axes that are passed in the constructor.
QString mName The name of the plottable.
QPen mPen The generic pen of the plottable. You should use this pen for the most prominent data representing lines in the plottable (e.g QCPGraph uses this pen for its graph lines and scatters)
QPen mSelectedPen The generic pen that should be used when the plottable is selected (hint: mainPen gives you the right pen, depending on selection state).
QBrush mBrush The generic brush of the plottable. You should use this brush for the most prominent fillable structures in the plottable (e.g. QCPGraph uses this brush to control filling under the graph)
QBrush mSelectedBrush The generic brush that should be used when the plottable is selected (hint: mainBrush gives you the right brush, depending on selection state).
QPointer<QCPAxis>mKeyAxis, mValueAxis The key and value axes this plottable is attached to. Call their QCPAxis::coordToPixel functions to translate coordinates to pixels in either the key or value dimension. Make sure to check whether the pointer is null before using it. If one of the axes is null, don't draw the plottable.
bool mSelected indicates whether the plottable is selected or not.
Definition at line 1388 of file qcustomplot.h.
Member Enumeration Documentation
enum SignDomain protected
Represents negative and positive sign domain for passing to getKeyRange and getValueRange.
Enumerator
sdNegative
The negative sign domain, i.e. numbers smaller than zero.
sdBoth
Both sign domains, including zero, i.e. all (rational) numbers.
sdPositive
The positive sign domain, i.e. numbers greater than zero.
Definition at line 1455 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPAbstractPlottable (QCPAxis * keyAxis, QCPAxis * valueAxis)
Constructs an abstract plottable which uses keyAxis as its key axis ("x") and valueAxis as its value axis ("y"). keyAxis and valueAxis must reside in the same QCustomPlot instance and have perpendicular orientations. If either of these restrictions is violated, a corresponding message is printed to the debug output (qDebug), the construction is not aborted, though.
Since QCPAbstractPlottable is an abstract class that defines the basic interface to plottables, it can't be directly instantiated.
You probably want one of the subclasses like QCPGraph or QCPCurve instead.
Definition at line 6840 of file qcustomplot.cpp.
References QCPAxis::orientation(), and QCPLayerable::parentPlot().
Member Function Documentation
bool addToLegend () virtual
Adds this plottable to the legend of the parent QCustomPlot (QCustomPlot::legend).
Normally, a QCPPlottableLegendItem is created and inserted into the legend. If the plottable needs a more specialized representation in the legend, this function will take this into account and instead create the specialized subclass of QCPAbstractLegendItem.
Returns true on success, i.e. when the legend exists and a legend item associated with this plottable isn't already in the legend.
See Also
removeFromLegend, QCPLegend::addItem
Definition at line 7134 of file qcustomplot.cpp.
References QCPLegend::addItem(), QCPLegend::hasItemWithPlottable(), QCustomPlot::legend, QCPLayerable::mParentPlot, and QCPPlottableLegendItem.
Referenced by QCustomPlot::addPlottable().
bool antialiasedErrorBars () const inline
Definition at line 1412 of file qcustomplot.h.
bool antialiasedFill () const inline
Definition at line 1410 of file qcustomplot.h.
bool antialiasedScatters () const inline
Definition at line 1411 of file qcustomplot.h.
void applyDefaultAntialiasingHint (QCPPainter * painter) const protected virtual
Implements QCPLayerable.
Definition at line 7297 of file qcustomplot.cpp.
References QCP::aePlottables, QCPLayerable::applyAntialiasingHint(), and QCPLayerable::mAntialiased.
Referenced by QCPCurve::draw(), QCPBars::draw(), QCPColorMap::draw(), QCPGraph::drawImpulsePlot(), QCPGraph::drawLegendIcon(), QCPCurve::drawLegendIcon(), QCPBars::drawLegendIcon(), QCPStatisticalBox::drawLegendIcon(), QCPColorMap::drawLegendIcon(), QCPGraph::drawLinePlot(), QCPStatisticalBox::drawMedian(), and QCPStatisticalBox::drawQuartileBox().
void applyErrorBarsAntialiasingHint (QCPPainter * painter) const protected
Definition at line 7345 of file qcustomplot.cpp.
References QCP::aeErrorBars, QCPLayerable::applyAntialiasingHint(), and mAntialiasedErrorBars.
Referenced by QCPGraph::drawScatterPlot(), and QCPStatisticalBox::drawWhiskers().
void applyFillAntialiasingHint (QCPPainter * painter) const protected
Definition at line 7313 of file qcustomplot.cpp.
References QCP::aeFills, QCPLayerable::applyAntialiasingHint(), and mAntialiasedFill.
Referenced by QCPCurve::draw(), QCPBars::draw(), QCPGraph::drawFill(), QCPGraph::drawLegendIcon(), and QCPCurve::drawLegendIcon().
void applyScattersAntialiasingHint (QCPPainter * painter) const protected
Definition at line 7329 of file qcustomplot.cpp.
References QCP::aeScatters, QCPLayerable::applyAntialiasingHint(), and mAntialiasedScatters.
Referenced by QCPGraph::drawLegendIcon(), QCPCurve::drawLegendIcon(), QCPStatisticalBox::drawOutliers(), QCPGraph::drawScatterPlot(), and QCPCurve::drawScatterPlot().
QBrush brush () const inline
Definition at line 1415 of file qcustomplot.h.
Referenced by setBrush(), QCPFinancial::setBrushNegative(), QCPFinancial::setBrushPositive(), and setSelectedBrush().
void clearData () pure virtual
Clears all data in the plottable.
Implemented in QCPFinancial, QCPColorMap, QCPStatisticalBox, QCPBars, QCPCurve, and QCPGraph.
QRect clipRect () const protected virtual
Reimplemented from QCPLayerable.
Definition at line 7169 of file qcustomplot.cpp.
References mKeyAxis, and mValueAxis.
void coordsToPixels (double key, double value, double & x, double & y) const protected
Definition at line 7193 of file qcustomplot.cpp.
References QCPAxis::coordToPixel(), keyAxis(), mKeyAxis, mValueAxis, QCPAxis::orientation(), and valueAxis().
Referenced by QCPColorMap::draw(), QCPStatisticalBox::drawMedian(), QCPStatisticalBox::drawOutliers(), QCPStatisticalBox::drawQuartileBox(), QCPStatisticalBox::drawWhiskers(), QCPCurve::getCurveData(), QCPCurve::getOptimizedCornerPoints(), QCPCurve::getOptimizedPoint(), QCPCurve::getTraverse(), QCPCurve::getTraverseCornerPoints(), QCPGraph::pointDistance(), and QCPCurve::pointDistance().
const QPointF coordsToPixels (double key, double value) const protected
Definition at line 7215 of file qcustomplot.cpp.
References QCPAxis::coordToPixel(), keyAxis(), mKeyAxis, mValueAxis, QCPAxis::orientation(), and valueAxis().
void deselectEvent (bool * selectionStateChanged) protected virtual
Reimplemented from QCPLayerable.
Definition at line 7396 of file qcustomplot.cpp.
References mSelectable, mSelected, and setSelected().
double distSqrToLine (const QPointF & start, const QPointF & end, const QPointF & point) const protected
Definition at line 7360 of file qcustomplot.cpp.
Referenced by QCPFinancial::candlestickSelectTest(), QCPFinancial::ohlcSelectTest(), QCPGraph::pointDistance(), and QCPCurve::pointDistance().
virtual void draw (QCPPainter * painter) protected pure virtual
Implements QCPLayerable.
Implemented in QCPFinancial, QCPColorMap, QCPStatisticalBox, QCPBars, QCPCurve, and QCPGraph.
void drawLegendIcon (QCPPainter * painter, const QRectF & rect) const protected pure virtual
Implemented in QCPFinancial, QCPColorMap, QCPStatisticalBox, QCPBars, QCPCurve, and QCPGraph.
Referenced by QCPPlottableLegendItem::draw().
QCPRange getKeyRange (bool & foundRange, SignDomain inSignDomain = sdBoth) const protected pure virtual
Implemented in QCPFinancial, QCPColorMap, QCPStatisticalBox, QCPBars, QCPCurve, and QCPGraph.
Referenced by rescaleKeyAxis().
QCPRange getValueRange (bool & foundRange, SignDomain inSignDomain = sdBoth) const protected pure virtual
Implemented in QCPFinancial, QCPColorMap, QCPStatisticalBox, QCPBars, QCPCurve, and QCPGraph.
Referenced by rescaleValueAxis().
QCPAxis* keyAxis () const inline
Definition at line 1417 of file qcustomplot.h.
Referenced by QCPFinancial::candlestickSelectTest(), coordsToPixels(), QCPColorMap::draw(), QCPFinancial::drawCandlestickPlot(), QCPGraph::drawError(), QCPFinancial::drawOhlcPlot(), QCPGraph::drawScatterPlot(), QCPBars::getBarPolygon(), QCPGraph::getChannelFillPolygon(), QCPCurve::getCurveData(), QCPGraph::getImpulsePlotData(), QCPGraph::getLinePlotData(), QCPBarsGroup::getPixelSpacing(), QCPGraph::getPreparedData(), QCPGraph::getStepCenterPlotData(), QCPGraph::getStepLeftPlotData(), QCPGraph::getStepRightPlotData(), QCPGraph::lowerFillBasePoint(), QCPBars::moveAbove(), QCPBars::moveBelow(), QCPFinancial::ohlcSelectTest(), pixelsToCoords(), QCustomPlot::plottableAt(), rescaleKeyAxis(), QCPGraph::rescaleKeyAxis(), QCPItemTracer::setGraph(), QCPColorMap::updateLegendIcon(), QCPColorMap::updateMapImage(), and QCPGraph::upperFillBasePoint().
QBrush mainBrush () const protected
Definition at line 7279 of file qcustomplot.cpp.
References mBrush, mSelected, and mSelectedBrush.
Referenced by QCPCurve::draw(), QCPBars::draw(), QCPGraph::drawFill(), and QCPStatisticalBox::drawQuartileBox().
QPen mainPen () const protected
Definition at line 7269 of file qcustomplot.cpp.
References mPen, mSelected, and mSelectedPen.
Referenced by QCPCurve::draw(), QCPBars::draw(), QCPGraph::drawImpulsePlot(), QCPGraph::drawLinePlot(), QCPStatisticalBox::drawQuartileBox(), and QCPCurve::getCurveData().
QString name () const inline
Definition at line 1409 of file qcustomplot.h.
Referenced by QCPPlottableLegendItem::draw(), QCPGraph::draw(), QCPCurve::draw(), QCPBars::draw(), QCPStatisticalBox::draw(), QCPPlottableLegendItem::minimumSizeHint(), and setName().
QPen pen () const inline
Definition at line 1413 of file qcustomplot.h.
Referenced by QCPGraph::drawImpulsePlot(), QCPGraph::setErrorPen(), QCPStatisticalBox::setMedianPen(), setPen(), QCPFinancial::setPenNegative(), QCPFinancial::setPenPositive(), setSelectedPen(), QCPStatisticalBox::setWhiskerBarPen(), and QCPStatisticalBox::setWhiskerPen().
void pixelsToCoords (double x, double y, double & key, double & value) const protected
Definition at line 7237 of file qcustomplot.cpp.
References keyAxis(), mKeyAxis, mValueAxis, QCPAxis::orientation(), QCPAxis::pixelToCoord(), and valueAxis().
Referenced by QCPFinancial::candlestickSelectTest(), pixelsToCoords(), QCPStatisticalBox::selectTest(), and QCPColorMap::selectTest().
void pixelsToCoords (const QPointF & pixelPos, double & key, double & value) const protected
Definition at line 7259 of file qcustomplot.cpp.
References pixelsToCoords().
bool removeFromLegend () const virtual
Removes the plottable from the legend of the parent QCustomPlot. This means the QCPAbstractLegendItem (usually a QCPPlottableLegendItem) that is associated with this plottable is removed.
Returns true on success, i.e. if the legend exists and a legend item associated with this plottable was found and removed.
See Also
addToLegend, QCPLegend::removeItem
Definition at line 7157 of file qcustomplot.cpp.
References QCPLegend::itemWithPlottable(), QCustomPlot::legend, QCPLayerable::mParentPlot, and QCPLegend::removeItem().
Referenced by QCustomPlot::removePlottable().
void rescaleAxes (bool onlyEnlarge = false) const
Rescales the key and value axes associated with this plottable to contain all displayed data, so the whole plottable is visible. If the scaling of an axis is logarithmic, rescaleAxes will make sure not to rescale to an illegal range i.e. a range containing different signs and/or zero. Instead it will stay in the current sign domain and ignore all parts of the plottable that lie outside of that domain.
onlyEnlarge makes sure the ranges are only expanded, never reduced. So it's possible to show multiple plottables in their entirety by multiple calls to rescaleAxes where the first call has onlyEnlarge set to false (the default), and all subsequent set to true.
See Also
rescaleKeyAxis, rescaleValueAxis, QCustomPlot::rescaleAxes, QCPAxis::rescale
Definition at line 7039 of file qcustomplot.cpp.
References rescaleKeyAxis(), and rescaleValueAxis().
void rescaleKeyAxis (bool onlyEnlarge = false) const
Rescales the key axis of the plottable so the whole plottable is visible.
See rescaleAxes for detailed behaviour.
Definition at line 7050 of file qcustomplot.cpp.
References QCPRange::expand(), getKeyRange(), keyAxis(), QCPRange::lower, mKeyAxis, QCPAxis::range(), QCPAxis::scaleType(), sdBoth, sdNegative, sdPositive, QCPAxis::setRange(), QCPRange::size(), QCPAxis::stLinear, QCPAxis::stLogarithmic, QCPRange::upper, and QCPRange::validRange().
Referenced by rescaleAxes().
void rescaleValueAxis (bool onlyEnlarge = false) const
Rescales the value axis of the plottable so the whole plottable is visible.
Returns true if the axis was actually scaled. This might not be the case if this plottable has an invalid range, e.g. because it has no data points.
See rescaleAxes for detailed behaviour.
Definition at line 7090 of file qcustomplot.cpp.
References QCPRange::expand(), getValueRange(), QCPRange::lower, mValueAxis, QCPAxis::range(), QCPAxis::scaleType(), sdBoth, sdNegative, sdPositive, QCPAxis::setRange(), QCPRange::size(), QCPAxis::stLinear, QCPAxis::stLogarithmic, QCPRange::upper, QCPRange::validRange(), and valueAxis().
Referenced by rescaleAxes().
bool selectable () const inline
Definition at line 1419 of file qcustomplot.h.
Referenced by QCustomPlot::plottableAt(), and setSelectable().
void selectableChanged (bool selectable) signal
This signal is emitted when the selectability of this plottable has changed.
See Also
setSelectable
Referenced by setSelectable().
bool selected () const inline
Definition at line 1420 of file qcustomplot.h.
Referenced by QCustomPlot::selectedGraphs(), QCustomPlot::selectedPlottables(), and setSelected().
QBrush selectedBrush () const inline
Definition at line 1416 of file qcustomplot.h.
QPen selectedPen () const inline
Definition at line 1414 of file qcustomplot.h.
void selectEvent (QMouseEvent * event, bool additive, const QVariant & details, bool * selectionStateChanged) protected virtual
Reimplemented from QCPLayerable.
Definition at line 7382 of file qcustomplot.cpp.
References mSelectable, mSelected, and setSelected().
QCP::Interaction selectionCategory () const protected virtual
Reimplemented from QCPLayerable.
Definition at line 7178 of file qcustomplot.cpp.
References QCP::iSelectPlottables.
void selectionChanged (bool selected) signal
This signal is emitted when the selection state of this plottable has changed, either by user interaction or by a direct call to setSelected.
Referenced by setSelected().
virtual double selectTest (const QPointF & pos, bool onlySelectable, QVariant * details = 0) const pure virtual
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
You may pass 0 as details to indicate that you are not interested in those selection details.
See Also
selectEvent, deselectEvent, QCustomPlot::setInteractions
Reimplemented from QCPLayerable.
Implemented in QCPFinancial, QCPColorMap, QCPStatisticalBox, QCPBars, QCPCurve, and QCPGraph.
Referenced by QCustomPlot::plottableAt().
void setAntialiasedErrorBars (bool enabled)
Sets whether the error bars of this plottable are drawn antialiased or not.
Note that this setting may be overridden by QCustomPlot::setAntialiasedElements and QCustomPlot::setNotAntialiasedElements.
Definition at line 6898 of file qcustomplot.cpp.
References mAntialiasedErrorBars.
void setAntialiasedFill (bool enabled)
Sets whether fills of this plottable are drawn antialiased or not.
Note that this setting may be overridden by QCustomPlot::setAntialiasedElements and QCustomPlot::setNotAntialiasedElements.
Definition at line 6876 of file qcustomplot.cpp.
References mAntialiasedFill.
void setAntialiasedScatters (bool enabled)
Sets whether the scatter symbols of this plottable are drawn antialiased or not.
Note that this setting may be overridden by QCustomPlot::setAntialiasedElements and QCustomPlot::setNotAntialiasedElements.
Definition at line 6887 of file qcustomplot.cpp.
References mAntialiasedScatters.
void setBrush (const QBrush & brush)
The brush is used to draw basic fills of the plottable representation in the plot. The Fill can be a color, gradient or texture, see the usage of QBrush.
For example, the QCPGraph subclass draws the fill under the graph with this brush, when it's not set to Qt::NoBrush.
See Also
setPen
Definition at line 6937 of file qcustomplot.cpp.
References brush(), and mBrush.
Referenced by QCPGraph::QCPGraph(), and QCPStatisticalBox::QCPStatisticalBox().
void setKeyAxis (QCPAxis * axis)
The key axis of a plottable can be set to any axis of a QCustomPlot, as long as it is orthogonal to the plottable's value axis. This function performs no checks to make sure this is the case. The typical mathematical choice is to use the x-axis (QCustomPlot::xAxis) as key axis and the y-axis (QCustomPlot::yAxis) as value axis.
Normally, the key and value axes are set in the constructor of the plottable (or QCustomPlot::addGraph when working with QCPGraphs through the dedicated graph interface).
See Also
setValueAxis
Definition at line 6964 of file qcustomplot.cpp.
References mKeyAxis.
void setName (const QString & name)
The name is the textual representation of this plottable as it is displayed in the legend (QCPLegend). It may contain any UTF-8 characters, including newlines.
Definition at line 6865 of file qcustomplot.cpp.
References mName, and name().
Referenced by QCustomPlot::addGraph().
void setPen (const QPen & pen)
The pen is used to draw basic lines that make up the plottable representation in the plot.
For example, the QCPGraph subclass draws its graph lines with this pen.
See Also
setBrush
Definition at line 6912 of file qcustomplot.cpp.
References mPen, and pen().
Referenced by QCPGraph::QCPGraph(), and QCPStatisticalBox::QCPStatisticalBox().
void setSelectable (bool selectable)
Sets whether the user can (de-)select this plottable by clicking on the QCustomPlot surface. (When QCustomPlot::setInteractions contains iSelectPlottables.)
However, even when selectable was set to false, it is possible to set the selection manually, by calling setSelected directly.
See Also
setSelected
Definition at line 6994 of file qcustomplot.cpp.
References mSelectable, selectable(), and selectableChanged().
void setSelected (bool selected)
Sets whether this plottable is selected or not. When selected, it uses a different pen and brush to draw its lines and fills, see setSelectedPen and setSelectedBrush.
The entire selection mechanism for plottables is handled automatically when QCustomPlot::setInteractions contains iSelectPlottables. You only need to call this function when you wish to change the selection state manually.
This function can change the selection state even when setSelectable was set to false.
emits the selectionChanged signal when selected is different from the previous selection state.
See Also
setSelectable, selectTest
Definition at line 7017 of file qcustomplot.cpp.
References mSelected, selected(), and selectionChanged().
Referenced by deselectEvent(), and selectEvent().
void setSelectedBrush (const QBrush & brush)
When the plottable is selected, this brush is used to draw fills instead of the normal brush set via setBrush.
See Also
setSelected, setSelectable, setSelectedPen, selectTest
Definition at line 6948 of file qcustomplot.cpp.
References brush(), and mSelectedBrush.
Referenced by QCPFinancial::QCPFinancial(), QCPGraph::QCPGraph(), and QCPStatisticalBox::QCPStatisticalBox().
void setSelectedPen (const QPen & pen)
When the plottable is selected, this pen is used to draw basic lines instead of the normal pen set via setPen.
See Also
setSelected, setSelectable, setSelectedBrush, selectTest
Definition at line 6923 of file qcustomplot.cpp.
References mSelectedPen, and pen().
Referenced by QCPFinancial::QCPFinancial(), QCPGraph::QCPGraph(), and QCPStatisticalBox::QCPStatisticalBox().
void setValueAxis (QCPAxis * axis)
The value axis of a plottable can be set to any axis of a QCustomPlot, as long as it is orthogonal to the plottable's key axis. This function performs no checks to make sure this is the case. The typical mathematical choice is to use the x-axis (QCustomPlot::xAxis) as key axis and the y-axis (QCustomPlot::yAxis) as value axis.
Normally, the key and value axes are set in the constructor of the plottable (or QCustomPlot::addGraph when working with QCPGraphs through the dedicated graph interface).
See Also
setKeyAxis
Definition at line 6980 of file qcustomplot.cpp.
References mValueAxis.
QCPAxis* valueAxis () const inline
Definition at line 1418 of file qcustomplot.h.
Referenced by QCPFinancial::candlestickSelectTest(), coordsToPixels(), QCPColorMap::draw(), QCPFinancial::drawCandlestickPlot(), QCPGraph::drawError(), QCPFinancial::drawOhlcPlot(), QCPGraph::drawScatterPlot(), QCPBars::getBarPolygon(), QCPGraph::getChannelFillPolygon(), QCPCurve::getCurveData(), QCPGraph::getImpulsePlotData(), QCPGraph::getLinePlotData(), QCPGraph::getPreparedData(), QCPGraph::getStepCenterPlotData(), QCPGraph::getStepLeftPlotData(), QCPGraph::getStepRightPlotData(), QCPGraph::lowerFillBasePoint(), QCPBars::moveAbove(), QCPBars::moveBelow(), QCPFinancial::ohlcSelectTest(), pixelsToCoords(), QCustomPlot::plottableAt(), rescaleValueAxis(), QCPGraph::rescaleValueAxis(), QCPItemTracer::setGraph(), QCPColorMap::updateLegendIcon(), and QCPGraph::upperFillBasePoint().
Friends And Related Function Documentation
friend class QCPAxis friend
Definition at line 1498 of file qcustomplot.h.
friend class QCPPlottableLegendItem friend
Definition at line 1499 of file qcustomplot.h.
Referenced by addToLegend().
friend class QCustomPlot friend
Definition at line 1497 of file qcustomplot.h.
Member Data Documentation
bool mAntialiasedErrorBars protected
Definition at line 1462 of file qcustomplot.h.
Referenced by applyErrorBarsAntialiasingHint(), and setAntialiasedErrorBars().
bool mAntialiasedFill protected
Definition at line 1462 of file qcustomplot.h.
Referenced by applyFillAntialiasingHint(), and setAntialiasedFill().
bool mAntialiasedScatters protected
Definition at line 1462 of file qcustomplot.h.
Referenced by applyScattersAntialiasingHint(), and setAntialiasedScatters().
QBrush mBrush protected
Definition at line 1464 of file qcustomplot.h.
Referenced by QCPFinancial::drawCandlestickPlot(), QCPGraph::drawLegendIcon(), QCPCurve::drawLegendIcon(), QCPBars::drawLegendIcon(), QCPStatisticalBox::drawLegendIcon(), QCPFinancial::drawLegendIcon(), mainBrush(), QCPBars::QCPBars(), QCPCurve::QCPCurve(), and setBrush().
QPointer<QCPAxis> mKeyAxis protected
Definition at line 1465 of file qcustomplot.h.
Referenced by QCPGraph::addFillBasePoints(), QCPFinancial::candlestickSelectTest(), clipRect(), coordsToPixels(), QCPGraph::draw(), QCPBars::draw(), QCPStatisticalBox::draw(), QCPColorMap::draw(), QCPFinancial::drawCandlestickPlot(), QCPGraph::drawError(), QCPFinancial::drawOhlcPlot(), QCPGraph::drawScatterPlot(), QCPBars::getBarPolygon(), QCPGraph::getChannelFillPolygon(), QCPCurve::getCurveData(), QCPGraph::getImpulsePlotData(), QCPBars::getKeyRange(), QCPFinancial::getKeyRange(), QCPGraph::getLinePlotData(), QCPBars::getPixelWidth(), QCPGraph::getPreparedData(), QCPGraph::getStepCenterPlotData(), QCPGraph::getStepLeftPlotData(), QCPGraph::getStepRightPlotData(), QCPGraph::getVisibleDataBounds(), QCPBars::getVisibleDataBounds(), QCPFinancial::getVisibleDataBounds(), QCPGraph::lowerFillBasePoint(), QCPBars::moveAbove(), QCPBars::moveBelow(), QCPFinancial::ohlcSelectTest(), pixelsToCoords(), rescaleKeyAxis(), QCPGraph::rescaleKeyAxis(), QCPGraph::selectTest(), QCPCurve::selectTest(), QCPBars::selectTest(), QCPStatisticalBox::selectTest(), QCPColorMap::selectTest(), QCPFinancial::selectTest(), setKeyAxis(), QCPColorMap::updateMapImage(), and QCPGraph::upperFillBasePoint().
QString mName protected
Definition at line 1461 of file qcustomplot.h.
Referenced by QCPCurve::pointDistance(), and setName().
QPen mPen protected
Definition at line 1463 of file qcustomplot.h.
Referenced by QCPFinancial::drawCandlestickPlot(), QCPGraph::drawLegendIcon(), QCPCurve::drawLegendIcon(), QCPBars::drawLegendIcon(), QCPStatisticalBox::drawLegendIcon(), QCPFinancial::drawLegendIcon(), QCPFinancial::drawOhlcPlot(), QCPStatisticalBox::drawOutliers(), QCPGraph::drawScatterPlot(), QCPCurve::drawScatterPlot(), mainPen(), QCPBars::QCPBars(), QCPCurve::QCPCurve(), and setPen().
bool mSelectable protected
Definition at line 1466 of file qcustomplot.h.
Referenced by deselectEvent(), selectEvent(), QCPGraph::selectTest(), QCPCurve::selectTest(), QCPBars::selectTest(), QCPStatisticalBox::selectTest(), QCPColorMap::selectTest(), QCPFinancial::selectTest(), and setSelectable().
bool mSelected protected
Definition at line 1466 of file qcustomplot.h.
Referenced by deselectEvent(), QCPFinancial::drawCandlestickPlot(), QCPFinancial::drawOhlcPlot(), mainBrush(), mainPen(), selectEvent(), and setSelected().
QBrush mSelectedBrush protected
Definition at line 1464 of file qcustomplot.h.
Referenced by QCPFinancial::drawCandlestickPlot(), mainBrush(), QCPBars::QCPBars(), QCPCurve::QCPCurve(), and setSelectedBrush().
QPen mSelectedPen protected
Definition at line 1463 of file qcustomplot.h.
Referenced by QCPFinancial::drawCandlestickPlot(), QCPFinancial::drawOhlcPlot(), mainPen(), QCPBars::QCPBars(), QCPCurve::QCPCurve(), and setSelectedPen().
QPointer<QCPAxis> mValueAxis protected
Definition at line 1465 of file qcustomplot.h.
Referenced by QCPFinancial::candlestickSelectTest(), clipRect(), coordsToPixels(), QCPGraph::draw(), QCPBars::draw(), QCPStatisticalBox::draw(), QCPColorMap::draw(), QCPFinancial::drawCandlestickPlot(), QCPGraph::drawError(), QCPFinancial::drawOhlcPlot(), QCPGraph::drawScatterPlot(), QCPBars::getBarPolygon(), QCPGraph::getChannelFillPolygon(), QCPCurve::getCurveData(), QCPGraph::getImpulsePlotData(), QCPGraph::getLinePlotData(), QCPGraph::getPreparedData(), QCPGraph::getStepCenterPlotData(), QCPGraph::getStepLeftPlotData(), QCPGraph::getStepRightPlotData(), QCPGraph::lowerFillBasePoint(), QCPBars::moveAbove(), QCPBars::moveBelow(), QCPFinancial::ohlcSelectTest(), pixelsToCoords(), rescaleValueAxis(), QCPGraph::rescaleValueAxis(), QCPGraph::selectTest(), QCPCurve::selectTest(), QCPBars::selectTest(), QCPStatisticalBox::selectTest(), QCPColorMap::selectTest(), QCPFinancial::selectTest(), setValueAxis(), and QCPGraph::upperFillBasePoint().
The documentation for this class was generated from the following files:
qcustomplot.h
qcustomplot.cpp