SETestKCL: QCustomPlot Class Reference
QCustomPlot Class Reference
#include <qcustomplot.h>
Public Types
enum LayerInsertMode { limBelow, limAbove }
enum RefreshPriority { rpImmediate, rpQueued, rpHint }
Signals
void mouseDoubleClick (QMouseEvent *event)
void mousePress (QMouseEvent *event)
void mouseMove (QMouseEvent *event)
void mouseRelease (QMouseEvent *event)
void mouseWheel (QWheelEvent *event)
void plottableClick (QCPAbstractPlottable *plottable, QMouseEvent *event)
void plottableDoubleClick (QCPAbstractPlottable *plottable, QMouseEvent *event)
void itemClick (QCPAbstractItem *item, QMouseEvent *event)
void itemDoubleClick (QCPAbstractItem *item, QMouseEvent *event)
void axisClick (QCPAxis *axis, QCPAxis::SelectablePart part, QMouseEvent *event)
void axisDoubleClick (QCPAxis *axis, QCPAxis::SelectablePart part, QMouseEvent *event)
void legendClick (QCPLegend *legend, QCPAbstractLegendItem *item, QMouseEvent *event)
void legendDoubleClick (QCPLegend *legend, QCPAbstractLegendItem *item, QMouseEvent *event)
void titleClick (QMouseEvent *event, QCPPlotTitle *title)
void titleDoubleClick (QMouseEvent *event, QCPPlotTitle *title)
void selectionChangedByUser ()
void beforeReplot ()
void afterReplot ()
Public Member Functions
QCustomPlot (QWidget *parent=0)
virtual ~QCustomPlot ()
QRect viewport () const
QPixmap background () const
bool backgroundScaled () const
Qt::AspectRatioMode backgroundScaledMode () const
QCPLayoutGrid * plotLayout () const
QCP::AntialiasedElements antialiasedElements () const
QCP::AntialiasedElements notAntialiasedElements () const
bool autoAddPlottableToLegend () const
const QCP::Interactions interactions () const
int selectionTolerance () const
bool noAntialiasingOnDrag () const
QCP::PlottingHints plottingHints () const
Qt::KeyboardModifier multiSelectModifier () const
void setViewport (const QRect &rect)
void setBackground (const QPixmap &pm)
void setBackground (const QPixmap &pm, bool scaled, Qt::AspectRatioMode mode=Qt::KeepAspectRatioByExpanding)
void setBackground (const QBrush &brush)
void setBackgroundScaled (bool scaled)
void setBackgroundScaledMode (Qt::AspectRatioMode mode)
void setAntialiasedElements (const QCP::AntialiasedElements &antialiasedElements)
void setAntialiasedElement (QCP::AntialiasedElement antialiasedElement, bool enabled=true)
void setNotAntialiasedElements (const QCP::AntialiasedElements &notAntialiasedElements)
void setNotAntialiasedElement (QCP::AntialiasedElement notAntialiasedElement, bool enabled=true)
void setAutoAddPlottableToLegend (bool on)
void setInteractions (const QCP::Interactions &interactions)
void setInteraction (const QCP::Interaction &interaction, bool enabled=true)
void setSelectionTolerance (int pixels)
void setNoAntialiasingOnDrag (bool enabled)
void setPlottingHints (const QCP::PlottingHints &hints)
void setPlottingHint (QCP::PlottingHint hint, bool enabled=true)
void setMultiSelectModifier (Qt::KeyboardModifier modifier)
QCPAbstractPlottable * plottable (int index)
QCPAbstractPlottable * plottable ()
bool addPlottable (QCPAbstractPlottable *plottable)
bool removePlottable (QCPAbstractPlottable *plottable)
bool removePlottable (int index)
int clearPlottables ()
int plottableCount () const
QList< QCPAbstractPlottable * > selectedPlottables () const
QCPAbstractPlottable * plottableAt (const QPointF &pos, bool onlySelectable=false) const
bool hasPlottable (QCPAbstractPlottable *plottable) const
QCPGraph * graph (int index) const
QCPGraph * graph () const
QCPGraph * addGraph (QCPAxis *keyAxis=0, QCPAxis *valueAxis=0)
bool removeGraph (QCPGraph *graph)
bool removeGraph (int index)
int clearGraphs ()
int graphCount () const
QList< QCPGraph * > selectedGraphs () const
QCPAbstractItem * item (int index) const
QCPAbstractItem * item () const
bool addItem (QCPAbstractItem *item)
bool removeItem (QCPAbstractItem *item)
bool removeItem (int index)
int clearItems ()
int itemCount () const
QList< QCPAbstractItem * > selectedItems () const
QCPAbstractItem * itemAt (const QPointF &pos, bool onlySelectable=false) const
bool hasItem (QCPAbstractItem *item) const
QCPLayer * layer (const QString &name) const
QCPLayer * layer (int index) const
QCPLayer * currentLayer () const
bool setCurrentLayer (const QString &name)
bool setCurrentLayer (QCPLayer *layer)
int layerCount () const
bool addLayer (const QString &name, QCPLayer *otherLayer=0, LayerInsertMode insertMode=limAbove)
bool removeLayer (QCPLayer *layer)
bool moveLayer (QCPLayer *layer, QCPLayer *otherLayer, LayerInsertMode insertMode=limAbove)
int axisRectCount () const
QCPAxisRect * axisRect (int index=0) const
QList< QCPAxisRect * > axisRects () const
QCPLayoutElement * layoutElementAt (const QPointF &pos) const
Q_SLOT void rescaleAxes (bool onlyVisiblePlottables=false)
QList< QCPAxis * > selectedAxes () const
QList< QCPLegend * > selectedLegends () const
Q_SLOT void deselectAll ()
bool savePdf (const QString &fileName, bool noCosmeticPen=false, int width=0, int height=0, const QString &pdfCreator=QString(), const QString &pdfTitle=QString())
bool savePng (const QString &fileName, int width=0, int height=0, double scale=1.0, int quality=-1)
bool saveJpg (const QString &fileName, int width=0, int height=0, double scale=1.0, int quality=-1)
bool saveBmp (const QString &fileName, int width=0, int height=0, double scale=1.0)
bool saveRastered (const QString &fileName, int width, int height, double scale, const char *format, int quality=-1)
QPixmap toPixmap (int width=0, int height=0, double scale=1.0)
void toPainter (QCPPainter *painter, int width=0, int height=0)
Q_SLOT void replot (QCustomPlot::RefreshPriority refreshPriority=QCustomPlot::rpHint)
Public Attributes
QCPAxis * xAxis
QCPAxis * yAxis
QCPAxis * xAxis2
QCPAxis * yAxis2
QCPLegend * legend
Protected Member Functions
virtual QSize minimumSizeHint () const
virtual QSize sizeHint () const
virtual void paintEvent (QPaintEvent *event)
virtual void resizeEvent (QResizeEvent *event)
virtual void mouseDoubleClickEvent (QMouseEvent *event)
virtual void mousePressEvent (QMouseEvent *event)
virtual void mouseMoveEvent (QMouseEvent *event)
virtual void mouseReleaseEvent (QMouseEvent *event)
virtual void wheelEvent (QWheelEvent *event)
virtual void draw (QCPPainter *painter)
virtual void axisRemoved (QCPAxis *axis)
virtual void legendRemoved (QCPLegend *legend)
void updateLayerIndices () const
QCPLayerable * layerableAt (const QPointF &pos, bool onlySelectable, QVariant *selectionDetails=0) const
void drawBackground (QCPPainter *painter)
Protected Attributes
QRect mViewport
QCPLayoutGrid * mPlotLayout
bool mAutoAddPlottableToLegend
QList< QCPAbstractPlottable * > mPlottables
QList< QCPGraph * > mGraphs
QList< QCPAbstractItem * > mItems
QList< QCPLayer * > mLayers
QCP::AntialiasedElements mAntialiasedElements
QCP::AntialiasedElements mNotAntialiasedElements
QCP::Interactions mInteractions
int mSelectionTolerance
bool mNoAntialiasingOnDrag
QBrush mBackgroundBrush
QPixmap mBackgroundPixmap
QPixmap mScaledBackgroundPixmap
bool mBackgroundScaled
Qt::AspectRatioMode mBackgroundScaledMode
QCPLayer * mCurrentLayer
QCP::PlottingHints mPlottingHints
Qt::KeyboardModifier mMultiSelectModifier
QPixmap mPaintBuffer
QPoint mMousePressPos
QPointer< QCPLayoutElement > mMouseEventElement
bool mReplotting
Friends
class QCPLegend
class QCPAxis
class QCPLayer
class QCPAxisRect
Detailed Description
The central class of the library. This is the QWidget which displays the plot and interacts with the user.
For tutorials on how to use QCustomPlot, see the website
http://www.qcustomplot.com/
Definition at line 1680 of file qcustomplot.h.
Member Enumeration Documentation
enum LayerInsertMode
Defines how a layer should be inserted relative to an other layer.
See Also
addLayer, moveLayer
Enumerator
limBelow
Layer is inserted below other layer.
limAbove
Layer is inserted above other layer.
Definition at line 1700 of file qcustomplot.h.
enum RefreshPriority
Defines with what timing the QCustomPlot surface is refreshed after a replot.
See Also
replot
Enumerator
rpImmediate
The QCustomPlot surface is immediately refreshed, by calling QWidget::repaint() after the replot.
rpQueued
Queues the refresh such that it is performed at a slightly delayed point in time after the replot, by calling QWidget::update() after the replot.
rpHint
Whether to use immediate repaint or queued update depends on whether the plotting hint QCP::phForceRepaint is set, see setPlottingHints.
Definition at line 1710 of file qcustomplot.h.
Constructor & Destructor Documentation
QCustomPlot (QWidget * parent = 0) explicit
Constructs a QCustomPlot and sets reasonable default values.
Definition at line 9017 of file qcustomplot.cpp.
References QCPLayoutGrid::addElement(), QCPLayoutInset::addElement(), QCPAxis::atBottom, QCPAxis::atLeft, QCPAxis::atRight, QCPAxis::atTop, QCPAxisRect::axis(), QCPAxis::grid(), QCPLayerable::initializeParentPlot(), QCPAxisRect::insetLayout(), legend, mLayers, mPlotLayout, QCPAxisRect, QCPLayer, QCPLegend, replot(), setCurrentLayer(), QCPLayerable::setLayer(), QCPLayoutElement::setMargins(), setViewport(), QCPLayerable::setVisible(), updateLayerIndices(), xAxis, xAxis2, yAxis, and yAxis2.
~QCustomPlot () virtual
Definition at line 9089 of file qcustomplot.cpp.
References clearItems(), clearPlottables(), mCurrentLayer, mLayers, and mPlotLayout.
Member Function Documentation
QCPGraph * addGraph (QCPAxis * keyAxis = 0, QCPAxis * valueAxis = 0)
Creates a new graph inside the plot. If keyAxis and valueAxis are left unspecified (0), the bottom (xAxis) is used as key and the left (yAxis) is used as value axis. If specified, keyAxis and valueAxis must reside in this QCustomPlot.
keyAxis will be used as key axis (typically "x") and valueAxis as value axis (typically "y") for the graph.
Returns a pointer to the newly created graph, or 0 if adding the graph failed.
See Also
graph, graphCount, removeGraph, clearGraphs
Definition at line 9697 of file qcustomplot.cpp.
References addPlottable(), mGraphs, QCPLayerable::parentPlot(), QCPAbstractPlottable::setName(), xAxis, and yAxis.
bool addItem (QCPAbstractItem * item)
Adds the specified item to the plot. QCustomPlot takes ownership of the item.
Returns true on success, i.e. when item wasn't already in the plot and the parent plot of item is this QCustomPlot.
See Also
item, itemCount, removeItem, clearItems
Definition at line 9838 of file qcustomplot.cpp.
References item(), mItems, and QCPLayerable::parentPlot().
bool addLayer (const QString & name, QCPLayer * otherLayer = 0, QCustomPlot::LayerInsertMode insertMode = limAbove)
Adds a new layer to this QCustomPlot instance. The new layer will have the name name, which must be unique. Depending on insertMode, it is positioned either below or above otherLayer.
Returns true on success, i.e. if there is no other layer named name and otherLayer is a valid layer inside this QCustomPlot.
If otherLayer is 0, the highest layer in the QCustomPlot will be used.
For an explanation of what layers are in QCustomPlot, see the documentation of QCPLayer.
See Also
layer, moveLayer, removeLayer
Definition at line 10083 of file qcustomplot.cpp.
References QCPLayer::index(), layer(), limAbove, mLayers, QCPLayer, and updateLayerIndices().
bool addPlottable (QCPAbstractPlottable * plottable)
Adds the specified plottable to the plot and, if setAutoAddPlottableToLegend is enabled, to the legend (QCustomPlot::legend). QCustomPlot takes ownership of the plottable.
Returns true on success, i.e. when plottable isn't already in the plot and the parent plot of plottable is this QCustomPlot (the latter is controlled by what axes were passed in the plottable's constructor).
See Also
plottable, plottableCount, removePlottable, clearPlottables
Definition at line 9495 of file qcustomplot.cpp.
References QCPAbstractPlottable::addToLegend(), currentLayer(), graph(), QCPLayerable::layer(), mAutoAddPlottableToLegend, mGraphs, mPlottables, QCPLayerable::parentPlot(), plottable(), and QCPLayerable::setLayer().
Referenced by addGraph().
void afterReplot () signal
This signal is emitted immediately after a replot has taken place (caused by a call to the slot replot).
It is safe to mutually connect the replot slot with this signal on two QCustomPlots to make them replot synchronously, it won't cause an infinite recursion.
See Also
replot, beforeReplot
Referenced by replot().
QCP::AntialiasedElements antialiasedElements () const inline
Definition at line 1724 of file qcustomplot.h.
Referenced by QCPLayerable::applyAntialiasingHint(), QCPAxisRect::mousePressEvent(), and setAntialiasedElements().
bool autoAddPlottableToLegend () const inline
Definition at line 1726 of file qcustomplot.h.
void axisClick (QCPAxis * axis, QCPAxis::SelectablePart part, QMouseEvent * event) signal
This signal is emitted when an axis is clicked.
event is the mouse event that caused the click, axis is the axis that received the click and part indicates the part of the axis that was clicked.
See Also
axisDoubleClick
Referenced by mouseReleaseEvent().
void axisDoubleClick (QCPAxis * axis, QCPAxis::SelectablePart part, QMouseEvent * event) signal
This signal is emitted when an axis is double clicked.
event is the mouse event that caused the click, axis is the axis that received the click and part indicates the part of the axis that was clicked.
See Also
axisClick
Referenced by mouseDoubleClickEvent().
QCPAxisRect * axisRect (int index = 0) const
Returns the axis rect with index.
Initially, only one axis rect (with index 0) exists in the plot. If multiple axis rects were added, all of them may be accessed with this function in a linear fashion (even when they are nested in a layout hierarchy or inside other axis rects via QCPAxisRect::insetLayout).
See Also
axisRectCount, axisRects
Definition at line 10209 of file qcustomplot.cpp.
References axisRects().
Referenced by QCPAbstractItem::createPosition().
int axisRectCount () const
Returns the number of axis rects in the plot.
All axis rects can be accessed via QCustomPlot::axisRect().
Initially, only one axis rect exists in the plot.
See Also
axisRect, axisRects
Definition at line 10195 of file qcustomplot.cpp.
References axisRects().
QList< QCPAxisRect * > axisRects () const
Returns all axis rects in the plot.
See Also
axisRectCount, axisRect
Definition at line 10227 of file qcustomplot.cpp.
References QCPLayoutElement::elements(), and mPlotLayout.
Referenced by axisRect(), axisRectCount(), QCPAbstractItem::QCPAbstractItem(), rescaleAxes(), and selectedAxes().
void axisRemoved (QCPAxis * axis) protected virtual
Definition at line 10957 of file qcustomplot.cpp.
References xAxis, xAxis2, yAxis, and yAxis2.
Referenced by QCPAxisRect::removeAxis().
QPixmap background () const inline
Definition at line 1720 of file qcustomplot.h.
bool backgroundScaled () const inline
Definition at line 1721 of file qcustomplot.h.
Qt::AspectRatioMode backgroundScaledMode () const inline
Definition at line 1722 of file qcustomplot.h.
void beforeReplot () signal
This signal is emitted immediately before a replot takes place (caused by a call to the slot replot).
It is safe to mutually connect the replot slot with this signal on two QCustomPlots to make them replot synchronously, it won't cause an infinite recursion.
See Also
replot, afterReplot
Referenced by replot().
int clearGraphs ()
Removes all graphs from the plot (and the QCustomPlot::legend, if necessary).
Returns the number of graphs removed.
See Also
removeGraph
Definition at line 9757 of file qcustomplot.cpp.
References mGraphs, and removeGraph().
int clearItems ()
Removes all items from the plot.
Returns the number of items removed.
See Also
removeItem
Definition at line 9894 of file qcustomplot.cpp.
References mItems, and removeItem().
Referenced by ~QCustomPlot().
int clearPlottables ()
Removes all plottables from the plot (and the QCustomPlot::legend, if necessary).
Returns the number of plottables removed.
See Also
removePlottable
Definition at line 9568 of file qcustomplot.cpp.
References mPlottables, and removePlottable().
Referenced by ~QCustomPlot().
QCPLayer * currentLayer () const
Returns the layer that is set as current layer (see setCurrentLayer).
Definition at line 10013 of file qcustomplot.cpp.
References mCurrentLayer.
Referenced by addPlottable(), QCPAxis::QCPAxis(), QCPLayerable::QCPLayerable(), QCPPlotTitle::QCPPlotTitle(), and QCPLayer::~QCPLayer().
void deselectAll ()
Deselects all layerables (plottables, items, axes, legends,...) of the QCustomPlot.
Since calling this function is not a user interaction, this does not emit the selectionChangedByUser signal. The individual selectionChanged signals are emitted though, if the objects were previously selected.
See Also
setInteractions, selectedPlottables, selectedItems, selectedAxes, selectedLegends
Definition at line 10344 of file qcustomplot.cpp.
References QCPLayer::children(), QCPLayerable::deselectEvent(), layer(), and mLayers.
void draw (QCPPainter * painter) protected virtual
Definition at line 10874 of file qcustomplot.cpp.
References QCPLayerable::applyDefaultAntialiasingHint(), QCPLayer::children(), QCPLayerable::clipRect(), QCPLayerable::draw(), drawBackground(), layer(), mLayers, mPlotLayout, QCPLayerable::realVisibility(), QCPPainter::restore(), QCPPainter::save(), QCPLayout::update(), QCPLayoutElement::upLayout, QCPLayoutElement::upMargins, and QCPLayoutElement::upPreparation.
Referenced by replot(), savePdf(), toPainter(), and toPixmap().
void drawBackground (QCPPainter * painter) protected
Definition at line 10929 of file qcustomplot.cpp.
References mBackgroundPixmap, mBackgroundScaled, mBackgroundScaledMode, mScaledBackgroundPixmap, and mViewport.
Referenced by draw().
QCPGraph * graph (int index) const
Returns the graph with index. If the index is invalid, returns 0.
There is an overloaded version of this function with no parameter which returns the last created graph, see QCustomPlot::graph()
See Also
graphCount, addGraph
Definition at line 9657 of file qcustomplot.cpp.
References mGraphs.
Referenced by MainWindow::UpdateSummary().
QCPGraph * graph () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns the last graph, that was created with addGraph. If there are no graphs in the plot, returns 0.
See Also
graphCount, addGraph
Definition at line 9676 of file qcustomplot.cpp.
References mGraphs.
Referenced by addPlottable(), removePlottable(), and selectedGraphs().
int graphCount () const
Returns the number of currently existing graphs in the plot
See Also
graph, addGraph
Definition at line 9770 of file qcustomplot.cpp.
References mGraphs.
bool hasItem (QCPAbstractItem * item) const
Returns whether this QCustomPlot contains the item.
See Also
addItem
Definition at line 9969 of file qcustomplot.cpp.
References mItems.
bool hasPlottable (QCPAbstractPlottable * plottable) const
Returns whether this QCustomPlot instance contains the plottable.
See Also
addPlottable
Definition at line 9644 of file qcustomplot.cpp.
References mPlottables.
Referenced by QCPItemTracer::updatePosition().
const QCP::Interactions interactions () const inline
Definition at line 1727 of file qcustomplot.h.
Referenced by QCPAxisRect::mouseMoveEvent(), QCPAxisRect::mousePressEvent(), setInteractions(), and QCPAxisRect::wheelEvent().
QCPAbstractItem * item (int index) const
Returns the item with index. If the index is invalid, returns 0.
There is an overloaded version of this function with no parameter which returns the last added item, see QCustomPlot::item()
See Also
itemCount, addItem
Definition at line 9802 of file qcustomplot.cpp.
References mItems.
QCPAbstractItem * item () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns the last item, that was added with addItem. If there are no items in the plot, returns 0.
See Also
itemCount, addItem
Definition at line 9821 of file qcustomplot.cpp.
References mItems.
Referenced by addItem(), itemAt(), removeItem(), and selectedItems().
QCPAbstractItem * itemAt (const QPointF & pos, bool onlySelectable = false) const
Returns the item at the pixel position pos. Items that only consist of single lines (e.g. QCPItemLine or QCPItemCurve) have a tolerance band around them, see setSelectionTolerance. If multiple items come into consideration, the one closest to pos is returned.
If onlySelectable is true, only items that are selectable (QCPAbstractItem::setSelectable) are considered.
If there is no item at pos, the return value is 0.
See Also
plottableAt, layoutElementAt
Definition at line 9941 of file qcustomplot.cpp.
References QCPAbstractItem::clipRect(), QCPAbstractItem::clipToAxisRect(), item(), mItems, mSelectionTolerance, QCPAbstractItem::selectable(), and QCPAbstractItem::selectTest().
void itemClick (QCPAbstractItem * item, QMouseEvent * event) signal
This signal is emitted when an item is clicked.
event is the mouse event that caused the click and item is the item that received the click.
See Also
itemDoubleClick
Referenced by mouseReleaseEvent().
int itemCount () const
Returns the number of currently existing items in the plot
See Also
item, addItem
Definition at line 9907 of file qcustomplot.cpp.
References mItems.
void itemDoubleClick (QCPAbstractItem * item, QMouseEvent * event) signal
This signal is emitted when an item is double clicked.
event is the mouse event that caused the click and item is the item that received the click.
See Also
itemClick
Referenced by mouseDoubleClickEvent().
QCPLayer * layer (const QString & name) const
Returns the layer with the specified name. If there is no layer with the specified name, 0 is returned.
Layer names are case-sensitive.
See Also
addLayer, moveLayer, removeLayer
Definition at line 9982 of file qcustomplot.cpp.
References mLayers, and QCPLayer::name().
Referenced by addLayer(), deselectAll(), draw(), mouseReleaseEvent(), moveLayer(), removeLayer(), setCurrentLayer(), and QCPLayerable::setLayer().
QCPLayer * layer (int index) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns the layer by index. If the index is invalid, 0 is returned.
See Also
addLayer, moveLayer, removeLayer
Definition at line 9998 of file qcustomplot.cpp.
References mLayers.
QCPLayerable * layerableAt (const QPointF & pos, bool onlySelectable, QVariant * selectionDetails = 0) const protected
Definition at line 11006 of file qcustomplot.cpp.
References mLayers, selectionTolerance(), and QCPLayerable::selectTest().
Referenced by mouseDoubleClickEvent(), and mouseReleaseEvent().
int layerCount () const
Returns the number of currently existing layers in the plot
See Also
layer, addLayer
Definition at line 10065 of file qcustomplot.cpp.
References mLayers.
QCPLayoutElement * layoutElementAt (const QPointF & pos) const
Returns the layout element at pixel position pos. If there is no element at that position, returns 0.
Only visible elements are used. If QCPLayoutElement::setVisible on the element itself or on any of its parent elements is set to false, it will not be considered.
See Also
itemAt, plottableAt
Definition at line 10259 of file qcustomplot.cpp.
References QCPLayoutElement::elements(), mPlotLayout, QCPLayerable::realVisibility(), and QCPLayoutElement::selectTest().
Referenced by mouseDoubleClickEvent(), mousePressEvent(), and wheelEvent().
void legendClick (QCPLegend * legend, QCPAbstractLegendItem * item, QMouseEvent * event) signal
This signal is emitted when a legend (item) is clicked.
event is the mouse event that caused the click, legend is the legend that received the click and item is the legend item that received the click. If only the legend and no item is clicked, item is 0. This happens for a click inside the legend padding or the space between two items.
See Also
legendDoubleClick
Referenced by mouseReleaseEvent().
void legendDoubleClick (QCPLegend * legend, QCPAbstractLegendItem * item, QMouseEvent * event) signal
This signal is emitted when a legend (item) is double clicked.
event is the mouse event that caused the click, legend is the legend that received the click and item is the legend item that received the click. If only the legend and no item is clicked, item is 0. This happens for a click inside the legend padding or the space between two items.
See Also
legendClick
Referenced by mouseDoubleClickEvent().
void legendRemoved (QCPLegend * legend) protected virtual
Definition at line 10976 of file qcustomplot.cpp.
Referenced by QCPLegend::~QCPLegend().
QSize minimumSizeHint () const protected virtual
Definition at line 10637 of file qcustomplot.cpp.
References QCPLayoutGrid::minimumSizeHint(), and mPlotLayout.
void mouseDoubleClick (QMouseEvent * event) signal
This signal is emitted when the QCustomPlot receives a mouse double click event.
Referenced by mouseDoubleClickEvent().
void mouseDoubleClickEvent (QMouseEvent * event) protected virtual
Definition at line 10687 of file qcustomplot.cpp.
References axisDoubleClick(), itemDoubleClick(), layerableAt(), layoutElementAt(), legendDoubleClick(), mMouseEventElement, mouseDoubleClick(), plottableDoubleClick(), and titleDoubleClick().
void mouseMove (QMouseEvent * event) signal
This signal is emitted when the QCustomPlot receives a mouse move event.
It is emitted before QCustomPlot handles any other mechanism like range dragging. So a slot connected to this signal can still influence the behaviour e.g. with QCPAxisRect::setRangeDrag or QCPAxisRect::setRangeDragAxes.
Warning
It is discouraged to change the drag-axes with QCPAxisRect::setRangeDragAxes here, because the dragging starting point was saved the moment the mouse was pressed. Thus it only has a meaning for the range drag axes that were set at that moment. If you want to change the drag axes, consider doing this in the mousePress signal instead.
Referenced by mouseMoveEvent().
void mouseMoveEvent (QMouseEvent * event) protected virtual
Definition at line 10751 of file qcustomplot.cpp.
References mMouseEventElement, and mouseMove().
void mousePress (QMouseEvent * event) signal
This signal is emitted when the QCustomPlot receives a mouse press event.
It is emitted before QCustomPlot handles any other mechanism like range dragging. So a slot connected to this signal can still influence the behaviour e.g. with QCPAxisRect::setRangeDrag or QCPAxisRect::setRangeDragAxes.
Referenced by mousePressEvent().
void mousePressEvent (QMouseEvent * event) protected virtual
Definition at line 10729 of file qcustomplot.cpp.
References layoutElementAt(), mMouseEventElement, mMousePressPos, and mousePress().
void mouseRelease (QMouseEvent * event) signal
This signal is emitted when the QCustomPlot receives a mouse release event.
It is emitted before QCustomPlot handles any other mechanisms like object selection. So a slot connected to this signal can still influence the behaviour e.g. with setInteractions or QCPAbstractPlottable::setSelectable.
Referenced by mouseReleaseEvent().
void mouseReleaseEvent (QMouseEvent * event) protected virtual
Definition at line 10776 of file qcustomplot.cpp.
References axisClick(), QCPLayer::children(), QCPLayerable::deselectEvent(), QCP::iMultiSelect, itemClick(), layer(), layerableAt(), legendClick(), mInteractions, mLayers, mMouseEventElement, mMousePressPos, mMultiSelectModifier, mouseRelease(), noAntialiasingOnDrag(), plottableClick(), replot(), QCPLayerable::selectEvent(), QCPLayerable::selectionCategory(), selectionChangedByUser(), and titleClick().
void mouseWheel (QWheelEvent * event) signal
This signal is emitted when the QCustomPlot receives a mouse wheel event.
It is emitted before QCustomPlot handles any other mechanisms like range zooming. So a slot connected to this signal can still influence the behaviour e.g. with QCPAxisRect::setRangeZoom, QCPAxisRect::setRangeZoomAxes or QCPAxisRect::setRangeZoomFactor.
Referenced by wheelEvent().
bool moveLayer (QCPLayer * layer, QCPLayer * otherLayer, QCustomPlot::LayerInsertMode insertMode = limAbove)
Moves the specified layer either above or below otherLayer. Whether it's placed above or below is controlled with insertMode.
Returns true on success, i.e. when both layer and otherLayer are valid layers in the QCustomPlot.
See Also
layer, addLayer, moveLayer
Definition at line 10164 of file qcustomplot.cpp.
References QCPLayer::index(), layer(), limAbove, mLayers, and updateLayerIndices().
Qt::KeyboardModifier multiSelectModifier () const inline
Definition at line 1731 of file qcustomplot.h.
bool noAntialiasingOnDrag () const inline
Definition at line 1729 of file qcustomplot.h.
Referenced by QCPAxisRect::mouseMoveEvent(), QCPAxisRect::mousePressEvent(), mouseReleaseEvent(), and QCPAxisRect::mouseReleaseEvent().
QCP::AntialiasedElements notAntialiasedElements () const inline
Definition at line 1725 of file qcustomplot.h.
Referenced by QCPLayerable::applyAntialiasingHint(), QCPAxisRect::mousePressEvent(), and setNotAntialiasedElements().
void paintEvent (QPaintEvent * event) protected virtual
Definition at line 10657 of file qcustomplot.cpp.
References mPaintBuffer.
QCPLayoutGrid * plotLayout () const inline
Returns the top level layout of this QCustomPlot instance. It is a QCPLayoutGrid, initially containing just one cell with the main QCPAxisRect inside.
Definition at line 1723 of file qcustomplot.h.
QCPAbstractPlottable * plottable (int index)
Returns the plottable with index. If the index is invalid, returns 0.
There is an overloaded version of this function with no parameter which returns the last added plottable, see QCustomPlot::plottable()
See Also
plottableCount, addPlottable
Definition at line 9457 of file qcustomplot.cpp.
References mPlottables.
Referenced by QCPColorScale::colorMaps().
QCPAbstractPlottable * plottable ()
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns the last plottable that was added with addPlottable. If there are no plottables in the plot, returns 0.
See Also
plottableCount, addPlottable
Definition at line 9476 of file qcustomplot.cpp.
References mPlottables.
Referenced by addPlottable(), plottableAt(), removePlottable(), and selectedPlottables().
QCPAbstractPlottable * plottableAt (const QPointF & pos, bool onlySelectable = false) const
Returns the plottable at the pixel position pos. Plottables that only consist of single lines (like graphs) have a tolerance band around them, see setSelectionTolerance. If multiple plottables come into consideration, the one closest to pos is returned.
If onlySelectable is true, only plottables that are selectable (QCPAbstractPlottable::setSelectable) are considered.
If there is no plottable at pos, the return value is 0.
See Also
itemAt, layoutElementAt
Definition at line 9616 of file qcustomplot.cpp.
References QCPAxis::axisRect(), QCPAbstractPlottable::keyAxis(), mPlottables, mSelectionTolerance, plottable(), QCPLayoutElement::rect(), QCPAbstractPlottable::selectable(), QCPAbstractPlottable::selectTest(), and QCPAbstractPlottable::valueAxis().
void plottableClick (QCPAbstractPlottable * plottable, QMouseEvent * event) signal
This signal is emitted when a plottable is clicked.
event is the mouse event that caused the click and plottable is the plottable that received the click.
See Also
plottableDoubleClick
Referenced by mouseReleaseEvent().
int plottableCount () const
Returns the number of currently existing plottables in the plot
See Also
plottable, addPlottable
Definition at line 9581 of file qcustomplot.cpp.
References mPlottables.
Referenced by QCPColorScale::colorMaps().
void plottableDoubleClick (QCPAbstractPlottable * plottable, QMouseEvent * event) signal
This signal is emitted when a plottable is double clicked.
event is the mouse event that caused the click and plottable is the plottable that received the click.
See Also
plottableClick
Referenced by mouseDoubleClickEvent().
QCP::PlottingHints plottingHints () const inline
Definition at line 1730 of file qcustomplot.h.
Referenced by QCPCurve::draw(), QCPGraph::drawLinePlot(), QCPAxisPainterPrivate::getMaxTickLabelSize(), and QCPAxisPainterPrivate::placeTickLabel().
bool removeGraph (QCPGraph * graph)
Removes the specified graph from the plot and, if necessary, from the QCustomPlot::legend. If any other graphs in the plot have a channel fill set towards the removed graph, the channel fill property of those graphs is reset to zero (no channel fill).
Returns true on success.
See Also
clearGraphs
Definition at line 9733 of file qcustomplot.cpp.
References removePlottable().
Referenced by clearGraphs(), and removeGraph().
bool removeGraph (int index)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Removes the graph by its index.
Definition at line 9742 of file qcustomplot.cpp.
References mGraphs, and removeGraph().
bool removeItem (QCPAbstractItem * item)
Removes the specified item from the plot.
Returns true on success.
See Also
addItem, clearItems
Definition at line 9858 of file qcustomplot.cpp.
References item(), and mItems.
Referenced by clearItems(), and removeItem().
bool removeItem (int index)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Removes the item by its index.
Definition at line 9876 of file qcustomplot.cpp.
References mItems, and removeItem().
bool removeLayer (QCPLayer * layer)
Removes the specified layer and returns true on success.
All layerables (e.g. plottables and items) on the removed layer will be moved to the layer below layer. If layer is the bottom layer, the layerables are moved to the layer above. In both cases, the total rendering order of all layerables in the QCustomPlot is preserved.
If layer is the current layer (setCurrentLayer), the layer below (or above, if bottom layer) becomes the new current layer.
It is not possible to remove the last layer of the plot.
See Also
layer, addLayer, moveLayer
Definition at line 10118 of file qcustomplot.cpp.
References QCPLayer::children(), QCPLayer::index(), layer(), mCurrentLayer, mLayers, setCurrentLayer(), and updateLayerIndices().
bool removePlottable (QCPAbstractPlottable * plottable)
Removes the specified plottable from the plot and, if necessary, from the legend (QCustomPlot::legend).
Returns true on success.
See Also
addPlottable, clearPlottables
Definition at line 9527 of file qcustomplot.cpp.
References graph(), mGraphs, mPlottables, plottable(), and QCPAbstractPlottable::removeFromLegend().
Referenced by clearPlottables(), removeGraph(), and removePlottable().
bool removePlottable (int index)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Removes the plottable by its index.
Definition at line 9550 of file qcustomplot.cpp.
References mPlottables, and removePlottable().
void replot (QCustomPlot::RefreshPriority refreshPriority = QCustomPlot::rpHint)
Causes a complete replot into the internal buffer. Finally, update() is called, to redraw the buffer on the QCustomPlot widget surface. This is the method that must be called to make changes, for example on the axis ranges or data points of graphs, visible.
Under a few circumstances, QCustomPlot causes a replot by itself. Those are resize events of the QCustomPlot widget and user interactions (object selection and range dragging/zooming).
Before the replot happens, the signal beforeReplot is emitted. After the replot, afterReplot is emitted. It is safe to mutually connect the replot slot with any of those two signals on two QCustomPlots to make them replot synchronously, it won't cause an infinite recursion.
Definition at line 10366 of file qcustomplot.cpp.
References afterReplot(), beforeReplot(), QCPPainter::begin(), draw(), mBackgroundBrush, mPaintBuffer, mPlottingHints, mReplotting, mViewport, QCP::phForceRepaint, rpHint, and rpImmediate.
Referenced by QCPAxisRect::mouseMoveEvent(), mouseReleaseEvent(), QCustomPlot(), resizeEvent(), MainWindow::UpdateSummary(), and QCPAxisRect::wheelEvent().
void rescaleAxes (bool onlyVisiblePlottables = false)
Rescales the axes such that all plottables (like graphs) in the plot are fully visible.
if onlyVisiblePlottables is set to true, only the plottables that have their visibility set to true (QCPLayerable::setVisible), will be used to rescale the axes.
See Also
QCPAbstractPlottable::rescaleAxes, QCPAxis::rescale
Definition at line 10402 of file qcustomplot.cpp.
References QCPAxisRect::axes(), axisRects(), and QCPAxis::rescale().
void resizeEvent (QResizeEvent * event) protected virtual
Definition at line 10670 of file qcustomplot.cpp.
References mPaintBuffer, replot(), rpQueued, and setViewport().
bool saveBmp (const QString & fileName, int width = 0, int height = 0, double scale = 1.0)
Saves a BMP image file to fileName on disc. The output plot will have the dimensions width and height in pixels. If either width or height is zero, the exported image will have the same dimensions as the QCustomPlot widget currently has. Line widths and texts etc. are not scaled up when larger widths/heights are used. If you want that effect, use the scale parameter.
For example, if you set both width and height to 100 and scale to 2, you will end up with an image file of size 200*200 in which all graphical elements are scaled up by factor 2 (line widths, texts, etc.). This scaling is not done by stretching a 100*100 image, the result will have full 200*200 pixel resolution.
If you use a high scaling factor, it is recommended to enable antialiasing for all elements via temporarily setting QCustomPlot::setAntialiasedElements to QCP::aeAll as this allows QCustomPlot to place objects with sub-pixel accuracy.
Warning
If calling this function inside the constructor of the parent of the QCustomPlot widget (i.e. the MainWindow constructor, if QCustomPlot is inside the MainWindow), always provide explicit non-zero widths and heights. If you leave width or height as 0 (default), this function uses the current width and height of the QCustomPlot widget. However, in Qt, these aren't defined yet inside the constructor, so you would get an image that has strange widths/heights.
The objects of the plot will appear in the current selection state. If you don't want any selected objects to be painted in their selected look, deselect everything with deselectAll before calling this function.
Returns true on success. If this function fails, most likely the BMP format isn't supported by the system, see Qt docs about QImageWriter::supportedImageFormats().
See Also
savePdf, savePng, saveJpg, saveRastered
Definition at line 10624 of file qcustomplot.cpp.
References saveRastered().
bool saveJpg (const QString & fileName, int width = 0, int height = 0, double scale = 1.0, int quality = -1)
Saves a JPG image file to fileName on disc. The output plot will have the dimensions width and height in pixels. If either width or height is zero, the exported image will have the same dimensions as the QCustomPlot widget currently has. Line widths and texts etc. are not scaled up when larger widths/heights are used. If you want that effect, use the scale parameter.
For example, if you set both width and height to 100 and scale to 2, you will end up with an image file of size 200*200 in which all graphical elements are scaled up by factor 2 (line widths, texts, etc.). This scaling is not done by stretching a 100*100 image, the result will have full 200*200 pixel resolution.
If you use a high scaling factor, it is recommended to enable antialiasing for all elements via temporarily setting QCustomPlot::setAntialiasedElements to QCP::aeAll as this allows QCustomPlot to place objects with sub-pixel accuracy.
Warning
If calling this function inside the constructor of the parent of the QCustomPlot widget (i.e. the MainWindow constructor, if QCustomPlot is inside the MainWindow), always provide explicit non-zero widths and heights. If you leave width or height as 0 (default), this function uses the current width and height of the QCustomPlot widget. However, in Qt, these aren't defined yet inside the constructor, so you would get an image that has strange widths/heights.
The objects of the plot will appear in the current selection state. If you don't want any selected objects to be painted in their selected look, deselect everything with deselectAll before calling this function.
JPG compression can be controlled with the quality parameter which must be between 0 and 100 or -1 to use the default setting.
Returns true on success. If this function fails, most likely the JPG format isn't supported by the system, see Qt docs about QImageWriter::supportedImageFormats().
See Also
savePdf, savePng, saveBmp, saveRastered
Definition at line 10588 of file qcustomplot.cpp.
References saveRastered().
bool savePdf (const QString & fileName, bool noCosmeticPen = false, int width = 0, int height = 0, const QString & pdfCreator = QString(), const QString & pdfTitle = QString())
Saves a PDF with the vectorized plot to the file fileName. The axis ratio as well as the scale of texts and lines will be derived from the specified width and height. This means, the output will look like the normal on-screen output of a QCustomPlot widget with the corresponding pixel width and height. If either width or height is zero, the exported image will have the same dimensions as the QCustomPlot widget currently has.
noCosmeticPen disables the use of cosmetic pens when drawing to the PDF file. Cosmetic pens are pens with numerical width 0, which are always drawn as a one pixel wide line, no matter what zoom factor is set in the PDF-Viewer. For more information about cosmetic pens, see the QPainter and QPen documentation.
The objects of the plot will appear in the current selection state. If you don't want any selected objects to be painted in their selected look, deselect everything with deselectAll before calling this function.
Returns true on success.
Warning
If you plan on editing the exported PDF file with a vector graphics editor like Inkscape, it is advised to set noCosmeticPen to true to avoid losing those cosmetic lines (which might be quite many, because cosmetic pens are the default for e.g. axes and tick marks).
If calling this function inside the constructor of the parent of the QCustomPlot widget (i.e. the MainWindow constructor, if QCustomPlot is inside the MainWindow), always provide explicit non-zero widths and heights. If you leave width or height as 0 (default), this function uses the current width and height of the QCustomPlot widget. However, in Qt, these aren't defined yet inside the constructor, so you would get an image that has strange widths/heights.
pdfCreator and pdfTitle may be used to set the according metadata fields in the resulting PDF file.
Note
On Android systems, this method does nothing and issues an according qDebug warning message. This is also the case if for other reasons the define flag QT_NO_PRINTER is set.
See Also
savePng, saveBmp, saveJpg, saveRastered
Definition at line 10449 of file qcustomplot.cpp.
References QCPPainter::begin(), draw(), mBackgroundBrush, mViewport, QCPPainter::pmNoCaching, QCPPainter::pmNonCosmetic, QCPPainter::pmVectorized, QCPPainter::setMode(), setViewport(), and viewport().
bool savePng (const QString & fileName, int width = 0, int height = 0, double scale = 1.0, int quality = -1)
Saves a PNG image file to fileName on disc. The output plot will have the dimensions width and height in pixels. If either width or height is zero, the exported image will have the same dimensions as the QCustomPlot widget currently has. Line widths and texts etc. are not scaled up when larger widths/heights are used. If you want that effect, use the scale parameter.
For example, if you set both width and height to 100 and scale to 2, you will end up with an image file of size 200*200 in which all graphical elements are scaled up by factor 2 (line widths, texts, etc.). This scaling is not done by stretching a 100*100 image, the result will have full 200*200 pixel resolution.
If you use a high scaling factor, it is recommended to enable antialiasing for all elements via temporarily setting QCustomPlot::setAntialiasedElements to QCP::aeAll as this allows QCustomPlot to place objects with sub-pixel accuracy.
Warning
If calling this function inside the constructor of the parent of the QCustomPlot widget (i.e. the MainWindow constructor, if QCustomPlot is inside the MainWindow), always provide explicit non-zero widths and heights. If you leave width or height as 0 (default), this function uses the current width and height of the QCustomPlot widget. However, in Qt, these aren't defined yet inside the constructor, so you would get an image that has strange widths/heights.
The objects of the plot will appear in the current selection state. If you don't want any selected objects to be painted in their selected look, deselect everything with deselectAll before calling this function.
If you want the PNG to have a transparent background, call setBackground(const QBrush &brush) with no brush (Qt::NoBrush) or a transparent color (Qt::transparent), before saving.
PNG compression can be controlled with the quality parameter which must be between 0 and 100 or -1 to use the default setting.
Returns true on success. If this function fails, most likely the PNG format isn't supported by the system, see Qt docs about QImageWriter::supportedImageFormats().
See Also
savePdf, saveBmp, saveJpg, saveRastered
Definition at line 10549 of file qcustomplot.cpp.
References saveRastered().
bool saveRastered (const QString & fileName, int width, int height, double scale, const char * format, int quality = -1)
Saves the plot to a rastered image file fileName in the image format format. The plot is sized to width and height in pixels and scaled with scale. (width 100 and scale 2.0 lead to a full resolution file with width 200.) If the format supports compression, quality may be between 0 and 100 to control it.
Returns true on success. If this function fails, most likely the given format isn't supported by the system, see Qt docs about QImageWriter::supportedImageFormats().
See Also
saveBmp, saveJpg, savePng, savePdf
Definition at line 11043 of file qcustomplot.cpp.
References toPixmap().
Referenced by saveBmp(), saveJpg(), and savePng().
QList< QCPAxis * > selectedAxes () const
Returns the axes that currently have selected parts, i.e. whose selection state is not QCPAxis::spNone.
See Also
selectedPlottables, selectedLegends, setInteractions, QCPAxis::setSelectedParts, QCPAxis::setSelectableParts
Definition at line 10286 of file qcustomplot.cpp.
References QCPAxisRect::axes(), axisRects(), QCPAxis::selectedParts(), and QCPAxis::spNone.
QList< QCPGraph * > selectedGraphs () const
Returns a list of the selected graphs. If no graphs are currently selected, the list is empty.
If you are not only interested in selected graphs but other plottables like QCPCurve, QCPBars, etc., use selectedPlottables.
See Also
setInteractions, selectedPlottables, QCPAbstractPlottable::setSelectable, QCPAbstractPlottable::setSelected
Definition at line 9783 of file qcustomplot.cpp.
References graph(), mGraphs, and QCPAbstractPlottable::selected().
QList< QCPAbstractItem * > selectedItems () const
Returns a list of the selected items. If no items are currently selected, the list is empty.
See Also
setInteractions, QCPAbstractItem::setSelectable, QCPAbstractItem::setSelected
Definition at line 9917 of file qcustomplot.cpp.
References item(), mItems, and QCPAbstractItem::selected().
QList< QCPLegend * > selectedLegends () const
Returns the legends that currently have selected parts, i.e. whose selection state is not QCPLegend::spNone.
See Also
selectedPlottables, selectedAxes, setInteractions, QCPLegend::setSelectedParts, QCPLegend::setSelectableParts, QCPLegend::selectedItems
Definition at line 10308 of file qcustomplot.cpp.
References QCPLayoutElement::elements(), mPlotLayout, and QCPLegend::spNone.
QList< QCPAbstractPlottable * > selectedPlottables () const
Returns a list of the selected plottables. If no plottables are currently selected, the list is empty.
There is a convenience function if you're only interested in selected graphs, see selectedGraphs.
See Also
setInteractions, QCPAbstractPlottable::setSelectable, QCPAbstractPlottable::setSelected
Definition at line 9593 of file qcustomplot.cpp.
References mPlottables, plottable(), and QCPAbstractPlottable::selected().
void selectionChangedByUser () signal
This signal is emitted after the user has changed the selection in the QCustomPlot, e.g. by clicking. It is not emitted when the selection state of an object has changed programmatically by a direct call to setSelected() on an object or by calling deselectAll.
In addition to this signal, selectable objects also provide individual signals, for example QCPAxis::selectionChanged or QCPAbstractPlottable::selectionChanged. Note that those signals are emitted even if the selection state is changed programmatically.
See the documentation of setInteractions for details about the selection mechanism.
See Also
selectedPlottables, selectedGraphs, selectedItems, selectedAxes, selectedLegends
Referenced by mouseReleaseEvent().
int selectionTolerance () const inline
Definition at line 1728 of file qcustomplot.h.
Referenced by QCPFinancial::candlestickSelectTest(), QCPAxisPainterPrivate::draw(), layerableAt(), QCPAbstractItem::rectSelectTest(), QCPLayoutElement::selectTest(), QCPLayoutInset::selectTest(), QCPAxis::selectTest(), QCPAbstractLegendItem::selectTest(), QCPLegend::selectTest(), QCPPlotTitle::selectTest(), QCPBars::selectTest(), QCPStatisticalBox::selectTest(), QCPColorMap::selectTest(), QCPItemEllipse::selectTest(), and QCPItemTracer::selectTest().
void setAntialiasedElement (QCP::AntialiasedElement antialiasedElement, bool enabled = true)
Sets whether the specified antialiasedElement is forcibly drawn antialiased.
See setAntialiasedElements for details.
See Also
setNotAntialiasedElement
Definition at line 9138 of file qcustomplot.cpp.
References mAntialiasedElements, and mNotAntialiasedElements.
void setAntialiasedElements (const QCP::AntialiasedElements & antialiasedElements)
Sets which elements are forcibly drawn antialiased as an or combination of QCP::AntialiasedElement.
This overrides the antialiasing settings for whole element groups, normally controlled with the setAntialiasing function on the individual elements. If an element is neither specified in setAntialiasedElements nor in setNotAntialiasedElements, the antialiasing setting on each individual element instance is used.
For example, if antialiasedElements contains QCP::aePlottables, all plottables will be drawn antialiased, no matter what the specific QCPAbstractPlottable::setAntialiased value was set to.
if an element in antialiasedElements is already set in setNotAntialiasedElements, it is removed from there.
See Also
setNotAntialiasedElements
Definition at line 9122 of file qcustomplot.cpp.
References antialiasedElements(), mAntialiasedElements, and mNotAntialiasedElements.
Referenced by QCPAxisRect::mouseReleaseEvent().
void setAutoAddPlottableToLegend (bool on)
If set to true, adding a plottable (e.g. a graph) to the QCustomPlot automatically also adds the plottable to the legend (QCustomPlot::legend).
See Also
addPlottable, addGraph, QCPLegend::addItem
Definition at line 9202 of file qcustomplot.cpp.
References mAutoAddPlottableToLegend.
void setBackground (const QPixmap & pm)
Sets pm as the viewport background pixmap (see setViewport). The pixmap is always drawn below all other objects in the plot.
For cases where the provided pixmap doesn't have the same size as the viewport, scaling can be enabled with setBackgroundScaled and the scaling mode (whether and how the aspect ratio is preserved) can be set with setBackgroundScaledMode. To set all these options in one call, consider using the overloaded version of this function.
If a background brush was set with setBackground(const QBrush &brush), the viewport will first be filled with that brush, before drawing the background pixmap. This can be useful for background pixmaps with translucent areas.
See Also
setBackgroundScaled, setBackgroundScaledMode
Definition at line 9384 of file qcustomplot.cpp.
References mBackgroundPixmap, and mScaledBackgroundPixmap.
void setBackground (const QPixmap & pm, bool scaled, Qt::AspectRatioMode mode = Qt::KeepAspectRatioByExpanding)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Allows setting the background pixmap of the viewport, whether it shall be scaled and how it shall be scaled in one call.
See Also
setBackground(const QPixmap &pm), setBackgroundScaled, setBackgroundScaledMode
Definition at line 9415 of file qcustomplot.cpp.
References mBackgroundPixmap, mBackgroundScaled, mBackgroundScaledMode, and mScaledBackgroundPixmap.
void setBackground (const QBrush & brush)
Sets the background brush of the viewport (see setViewport).
Before drawing everything else, the background is filled with brush. If a background pixmap was set with setBackground(const QPixmap &pm), this brush will be used to fill the viewport before the background pixmap is drawn. This can be useful for background pixmaps with translucent areas.
Set brush to Qt::NoBrush or Qt::Transparent to leave background transparent. This can be useful for exporting to image formats which support transparency, e.g. savePng.
See Also
setBackgroundScaled, setBackgroundScaledMode
Definition at line 9403 of file qcustomplot.cpp.
References mBackgroundBrush.
void setBackgroundScaled (bool scaled)
Sets whether the viewport background pixmap shall be scaled to fit the viewport. If scaled is set to true, control whether and how the aspect ratio of the original pixmap is preserved with setBackgroundScaledMode.
Note that the scaled version of the original pixmap is buffered, so there is no performance penalty on replots. (Except when the viewport dimensions are changed continuously.)
See Also
setBackground, setBackgroundScaledMode
Definition at line 9433 of file qcustomplot.cpp.
References mBackgroundScaled.
void setBackgroundScaledMode (Qt::AspectRatioMode mode)
If scaling of the viewport background pixmap is enabled (setBackgroundScaled), use this function to define whether and how the aspect ratio of the original pixmap is preserved.
See Also
setBackground, setBackgroundScaled
Definition at line 9444 of file qcustomplot.cpp.
References mBackgroundScaledMode.
bool setCurrentLayer (const QString & name)
Sets the layer with the specified name to be the current layer. All layerables (QCPLayerable), e.g. plottables and items, are created on the current layer.
Returns true on success, i.e. if there is a layer with the specified name in the QCustomPlot.
Layer names are case-sensitive.
See Also
addLayer, moveLayer, removeLayer, QCPLayerable::setLayer
Definition at line 10028 of file qcustomplot.cpp.
References layer().
Referenced by QCustomPlot(), and removeLayer().
bool setCurrentLayer (QCPLayer * layer)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Sets the provided layer to be the current layer.
Returns true on success, i.e. when layer is a valid layer in the QCustomPlot.
See Also
addLayer, moveLayer, removeLayer
Definition at line 10048 of file qcustomplot.cpp.
References layer(), mCurrentLayer, and mLayers.
void setInteraction (const QCP::Interaction & interaction, bool enabled = true)
Sets the single interaction of this QCustomPlot to enabled.
For details about the interaction system, see setInteractions.
See Also
setInteractions
Definition at line 9273 of file qcustomplot.cpp.
References mInteractions.
void setInteractions (const QCP::Interactions & interactions)
Sets the possible interactions of this QCustomPlot as an or-combination of QCP::Interaction enums. There are the following types of interactions:
Axis range manipulation is controlled via QCP::iRangeDrag and QCP::iRangeZoom. When the respective interaction is enabled, the user may drag axes ranges and zoom with the mouse wheel. For details how to control which axes the user may drag/zoom and in what orientations, see QCPAxisRect::setRangeDrag, QCPAxisRect::setRangeZoom, QCPAxisRect::setRangeDragAxes, QCPAxisRect::setRangeZoomAxes.
Plottable selection is controlled by QCP::iSelectPlottables. If QCP::iSelectPlottables is set, the user may select plottables (graphs, curves, bars,...) by clicking on them or in their vicinity (setSelectionTolerance). Whether the user can actually select a plottable can further be restricted with the QCPAbstractPlottable::setSelectable function on the specific plottable. To find out whether a specific plottable is selected, call QCPAbstractPlottable::selected(). To retrieve a list of all currently selected plottables, call selectedPlottables. If you're only interested in QCPGraphs, you may use the convenience function selectedGraphs.
Item selection is controlled by QCP::iSelectItems. If QCP::iSelectItems is set, the user may select items (QCPItemLine, QCPItemText,...) by clicking on them or in their vicinity. To find out whether a specific item is selected, call QCPAbstractItem::selected(). To retrieve a list of all currently selected items, call selectedItems.
Axis selection is controlled with QCP::iSelectAxes. If QCP::iSelectAxes is set, the user may select parts of the axes by clicking on them. What parts exactly (e.g. Axis base line, tick labels, axis label) are selectable can be controlled via QCPAxis::setSelectableParts for each axis. To retrieve a list of all axes that currently contain selected parts, call selectedAxes. Which parts of an axis are selected, can be retrieved with QCPAxis::selectedParts().
Legend selection is controlled with QCP::iSelectLegend. If this is set, the user may select the legend itself or individual items by clicking on them. What parts exactly are selectable can be controlled via QCPLegend::setSelectableParts. To find out whether the legend or any of its child items are selected, check the value of QCPLegend::selectedParts. To find out which child items are selected, call QCPLegend::selectedItems.
All other selectable elements The selection of all other selectable objects (e.g. QCPPlotTitle, or your own layerable subclasses) is controlled with QCP::iSelectOther. If set, the user may select those objects by clicking on them. To find out which are currently selected, you need to check their selected state explicitly.
If the selection state has changed by user interaction, the selectionChangedByUser signal is emitted. Each selectable object additionally emits an individual selectionChanged signal whenever their selection state has changed, i.e. not only by user interaction.
To allow multiple objects to be selected by holding the selection modifier (setMultiSelectModifier), set the flag QCP::iMultiSelect.
Note
In addition to the selection mechanism presented here, QCustomPlot always emits corresponding signals, when an object is clicked or double clicked. see plottableClick and plottableDoubleClick for example.
See Also
setInteraction, setSelectionTolerance
Definition at line 9261 of file qcustomplot.cpp.
References interactions(), and mInteractions.
void setMultiSelectModifier (Qt::KeyboardModifier modifier)
Sets the keyboard modifier that will be recognized as multi-select-modifier.
If QCP::iMultiSelect is specified in setInteractions, the user may select multiple objects by clicking on them one after the other while holding down modifier.
By default the multi-select-modifier is set to Qt::ControlModifier.
See Also
setInteractions
Definition at line 9350 of file qcustomplot.cpp.
References mMultiSelectModifier.
void setNoAntialiasingOnDrag (bool enabled)
Sets whether antialiasing is disabled for this QCustomPlot while the user is dragging axes ranges. If many objects, especially plottables, are drawn antialiased, this greatly improves performance during dragging. Thus it creates a more responsive user experience. As soon as the user stops dragging, the last replot is done with normal antialiasing, to restore high image quality.
See Also
setAntialiasedElements, setNotAntialiasedElements
Definition at line 9308 of file qcustomplot.cpp.
References mNoAntialiasingOnDrag.
void setNotAntialiasedElement (QCP::AntialiasedElement notAntialiasedElement, bool enabled = true)
Sets whether the specified notAntialiasedElement is forcibly drawn not antialiased.
See setNotAntialiasedElements for details.
See Also
setAntialiasedElement
Definition at line 9184 of file qcustomplot.cpp.
References mAntialiasedElements, and mNotAntialiasedElements.
void setNotAntialiasedElements (const QCP::AntialiasedElements & notAntialiasedElements)
Sets which elements are forcibly drawn not antialiased as an or combination of QCP::AntialiasedElement.
This overrides the antialiasing settings for whole element groups, normally controlled with the setAntialiasing function on the individual elements. If an element is neither specified in setAntialiasedElements nor in setNotAntialiasedElements, the antialiasing setting on each individual element instance is used.
For example, if notAntialiasedElements contains QCP::aePlottables, no plottables will be drawn antialiased, no matter what the specific QCPAbstractPlottable::setAntialiased value was set to.
if an element in notAntialiasedElements is already set in setAntialiasedElements, it is removed from there.
See Also
setAntialiasedElements
Definition at line 9168 of file qcustomplot.cpp.
References mAntialiasedElements, mNotAntialiasedElements, and notAntialiasedElements().
Referenced by QCPAxisRect::mouseMoveEvent(), and QCPAxisRect::mouseReleaseEvent().
void setPlottingHint (QCP::PlottingHint hint, bool enabled = true)
Sets the specified plotting hint to enabled.
See Also
setPlottingHints
Definition at line 9328 of file qcustomplot.cpp.
References mPlottingHints, and setPlottingHints().
void setPlottingHints (const QCP::PlottingHints & hints)
Sets the plotting hints for this QCustomPlot instance as an or combination of QCP::PlottingHint.
See Also
setPlottingHint
Definition at line 9318 of file qcustomplot.cpp.
References mPlottingHints.
Referenced by setPlottingHint().
void setSelectionTolerance (int pixels)
Sets the tolerance that is used to decide whether a click selects an object (e.g. a plottable) or not.
If the user clicks in the vicinity of the line of e.g. a QCPGraph, it's only regarded as a potential selection when the minimum distance between the click position and the graph line is smaller than pixels. Objects that are defined by an area (e.g. QCPBars) only react to clicks directly inside the area and ignore this selection tolerance. In other words, it only has meaning for parts of objects that are too thin to exactly hit with a click and thus need such a tolerance.
See Also
setInteractions, QCPLayerable::selectTest
Definition at line 9294 of file qcustomplot.cpp.
References mSelectionTolerance.
void setViewport (const QRect & rect)
Sets the viewport of this QCustomPlot. The Viewport is the area that the top level layout (QCustomPlot::plotLayout()) uses as its rect. Normally, the viewport is the entire widget rect.
This function is used to allow arbitrary size exports with toPixmap, savePng, savePdf, etc. by temporarily changing the viewport size.
Definition at line 9362 of file qcustomplot.cpp.
References mPlotLayout, mViewport, and QCPLayoutElement::setOuterRect().
Referenced by QCustomPlot(), resizeEvent(), savePdf(), toPainter(), and toPixmap().
QSize sizeHint () const protected virtual
Definition at line 10647 of file qcustomplot.cpp.
References QCPLayoutGrid::minimumSizeHint(), and mPlotLayout.
void titleClick (QMouseEvent * event, QCPPlotTitle * title) signal
This signal is emitted when a plot title is clicked.
event is the mouse event that caused the click and title is the plot title that received the click.
See Also
titleDoubleClick
Referenced by mouseReleaseEvent().
void titleDoubleClick (QMouseEvent * event, QCPPlotTitle * title) signal
This signal is emitted when a plot title is double clicked.
event is the mouse event that caused the click and title is the plot title that received the click.
See Also
titleClick
Referenced by mouseDoubleClickEvent().
void toPainter (QCPPainter * painter, int width = 0, int height = 0)
Renders the plot using the passed painter.
The plot is sized to width and height in pixels. If the painter's scale is not 1.0, the resulting plot will appear scaled accordingly.
Note
If you are restricted to using a QPainter (instead of QCPPainter), create a temporary QPicture and open a QCPPainter on it. Then call toPainter with this QCPPainter. After ending the paint operation on the picture, draw it with the QPainter. This will reproduce the painter actions the QCPPainter took, with a QPainter.
See Also
toPixmap
Definition at line 11116 of file qcustomplot.cpp.
References draw(), mBackgroundBrush, mViewport, QCPPainter::pmNoCaching, QCPPainter::setMode(), setViewport(), and viewport().
QPixmap toPixmap (int width = 0, int height = 0, double scale = 1.0)
Renders the plot to a pixmap and returns it.
The plot is sized to width and height in pixels and scaled with scale. (width 100 and scale 2.0 lead to a full resolution pixmap with width 200.)
See Also
toPainter, saveRastered, saveBmp, savePng, saveJpg, savePdf
Definition at line 11060 of file qcustomplot.cpp.
References QCPPainter::begin(), draw(), mBackgroundBrush, mViewport, QCPPainter::pmNoCaching, QCPPainter::pmNonCosmetic, QCPPainter::setMode(), setViewport(), and viewport().
Referenced by saveRastered().
void updateLayerIndices () const protected
Definition at line 10988 of file qcustomplot.cpp.
References mLayers.
Referenced by addLayer(), moveLayer(), QCustomPlot(), and removeLayer().
QRect viewport () const inline
Returns the viewport rect of this QCustomPlot instance. The viewport is the area the plot is drawn in, all mechanisms, e.g. margin caluclation take the viewport to be the outer border of the plot. The viewport normally is the rect() of the QCustomPlot widget, i.e. a rect with top left (0, 0) and size of the QCustomPlot widget.
Don't confuse the viewport with the axis rect (QCustomPlot::axisRect). An axis rect is typically an area enclosed by four axes, where the graphs/plottables are drawn in. The viewport is larger and contains also the axes themselves, their tick numbers, their labels, the plot title etc.
Only when saving to a file (see savePng, savePdf etc.) the viewport is temporarily modified to allow saving plots with sizes independent of the current widget size.
Definition at line 1719 of file qcustomplot.h.
Referenced by QCPAxis::calculateMargin(), QCPLayerable::clipRect(), QCPAbstractItem::clipRect(), QCPAxis::draw(), QCPItemPosition::pixelPoint(), savePdf(), QCPItemPosition::setPixelPoint(), toPainter(), and toPixmap().
void wheelEvent (QWheelEvent * event) protected virtual
Definition at line 10856 of file qcustomplot.cpp.
References layoutElementAt(), and mouseWheel().
Friends And Related Function Documentation
friend class QCPAxis friend
Definition at line 1894 of file qcustomplot.h.
friend class QCPAxisRect friend
Definition at line 1896 of file qcustomplot.h.
Referenced by QCustomPlot().
friend class QCPLayer friend
Definition at line 1895 of file qcustomplot.h.
Referenced by addLayer(), and QCustomPlot().
friend class QCPLegend friend
Definition at line 1893 of file qcustomplot.h.
Referenced by QCustomPlot().
Member Data Documentation
QCPLegend * legend
A pointer to the default legend of the main axis rect. The legend is invisible by default. Use QCPLegend::setVisible to change this.
QCustomPlot offers convenient pointers to the axes (xAxis, yAxis, xAxis2, yAxis2) and the legend. They make it very easy working with plots that only have a single axis rect and at most one axis at each axis rect side. If you use the layout system to add multiple legends to the plot, use the layout system interface to access the new legend. For example, legends can be placed inside an axis rect's inset layout, and must then also be accessed via the inset layout. If the default legend is removed due to manipulation of the layout system (e.g. by removing the main axis rect), the corresponding pointer becomes 0.
Definition at line 1820 of file qcustomplot.h.
Referenced by QCPAbstractPlottable::addToLegend(), QCustomPlot(), and QCPAbstractPlottable::removeFromLegend().
QCP::AntialiasedElements mAntialiasedElements protected
Definition at line 1853 of file qcustomplot.h.
Referenced by setAntialiasedElement(), setAntialiasedElements(), setNotAntialiasedElement(), and setNotAntialiasedElements().
bool mAutoAddPlottableToLegend protected
Definition at line 1848 of file qcustomplot.h.
Referenced by addPlottable(), and setAutoAddPlottableToLegend().
QBrush mBackgroundBrush protected
Definition at line 1857 of file qcustomplot.h.
Referenced by replot(), savePdf(), setBackground(), toPainter(), and toPixmap().
QPixmap mBackgroundPixmap protected
Definition at line 1858 of file qcustomplot.h.
Referenced by drawBackground(), and setBackground().
bool mBackgroundScaled protected
Definition at line 1860 of file qcustomplot.h.
Referenced by drawBackground(), setBackground(), and setBackgroundScaled().
Qt::AspectRatioMode mBackgroundScaledMode protected
Definition at line 1861 of file qcustomplot.h.
Referenced by drawBackground(), setBackground(), and setBackgroundScaledMode().
QCPLayer* mCurrentLayer protected
Definition at line 1862 of file qcustomplot.h.
Referenced by currentLayer(), removeLayer(), setCurrentLayer(), and ~QCustomPlot().
QList<QCPGraph*> mGraphs protected
Definition at line 1850 of file qcustomplot.h.
Referenced by addGraph(), addPlottable(), clearGraphs(), graph(), graphCount(), QCPAxis::graphs(), QCPAxisRect::graphs(), removeGraph(), removePlottable(), and selectedGraphs().
QCP::Interactions mInteractions protected
Definition at line 1854 of file qcustomplot.h.
Referenced by mouseReleaseEvent(), setInteraction(), and setInteractions().
QList<QCPAbstractItem*> mItems protected
Definition at line 1851 of file qcustomplot.h.
Referenced by addItem(), clearItems(), hasItem(), item(), itemAt(), itemCount(), QCPAxis::items(), QCPAxisRect::items(), removeItem(), and selectedItems().
QList<QCPLayer*> mLayers protected
Definition at line 1852 of file qcustomplot.h.
Referenced by addLayer(), deselectAll(), draw(), layer(), layerableAt(), layerCount(), mouseReleaseEvent(), moveLayer(), QCustomPlot(), removeLayer(), setCurrentLayer(), updateLayerIndices(), and ~QCustomPlot().
QPointer<QCPLayoutElement> mMouseEventElement protected
Definition at line 1869 of file qcustomplot.h.
Referenced by mouseDoubleClickEvent(), mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
QPoint mMousePressPos protected
Definition at line 1868 of file qcustomplot.h.
Referenced by mousePressEvent(), and mouseReleaseEvent().
Qt::KeyboardModifier mMultiSelectModifier protected
Definition at line 1864 of file qcustomplot.h.
Referenced by mouseReleaseEvent(), and setMultiSelectModifier().
bool mNoAntialiasingOnDrag protected
Definition at line 1856 of file qcustomplot.h.
Referenced by setNoAntialiasingOnDrag().
QCP::AntialiasedElements mNotAntialiasedElements protected
Definition at line 1853 of file qcustomplot.h.
Referenced by setAntialiasedElement(), setAntialiasedElements(), setNotAntialiasedElement(), and setNotAntialiasedElements().
QPixmap mPaintBuffer protected
Definition at line 1867 of file qcustomplot.h.
Referenced by paintEvent(), replot(), and resizeEvent().
QCPLayoutGrid* mPlotLayout protected
Definition at line 1847 of file qcustomplot.h.
Referenced by axisRects(), draw(), layoutElementAt(), minimumSizeHint(), QCustomPlot(), selectedLegends(), setViewport(), sizeHint(), and ~QCustomPlot().
QList<QCPAbstractPlottable*> mPlottables protected
Definition at line 1849 of file qcustomplot.h.
Referenced by addPlottable(), clearPlottables(), hasPlottable(), plottable(), plottableAt(), plottableCount(), QCPAxis::plottables(), QCPAxisRect::plottables(), removePlottable(), and selectedPlottables().
QCP::PlottingHints mPlottingHints protected
Definition at line 1863 of file qcustomplot.h.
Referenced by replot(), setPlottingHint(), and setPlottingHints().
bool mReplotting protected
Definition at line 1870 of file qcustomplot.h.
Referenced by replot().
QPixmap mScaledBackgroundPixmap protected
Definition at line 1859 of file qcustomplot.h.
Referenced by drawBackground(), and setBackground().
int mSelectionTolerance protected
Definition at line 1855 of file qcustomplot.h.
Referenced by itemAt(), plottableAt(), and setSelectionTolerance().
QRect mViewport protected
Definition at line 1846 of file qcustomplot.h.
Referenced by drawBackground(), replot(), savePdf(), setViewport(), toPainter(), and toPixmap().
QCPAxis * xAxis
A pointer to the primary x Axis (bottom) of the main axis rect of the plot.
QCustomPlot offers convenient pointers to the axes (xAxis, yAxis, xAxis2, yAxis2) and the legend. They make it very easy working with plots that only have a single axis rect and at most one axis at each axis rect side. If you use the layout system to add multiple axis rects or multiple axes to one side, use the QCPAxisRect::axis interface to access the new axes. If one of the four default axes or the default legend is removed due to manipulation of the layout system (e.g. by removing the main axis rect), the corresponding pointers become 0.
Definition at line 1819 of file qcustomplot.h.
Referenced by addGraph(), axisRemoved(), QCPAbstractItem::createPosition(), and QCustomPlot().
QCPAxis * xAxis2
A pointer to the secondary x Axis (top) of the main axis rect of the plot. Secondary axes are invisible by default. Use QCPAxis::setVisible to change this (or use QCPAxisRect::setupFullAxesBox).
QCustomPlot offers convenient pointers to the axes (xAxis, yAxis, xAxis2, yAxis2) and the legend. They make it very easy working with plots that only have a single axis rect and at most one axis at each axis rect side. If you use the layout system to add multiple axis rects or multiple axes to one side, use the QCPAxisRect::axis interface to access the new axes. If one of the four default axes or the default legend is removed due to manipulation of the layout system (e.g. by removing the main axis rect), the corresponding pointers become 0.
Definition at line 1819 of file qcustomplot.h.
Referenced by axisRemoved(), and QCustomPlot().
QCPAxis * yAxis
A pointer to the primary y Axis (left) of the main axis rect of the plot.
QCustomPlot offers convenient pointers to the axes (xAxis, yAxis, xAxis2, yAxis2) and the legend. They make it very easy working with plots that only have a single axis rect and at most one axis at each axis rect side. If you use the layout system to add multiple axis rects or multiple axes to one side, use the QCPAxisRect::axis interface to access the new axes. If one of the four default axes or the default legend is removed due to manipulation of the layout system (e.g. by removing the main axis rect), the corresponding pointers become 0.
Definition at line 1819 of file qcustomplot.h.
Referenced by addGraph(), axisRemoved(), QCPAbstractItem::createPosition(), and QCustomPlot().
QCPAxis * yAxis2
A pointer to the secondary y Axis (right) of the main axis rect of the plot. Secondary axes are invisible by default. Use QCPAxis::setVisible to change this (or use QCPAxisRect::setupFullAxesBox).
QCustomPlot offers convenient pointers to the axes (xAxis, yAxis, xAxis2, yAxis2) and the legend. They make it very easy working with plots that only have a single axis rect and at most one axis at each axis rect side. If you use the layout system to add multiple axis rects or multiple axes to one side, use the QCPAxisRect::axis interface to access the new axes. If one of the four default axes or the default legend is removed due to manipulation of the layout system (e.g. by removing the main axis rect), the corresponding pointers become 0.
Definition at line 1819 of file qcustomplot.h.
Referenced by axisRemoved(), and QCustomPlot().
The documentation for this class was generated from the following files:
qcustomplot.h
qcustomplot.cpp