SETestKCL: QCPPlotTitle Class Reference
QCPPlotTitle Class Reference
#include <qcustomplot.h>
Signals
void selectionChanged (bool selected)
void selectableChanged (bool selectable)
Signals inherited from QCPLayerable
void layerChanged (QCPLayer *newLayer)
Public Member Functions
QCPPlotTitle (QCustomPlot *parentPlot)
QCPPlotTitle (QCustomPlot *parentPlot, const QString &text)
QString text () const
QFont font () const
QColor textColor () const
QFont selectedFont () const
QColor selectedTextColor () const
bool selectable () const
bool selected () const
void setText (const QString &text)
void setFont (const QFont &font)
void setTextColor (const QColor &color)
void setSelectedFont (const QFont &font)
void setSelectedTextColor (const QColor &color)
Q_SLOT void setSelectable (bool selectable)
Q_SLOT void setSelected (bool selected)
virtual double selectTest (const QPointF &pos, bool onlySelectable, QVariant *details=0) const
Public Member Functions inherited from QCPLayoutElement
QCPLayoutElement (QCustomPlot *parentPlot=0)
virtual ~QCPLayoutElement ()
QCPLayout * layout () const
QRect rect () const
QRect outerRect () const
QMargins margins () const
QMargins minimumMargins () const
QCP::MarginSides autoMargins () const
QSize minimumSize () const
QSize maximumSize () const
QCPMarginGroup * marginGroup (QCP::MarginSide side) const
QHash< QCP::MarginSide,
QCPMarginGroup * > marginGroups () const
void setOuterRect (const QRect &rect)
void setMargins (const QMargins &margins)
void setMinimumMargins (const QMargins &margins)
void setAutoMargins (QCP::MarginSides sides)
void setMinimumSize (const QSize &size)
void setMinimumSize (int width, int height)
void setMaximumSize (const QSize &size)
void setMaximumSize (int width, int height)
void setMarginGroup (QCP::MarginSides sides, QCPMarginGroup *group)
virtual void update (UpdatePhase phase)
virtual QList< QCPLayoutElement * > elements (bool recursive) const
Public Member Functions inherited from QCPLayerable
QCPLayerable (QCustomPlot *plot, QString targetLayer=QString(), QCPLayerable *parentLayerable=0)
~QCPLayerable ()
bool visible () const
QCustomPlot * parentPlot () const
QCPLayerable * parentLayerable () const
QCPLayer * layer () const
bool antialiased () const
void setVisible (bool on)
Q_SLOT bool setLayer (QCPLayer *layer)
bool setLayer (const QString &layerName)
void setAntialiased (bool enabled)
bool realVisibility () const
Protected Member Functions
virtual void applyDefaultAntialiasingHint (QCPPainter *painter) const
virtual void draw (QCPPainter *painter)
virtual QSize minimumSizeHint () const
virtual QSize maximumSizeHint () const
virtual void selectEvent (QMouseEvent *event, bool additive, const QVariant &details, bool *selectionStateChanged)
virtual void deselectEvent (bool *selectionStateChanged)
QFont mainFont () const
QColor mainTextColor () const
Protected Member Functions inherited from QCPLayoutElement
virtual int calculateAutoMargin (QCP::MarginSide side)
virtual void mousePressEvent (QMouseEvent *event)
virtual void mouseMoveEvent (QMouseEvent *event)
virtual void mouseReleaseEvent (QMouseEvent *event)
virtual void mouseDoubleClickEvent (QMouseEvent *event)
virtual void wheelEvent (QWheelEvent *event)
virtual void parentPlotInitialized (QCustomPlot *parentPlot)
Protected Member Functions inherited from QCPLayerable
virtual QCP::Interaction selectionCategory () const
virtual QRect clipRect () const
void initializeParentPlot (QCustomPlot *parentPlot)
void setParentLayerable (QCPLayerable *parentLayerable)
bool moveToLayer (QCPLayer *layer, bool prepend)
void applyAntialiasingHint (QCPPainter *painter, bool localAntialiased, QCP::AntialiasedElement overrideElement) const
Protected Attributes
QString mText
QFont mFont
QColor mTextColor
QFont mSelectedFont
QColor mSelectedTextColor
QRect mTextBoundingRect
bool mSelectable
bool mSelected
Protected Attributes inherited from QCPLayoutElement
QCPLayout * mParentLayout
QSize mMinimumSize
QSize mMaximumSize
QRect mRect
QRect mOuterRect
QMargins mMargins
QMargins mMinimumMargins
QCP::MarginSides mAutoMargins
QHash< QCP::MarginSide,
QCPMarginGroup * > mMarginGroups
Protected Attributes inherited from QCPLayerable
bool mVisible
QCustomPlot * mParentPlot
QPointer< QCPLayerable > mParentLayerable
QCPLayer * mLayer
bool mAntialiased
Additional Inherited Members
Public Types inherited from QCPLayoutElement
enum UpdatePhase { upPreparation, upMargins, upLayout }
Detailed Description
A layout element displaying a plot title text.
The text may be specified with setText, theformatting can be controlled with setFont and setTextColor.
A plot title can be added as follows:
Since a plot title is a common requirement, QCustomPlot offers specialized selection signals for easy interaction with QCPPlotTitle. If a layout element of type QCPPlotTitle is clicked, the signal QCustomPlot::titleClick is emitted. A double click emits the QCustomPlot::titleDoubleClick signal.
Definition at line 2293 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPPlotTitle (QCustomPlot * parentPlot) explicit
Creates a new QCPPlotTitle instance and sets default values. The initial text is empty (setText).
To set the title text in the constructor, rather use QCPPlotTitle(QCustomPlot *parentPlot, const QString &text).
Definition at line 13513 of file qcustomplot.cpp.
References QCustomPlot::currentLayer(), mFont, mSelectedFont, QCPLayerable::setLayer(), and QCPLayoutElement::setMargins().
QCPPlotTitle (QCustomPlot * parentPlot, const QString & text) explicit
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Creates a new QCPPlotTitle instance and sets default values. The initial text is set to text.
Definition at line 13535 of file qcustomplot.cpp.
References QCPLayerable::setLayer(), and QCPLayoutElement::setMargins().
Member Function Documentation
void applyDefaultAntialiasingHint (QCPPainter * painter) const protected virtual
Reimplemented from QCPLayoutElement.
Definition at line 13631 of file qcustomplot.cpp.
References QCP::aeNone, QCPLayerable::applyAntialiasingHint(), and QCPLayerable::mAntialiased.
void deselectEvent (bool * selectionStateChanged) protected virtual
Reimplemented from QCPLayerable.
Definition at line 13679 of file qcustomplot.cpp.
References mSelectable, mSelected, and setSelected().
void draw (QCPPainter * painter) protected virtual
Reimplemented from QCPLayoutElement.
Definition at line 13637 of file qcustomplot.cpp.
References mainFont(), mainTextColor(), QCPLayoutElement::mRect, mText, mTextBoundingRect, and QCPPainter::setPen().
QFont font () const inline
Definition at line 2311 of file qcustomplot.h.
Referenced by setFont(), and setSelectedFont().
QFont mainFont () const protected
Definition at line 13708 of file qcustomplot.cpp.
References mFont, mSelected, and mSelectedFont.
Referenced by draw().
QColor mainTextColor () const protected
Definition at line 13718 of file qcustomplot.cpp.
References mSelected, mSelectedTextColor, and mTextColor.
Referenced by draw().
QSize maximumSizeHint () const protected virtual
Returns the maximum size this layout element (the inner rect) may be expanded to.
if a maximum size (setMaximumSize) was not set manually, parent layouts consult this function to determine the maximum allowed size of this layout element. (A manual maximum size is considered set if it is smaller than Qt's QWIDGETSIZE_MAX.)
Reimplemented from QCPLayoutElement.
Definition at line 13655 of file qcustomplot.cpp.
References mFont, QCPLayoutElement::mMargins, and mText.
QSize minimumSizeHint () const protected virtual
Returns the minimum size this layout element (the inner rect) may be compressed to.
if a minimum size (setMinimumSize) was not set manually, parent layouts consult this function to determine the minimum allowed size of this layout element. (A manual minimum size is considered set if it is non-zero.)
Reimplemented from QCPLayoutElement.
Definition at line 13645 of file qcustomplot.cpp.
References mFont, QCPLayoutElement::mMargins, and mText.
bool selectable () const inline
Definition at line 2315 of file qcustomplot.h.
Referenced by setSelectable().
void selectableChanged (bool selectable) signal
Referenced by setSelectable().
bool selected () const inline
Definition at line 2316 of file qcustomplot.h.
Referenced by setSelected().
QFont selectedFont () const inline
Definition at line 2313 of file qcustomplot.h.
QColor selectedTextColor () const inline
Definition at line 2314 of file qcustomplot.h.
void selectEvent (QMouseEvent * event, bool additive, const QVariant & details, bool * selectionStateChanged) protected virtual
Reimplemented from QCPLayerable.
Definition at line 13665 of file qcustomplot.cpp.
References mSelectable, mSelected, and setSelected().
void selectionChanged (bool selected) signal
This signal is emitted when the selection state has changed to selected, either by user interaction or by a direct call to setSelected.
See Also
setSelected, setSelectable
Referenced by setSelected().
double selectTest (const QPointF & pos, bool onlySelectable, QVariant * details = 0) const virtual
Layout elements are sensitive to events inside their outer rect. If pos is within the outer rect, this method returns a value corresponding to 0.99 times the parent plot's selection tolerance. However, layout elements are not selectable by default. So if onlySelectable is true, -1.0 is returned.
See QCPLayerable::selectTest for a general explanation of this virtual method.
QCPLayoutElement subclasses may reimplement this method to provide more specific selection test behaviour.
Reimplemented from QCPLayoutElement.
Definition at line 13691 of file qcustomplot.cpp.
References QCPLayerable::mParentPlot, mSelectable, mTextBoundingRect, and QCustomPlot::selectionTolerance().
void setFont (const QFont & font)
Sets the font of the title text.
See Also
setTextColor, setSelectedFont
Definition at line 13564 of file qcustomplot.cpp.
References font(), and mFont.
void setSelectable (bool selectable)
Sets whether the user may select this plot title to selectable.
Note that even when selectable is set to false, the selection state may be changed programmatically via setSelected.
Definition at line 13605 of file qcustomplot.cpp.
References mSelectable, selectable(), and selectableChanged().
void setSelected (bool selected)
Sets the selection state of this plot title to selected. If the selection has changed, selectionChanged is emitted.
Note that this function can change the selection state independently of the current setSelectable state.
Definition at line 13621 of file qcustomplot.cpp.
References mSelected, selected(), and selectionChanged().
Referenced by deselectEvent(), and selectEvent().
void setSelectedFont (const QFont & font)
Sets the font of the title text that will be used if the plot title is selected (setSelected).
See Also
setFont
Definition at line 13584 of file qcustomplot.cpp.
References font(), and mSelectedFont.
void setSelectedTextColor (const QColor & color)
Sets the color of the title text that will be used if the plot title is selected (setSelected).
See Also
setTextColor
Definition at line 13594 of file qcustomplot.cpp.
References mSelectedTextColor.
void setText (const QString & text)
Sets the text that will be displayed to text. Multiple lines can be created by insertion of "\n".
See Also
setFont, setTextColor
Definition at line 13554 of file qcustomplot.cpp.
References mText, and text().
void setTextColor (const QColor & color)
Sets the color of the title text.
See Also
setFont, setSelectedTextColor
Definition at line 13574 of file qcustomplot.cpp.
References mTextColor.
QString text () const inline
Definition at line 2310 of file qcustomplot.h.
Referenced by setText().
QColor textColor () const inline
Definition at line 2312 of file qcustomplot.h.
Member Data Documentation
QFont mFont protected
Definition at line 2337 of file qcustomplot.h.
Referenced by mainFont(), maximumSizeHint(), minimumSizeHint(), QCPPlotTitle(), and setFont().
bool mSelectable protected
Definition at line 2342 of file qcustomplot.h.
Referenced by deselectEvent(), selectEvent(), selectTest(), and setSelectable().
bool mSelected protected
Definition at line 2342 of file qcustomplot.h.
Referenced by deselectEvent(), mainFont(), mainTextColor(), selectEvent(), and setSelected().
QFont mSelectedFont protected
Definition at line 2339 of file qcustomplot.h.
Referenced by mainFont(), QCPPlotTitle(), and setSelectedFont().
QColor mSelectedTextColor protected
Definition at line 2340 of file qcustomplot.h.
Referenced by mainTextColor(), and setSelectedTextColor().
QString mText protected
Definition at line 2336 of file qcustomplot.h.
Referenced by draw(), maximumSizeHint(), minimumSizeHint(), and setText().
QRect mTextBoundingRect protected
Definition at line 2341 of file qcustomplot.h.
Referenced by draw(), and selectTest().
QColor mTextColor protected
Definition at line 2338 of file qcustomplot.h.
Referenced by mainTextColor(), and setTextColor().
The documentation for this class was generated from the following files:
qcustomplot.h
qcustomplot.cpp