SETestKCL: QCPAxisRect Class Reference
QCPAxisRect Class Reference
#include <qcustomplot.h>
Public Member Functions
QCPAxisRect (QCustomPlot *parentPlot, bool setupDefaultAxes=true)
virtual ~QCPAxisRect ()
QPixmap background () const
bool backgroundScaled () const
Qt::AspectRatioMode backgroundScaledMode () const
Qt::Orientations rangeDrag () const
Qt::Orientations rangeZoom () const
QCPAxis * rangeDragAxis (Qt::Orientation orientation)
QCPAxis * rangeZoomAxis (Qt::Orientation orientation)
double rangeZoomFactor (Qt::Orientation orientation)
void setBackground (const QPixmap &pm)
void setBackground (const QPixmap &pm, bool scaled, Qt::AspectRatioMode mode=Qt::KeepAspectRatioByExpanding)
void setBackground (const QBrush &brush)
void setBackgroundScaled (bool scaled)
void setBackgroundScaledMode (Qt::AspectRatioMode mode)
void setRangeDrag (Qt::Orientations orientations)
void setRangeZoom (Qt::Orientations orientations)
void setRangeDragAxes (QCPAxis *horizontal, QCPAxis *vertical)
void setRangeZoomAxes (QCPAxis *horizontal, QCPAxis *vertical)
void setRangeZoomFactor (double horizontalFactor, double verticalFactor)
void setRangeZoomFactor (double factor)
int axisCount (QCPAxis::AxisType type) const
QCPAxis * axis (QCPAxis::AxisType type, int index=0) const
QList< QCPAxis * > axes (QCPAxis::AxisTypes types) const
QList< QCPAxis * > axes () const
QCPAxis * addAxis (QCPAxis::AxisType type, QCPAxis *axis=0)
QList< QCPAxis * > addAxes (QCPAxis::AxisTypes types)
bool removeAxis (QCPAxis *axis)
QCPLayoutInset * insetLayout () const
void setupFullAxesBox (bool connectRanges=false)
QList< QCPAbstractPlottable * > plottables () const
QList< QCPGraph * > graphs () const
QList< QCPAbstractItem * > items () const
int left () const
int right () const
int top () const
int bottom () const
int width () const
int height () const
QSize size () const
QPoint topLeft () const
QPoint topRight () const
QPoint bottomLeft () const
QPoint bottomRight () const
QPoint center () const
virtual void update (UpdatePhase phase)
virtual QList< QCPLayoutElement * > elements (bool recursive) const
Public Member Functions inherited from QCPLayoutElement
QCPLayoutElement (QCustomPlot *parentPlot=0)
virtual ~QCPLayoutElement ()
QCPLayout * layout () const
QRect rect () const
QRect outerRect () const
QMargins margins () const
QMargins minimumMargins () const
QCP::MarginSides autoMargins () const
QSize minimumSize () const
QSize maximumSize () const
QCPMarginGroup * marginGroup (QCP::MarginSide side) const
QHash< QCP::MarginSide,
QCPMarginGroup * > marginGroups () const
void setOuterRect (const QRect &rect)
void setMargins (const QMargins &margins)
void setMinimumMargins (const QMargins &margins)
void setAutoMargins (QCP::MarginSides sides)
void setMinimumSize (const QSize &size)
void setMinimumSize (int width, int height)
void setMaximumSize (const QSize &size)
void setMaximumSize (int width, int height)
void setMarginGroup (QCP::MarginSides sides, QCPMarginGroup *group)
virtual QSize minimumSizeHint () const
virtual QSize maximumSizeHint () const
virtual double selectTest (const QPointF &pos, bool onlySelectable, QVariant *details=0) const
Public Member Functions inherited from QCPLayerable
QCPLayerable (QCustomPlot *plot, QString targetLayer=QString(), QCPLayerable *parentLayerable=0)
~QCPLayerable ()
bool visible () const
QCustomPlot * parentPlot () const
QCPLayerable * parentLayerable () const
QCPLayer * layer () const
bool antialiased () const
void setVisible (bool on)
Q_SLOT bool setLayer (QCPLayer *layer)
bool setLayer (const QString &layerName)
void setAntialiased (bool enabled)
bool realVisibility () const
Protected Member Functions
virtual void applyDefaultAntialiasingHint (QCPPainter *painter) const
virtual void draw (QCPPainter *painter)
virtual int calculateAutoMargin (QCP::MarginSide side)
virtual void mousePressEvent (QMouseEvent *event)
virtual void mouseMoveEvent (QMouseEvent *event)
virtual void mouseReleaseEvent (QMouseEvent *event)
virtual void wheelEvent (QWheelEvent *event)
void drawBackground (QCPPainter *painter)
void updateAxesOffset (QCPAxis::AxisType type)
Protected Member Functions inherited from QCPLayoutElement
virtual void mouseDoubleClickEvent (QMouseEvent *event)
virtual void parentPlotInitialized (QCustomPlot *parentPlot)
Protected Member Functions inherited from QCPLayerable
virtual QCP::Interaction selectionCategory () const
virtual QRect clipRect () const
virtual void selectEvent (QMouseEvent *event, bool additive, const QVariant &details, bool *selectionStateChanged)
virtual void deselectEvent (bool *selectionStateChanged)
void initializeParentPlot (QCustomPlot *parentPlot)
void setParentLayerable (QCPLayerable *parentLayerable)
bool moveToLayer (QCPLayer *layer, bool prepend)
void applyAntialiasingHint (QCPPainter *painter, bool localAntialiased, QCP::AntialiasedElement overrideElement) const
Protected Attributes
QBrush mBackgroundBrush
QPixmap mBackgroundPixmap
QPixmap mScaledBackgroundPixmap
bool mBackgroundScaled
Qt::AspectRatioMode mBackgroundScaledMode
QCPLayoutInset * mInsetLayout
Qt::Orientations mRangeDrag
Qt::Orientations mRangeZoom
QPointer< QCPAxis > mRangeDragHorzAxis
QPointer< QCPAxis > mRangeDragVertAxis
QPointer< QCPAxis > mRangeZoomHorzAxis
QPointer< QCPAxis > mRangeZoomVertAxis
double mRangeZoomFactorHorz
double mRangeZoomFactorVert
QCPRange mDragStartHorzRange
QCPRange mDragStartVertRange
QCP::AntialiasedElements mAADragBackup
QCP::AntialiasedElements mNotAADragBackup
QPoint mDragStart
bool mDragging
QHash< QCPAxis::AxisType,
QList< QCPAxis * > > mAxes
Protected Attributes inherited from QCPLayoutElement
QCPLayout * mParentLayout
QSize mMinimumSize
QSize mMaximumSize
QRect mRect
QRect mOuterRect
QMargins mMargins
QMargins mMinimumMargins
QCP::MarginSides mAutoMargins
QHash< QCP::MarginSide,
QCPMarginGroup * > mMarginGroups
Protected Attributes inherited from QCPLayerable
bool mVisible
QCustomPlot * mParentPlot
QPointer< QCPLayerable > mParentLayerable
QCPLayer * mLayer
bool mAntialiased
Friends
class QCustomPlot
Additional Inherited Members
Public Types inherited from QCPLayoutElement
enum UpdatePhase { upPreparation, upMargins, upLayout }
Signals inherited from QCPLayerable
void layerChanged (QCPLayer *newLayer)
Detailed Description
Holds multiple axes and arranges them in a rectangular shape.
This class represents an axis rect, a rectangular area that is bounded on all sides with an arbitrary number of axes.
Initially QCustomPlot has one axis rect, accessible via QCustomPlot::axisRect(). However, the layout system allows to have multiple axis rects, e.g. arranged in a grid layout (QCustomPlot::plotLayout).
By default, QCPAxisRect comes with four axes, at bottom, top, left and right. They can be accessed via axis by providing the respective axis type (QCPAxis::AxisType) and index. If you need all axes in the axis rect, use axes. The top and right axes are set to be invisible initially (QCPAxis::setVisible). To add more axes to a side, use addAxis or addAxes. To remove an axis, use removeAxis.
The axis rect layerable itself only draws a background pixmap or color, if specified (setBackground). It is placed on the "background" layer initially (see QCPLayer for an explanation of the QCustomPlot layer system). The axes that are held by the axis rect can be placed on other layers, independently of the axis rect.
Every axis rect has a child layout of type QCPLayoutInset. It is accessible via insetLayout and can be used to have other layout elements (or even other layouts with multiple elements) hovering inside the axis rect.
If an axis rect is clicked and dragged, it processes this by moving certain axis ranges. The behaviour can be controlled with setRangeDrag and setRangeDragAxes. If the mouse wheel is scrolled while the cursor is on the axis rect, certain axes are scaled. This is controllable via setRangeZoom, setRangeZoomAxes and setRangeZoomFactor. These interactions are only enabled if QCustomPlot::setInteractions contains QCP::iRangeDrag and QCP::iRangeZoom.
Overview of the spacings and paddings that define the geometry of an axis. The dashed line on the far left indicates the viewport/widget border.
Definition at line 1972 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPAxisRect (QCustomPlot * parentPlot, bool setupDefaultAxes = true) explicit
Creates a QCPAxisRect instance and sets default values. An axis is added for each of the four sides, the top and right axes are set invisible initially.
Definition at line 11726 of file qcustomplot.cpp.
References addAxis(), QCPAxis::atBottom, QCPAxis::atLeft, QCPAxis::atRight, QCPAxis::atTop, QCPAxis::grid(), QCPLayerable::initializeParentPlot(), mAxes, mInsetLayout, QCPLayerable::mParentPlot, QCPLayoutElement::setMinimumMargins(), QCPLayoutElement::setMinimumSize(), QCPLayerable::setParentLayerable(), setRangeDragAxes(), setRangeZoomAxes(), QCPLayerable::setVisible(), and QCPGrid::setZeroLinePen().
~QCPAxisRect () virtual
Definition at line 11770 of file qcustomplot.cpp.
References axes(), mInsetLayout, and removeAxis().
Member Function Documentation
QList< QCPAxis * > addAxes (QCPAxis::AxisTypes types)
Adds a new axis with addAxis to each axis rect side specified in types. This may be an or-combination of QCPAxis::AxisType, so axes can be added to multiple sides at once.
Returns a list of the added axes.
See Also
addAxis, setupFullAxesBox
Definition at line 11907 of file qcustomplot.cpp.
References addAxis(), QCPAxis::atBottom, QCPAxis::atLeft, QCPAxis::atRight, and QCPAxis::atTop.
QCPAxis * addAxis (QCPAxis::AxisType type, QCPAxis * axis = 0)
Adds a new axis to the axis rect side specified with type, and returns it. If axis is 0, a new QCPAxis instance is created internally.
You may inject QCPAxis instances (or sublasses of QCPAxis) by setting axis to an axis that was previously created outside QCustomPlot. It is important to note that QCustomPlot takes ownership of the axis, so you may not delete it afterwards. Further, the axis must have been created with this axis rect as parent and with the same axis type as specified in type. If this is not the case, a debug output is generated, the axis is not added, and the method returns 0.
This method can not be used to move axis between axis rects. The same axis instance must not be added multiple times to the same or different axis rects.
If an axis rect side already contains one or more axes, the lower and upper endings of the new axis (QCPAxis::setLowerEnding, QCPAxis::setUpperEnding) are set to QCPLineEnding::esHalfBar.
See Also
addAxes, setupFullAxesBox
Definition at line 11865 of file qcustomplot.cpp.
References QCPAxis::atBottom, QCPAxis::atRight, axes(), axis(), QCPAxis::axisRect(), QCPAxis::axisType(), QCPLineEnding::esHalfBar, mAxes, QCPAxis::setLowerEnding(), QCPAxis::setUpperEnding(), and size().
Referenced by addAxes(), QCPAxisRect(), and setupFullAxesBox().
void applyDefaultAntialiasingHint (QCPPainter * painter) const protected virtual
Reimplemented from QCPLayoutElement.
Definition at line 12167 of file qcustomplot.cpp.
References QCPPainter::setAntialiasing().
QList< QCPAxis * > axes (QCPAxis::AxisTypes types) const
Returns all axes on the axis rect sides specified with types.
types may be a single QCPAxis::AxisType or an or-combination, to get the axes of multiple sides.
See Also
axis
Definition at line 11816 of file qcustomplot.cpp.
References QCPAxis::atBottom, QCPAxis::atLeft, QCPAxis::atRight, QCPAxis::atTop, and mAxes.
Referenced by QCustomPlot::rescaleAxes(), and QCustomPlot::selectedAxes().
QList< QCPAxis * > axes () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns all axes of this axis rect.
Definition at line 11834 of file qcustomplot.cpp.
References mAxes.
Referenced by addAxis(), update(), and ~QCPAxisRect().
QCPAxis * axis (QCPAxis::AxisType type, int index = 0) const
Returns the axis with the given index on the axis rect side specified with type.
See Also
axisCount, axes
Definition at line 11795 of file qcustomplot.cpp.
References mAxes.
Referenced by addAxis(), QCPColorScaleAxisRectPrivate::axisSelectableChanged(), QCPColorScaleAxisRectPrivate::axisSelectionChanged(), QCPColorScaleAxisRectPrivate::QCPColorScaleAxisRectPrivate(), QCustomPlot::QCustomPlot(), removeAxis(), and setupFullAxesBox().
int axisCount (QCPAxis::AxisType type) const
Returns the number of axes on the axis rect side specified with type.
See Also
axis
Definition at line 11785 of file qcustomplot.cpp.
References mAxes.
Referenced by setupFullAxesBox().
QPixmap background () const inline
Definition at line 1987 of file qcustomplot.h.
bool backgroundScaled () const inline
Definition at line 1988 of file qcustomplot.h.
Qt::AspectRatioMode backgroundScaledMode () const inline
Definition at line 1989 of file qcustomplot.h.
int bottom () const inline
Returns the pixel position of the bottom border of this axis rect. Margins are not taken into account here, so the returned value is with respect to the inner rect.
Definition at line 2028 of file qcustomplot.h.
Referenced by QCPAxis::coordToPixel(), QCPGrid::drawGridLines(), QCPGrid::drawSubGridLines(), QCPGraph::lowerFillBasePoint(), QCPAxis::pixelToCoord(), and QCPGraph::upperFillBasePoint().
QPoint bottomLeft () const inline
Returns the bottom left corner of this axis rect in pixels. Margins are not taken into account here, so the returned value is with respect to the inner rect.
Definition at line 2034 of file qcustomplot.h.
QPoint bottomRight () const inline
Returns the bottom right corner of this axis rect in pixels. Margins are not taken into account here, so the returned value is with respect to the inner rect.
Definition at line 2035 of file qcustomplot.h.
int calculateAutoMargin (QCP::MarginSide side) protected virtual
Reimplemented from QCPLayoutElement.
Definition at line 12452 of file qcustomplot.cpp.
References QCPAxis::marginSideToAxisType(), QCPLayoutElement::mAutoMargins, mAxes, and updateAxesOffset().
QPoint center () const inline
Returns the center of this axis rect in pixels. Margins are not taken into account here, so the returned value is with respect to the inner rect.
Definition at line 2036 of file qcustomplot.h.
void draw (QCPPainter * painter) protected virtual
Reimplemented from QCPLayoutElement.
Reimplemented in QCPColorScaleAxisRectPrivate.
Definition at line 12173 of file qcustomplot.cpp.
References drawBackground().
Referenced by QCPColorScaleAxisRectPrivate::draw().
void drawBackground (QCPPainter * painter) protected
Definition at line 12397 of file qcustomplot.cpp.
References mBackgroundBrush, mBackgroundPixmap, mBackgroundScaled, mBackgroundScaledMode, QCPLayoutElement::mRect, and mScaledBackgroundPixmap.
Referenced by draw().
QList< QCPLayoutElement * > elements (bool recursive) const virtual
Returns a list of all child elements in this layout element. If recursive is true, all sub-child elements are included in the list, too.
Warning
There may be entries with value 0 in the returned list. (For example, QCPLayoutGrid may have empty cells which yield 0 at the respective index.)
Reimplemented from QCPLayoutElement.
Definition at line 12154 of file qcustomplot.cpp.
References QCPLayout::elements(), and mInsetLayout.
QList< QCPGraph * > graphs () const
Returns a list of all the graphs that are associated with this axis rect.
A graph is considered associated with an axis rect if its key or value axis (or both) is in this axis rect.
See Also
plottables, items
Definition at line 12071 of file qcustomplot.cpp.
References QCustomPlot::mGraphs, and QCPLayerable::mParentPlot.
int height () const inline
Returns the pixel height of this axis rect. Margins are not taken into account here, so the returned value is with respect to the inner rect.
Definition at line 2030 of file qcustomplot.h.
Referenced by QCPAxis::coordToPixel(), QCPBarsGroup::getPixelSpacing(), QCPAxis::pixelToCoord(), and QCPAxis::setScaleRatio().
QCPLayoutInset * insetLayout () const inline
Returns the inset layout of this axis rect. It can be used to place other layout elements (or even layouts with multiple other elements) inside/on top of an axis rect.
See Also
QCPLayoutInset
Definition at line 2017 of file qcustomplot.h.
Referenced by QCustomPlot::QCustomPlot().
QList< QCPAbstractItem * > items () const
Returns a list of all the items that are associated with this axis rect.
An item is considered associated with an axis rect if any of its positions has key or value axis set to an axis that is in this axis rect, or if any of its positions has QCPItemPosition::setAxisRect set to the axis rect, or if the clip axis rect (QCPAbstractItem::setClipAxisRect) is set to this axis rect.
See Also
plottables, graphs
Definition at line 12093 of file qcustomplot.cpp.
References QCustomPlot::mItems, and QCPLayerable::mParentPlot.
int left () const inline
Returns the pixel position of the left border of this axis rect. Margins are not taken into account here, so the returned value is with respect to the inner rect.
Definition at line 2025 of file qcustomplot.h.
Referenced by QCPAxis::coordToPixel(), QCPGrid::drawGridLines(), QCPGrid::drawSubGridLines(), QCPGraph::lowerFillBasePoint(), QCPAxis::pixelToCoord(), and QCPGraph::upperFillBasePoint().
void mouseMoveEvent (QMouseEvent * event) protected virtual
This event is called, if the mouse is moved inside the outer rect of this layout element.
Reimplemented from QCPLayoutElement.
Definition at line 12508 of file qcustomplot.cpp.
References QCP::aeAll, QCustomPlot::interactions(), QCP::iRangeDrag, QCPRange::lower, mDragging, mDragStart, mDragStartHorzRange, mDragStartVertRange, QCPLayerable::mParentPlot, mRangeDrag, mRangeDragHorzAxis, mRangeDragVertAxis, QCustomPlot::noAntialiasingOnDrag(), QCustomPlot::replot(), QCustomPlot::setNotAntialiasedElements(), QCPAxis::stLinear, QCPAxis::stLogarithmic, and QCPRange::upper.
void mousePressEvent (QMouseEvent * event) protected virtual
This event is called, if the mouse was pressed while being inside the outer rect of this layout element.
Reimplemented from QCPLayoutElement.
Definition at line 12478 of file qcustomplot.cpp.
References QCustomPlot::antialiasedElements(), QCustomPlot::interactions(), QCP::iRangeDrag, mAADragBackup, mDragging, mDragStart, mDragStartHorzRange, mDragStartVertRange, mNotAADragBackup, QCPLayerable::mParentPlot, mRangeDragHorzAxis, mRangeDragVertAxis, QCustomPlot::noAntialiasingOnDrag(), and QCustomPlot::notAntialiasedElements().
void mouseReleaseEvent (QMouseEvent * event) protected virtual
This event is called, if the mouse was previously pressed inside the outer rect of this layout element and is now released.
Reimplemented from QCPLayoutElement.
Definition at line 12553 of file qcustomplot.cpp.
References mAADragBackup, mDragging, mNotAADragBackup, QCPLayerable::mParentPlot, QCustomPlot::noAntialiasingOnDrag(), QCustomPlot::setAntialiasedElements(), and QCustomPlot::setNotAntialiasedElements().
QList< QCPAbstractPlottable * > plottables () const
Returns a list of all the plottables that are associated with this axis rect.
A plottable is considered associated with an axis rect if its key or value axis (or both) is in this axis rect.
See Also
graphs, items
Definition at line 12051 of file qcustomplot.cpp.
References QCPLayerable::mParentPlot, and QCustomPlot::mPlottables.
Qt::Orientations rangeDrag () const inline
Definition at line 1990 of file qcustomplot.h.
QCPAxis * rangeDragAxis (Qt::Orientation orientation)
Returns the range drag axis of the orientation provided.
See Also
setRangeDragAxes
Definition at line 12262 of file qcustomplot.cpp.
References mRangeDragHorzAxis, and mRangeDragVertAxis.
Qt::Orientations rangeZoom () const inline
Definition at line 1991 of file qcustomplot.h.
QCPAxis * rangeZoomAxis (Qt::Orientation orientation)
Returns the range zoom axis of the orientation provided.
See Also
setRangeZoomAxes
Definition at line 12272 of file qcustomplot.cpp.
References mRangeZoomHorzAxis, and mRangeZoomVertAxis.
double rangeZoomFactor (Qt::Orientation orientation)
Returns the range zoom factor of the orientation provided.
See Also
setRangeZoomFactor
Definition at line 12282 of file qcustomplot.cpp.
References mRangeZoomFactorHorz, and mRangeZoomFactorVert.
bool removeAxis (QCPAxis * axis)
Removes the specified axis from the axis rect and deletes it.
Returns true on success, i.e. if axis was a valid axis in this axis rect.
See Also
addAxis
Definition at line 11928 of file qcustomplot.cpp.
References axis(), QCustomPlot::axisRemoved(), mAxes, and QCPLayerable::parentPlot().
Referenced by ~QCPAxisRect().
int right () const inline
Returns the pixel position of the right border of this axis rect. Margins are not taken into account here, so the returned value is with respect to the inner rect.
Definition at line 2026 of file qcustomplot.h.
Referenced by QCPAxis::coordToPixel(), QCPGrid::drawGridLines(), QCPGrid::drawSubGridLines(), QCPGraph::lowerFillBasePoint(), and QCPGraph::upperFillBasePoint().
void setBackground (const QPixmap & pm)
Sets pm as the axis background pixmap. The axis background pixmap will be drawn inside the axis rect. Since axis rects place themselves on the "background" layer by default, the axis rect backgrounds are usually drawn below everything else.
For cases where the provided pixmap doesn't have the same size as the axis rect, scaling can be enabled with setBackgroundScaled and the scaling mode (i.e. whether and how the aspect ratio is preserved) can be set with setBackgroundScaledMode. To set all these options in one call, consider using the overloaded version of this function.
Below the pixmap, the axis rect may be optionally filled with a brush, if specified with setBackground(const QBrush &brush).
See Also
setBackgroundScaled, setBackgroundScaledMode, setBackground(const QBrush &brush)
Definition at line 12193 of file qcustomplot.cpp.
References mBackgroundPixmap, and mScaledBackgroundPixmap.
void setBackground (const QPixmap & pm, bool scaled, Qt::AspectRatioMode mode = Qt::KeepAspectRatioByExpanding)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Allows setting the background pixmap of the axis rect, whether it shall be scaled and how it shall be scaled in one call.
See Also
setBackground(const QPixmap &pm), setBackgroundScaled, setBackgroundScaledMode
Definition at line 12224 of file qcustomplot.cpp.
References mBackgroundPixmap, mBackgroundScaled, mBackgroundScaledMode, and mScaledBackgroundPixmap.
void setBackground (const QBrush & brush)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Sets brush as the background brush. The axis rect background will be filled with this brush. Since axis rects place themselves on the "background" layer by default, the axis rect backgrounds are usually drawn below everything else.
The brush will be drawn before (under) any background pixmap, which may be specified with setBackground(const QPixmap &pm).
To disable drawing of a background brush, set brush to Qt::NoBrush.
See Also
setBackground(const QPixmap &pm)
Definition at line 12212 of file qcustomplot.cpp.
References mBackgroundBrush.
void setBackgroundScaled (bool scaled)
Sets whether the axis background pixmap shall be scaled to fit the axis rect or not. If scaled is set to true, you may control whether and how the aspect ratio of the original pixmap is preserved with setBackgroundScaledMode.
Note that the scaled version of the original pixmap is buffered, so there is no performance penalty on replots. (Except when the axis rect dimensions are changed continuously.)
See Also
setBackground, setBackgroundScaledMode
Definition at line 12242 of file qcustomplot.cpp.
References mBackgroundScaled.
void setBackgroundScaledMode (Qt::AspectRatioMode mode)
If scaling of the axis background pixmap is enabled (setBackgroundScaled), use this function to define whether and how the aspect ratio of the original pixmap passed to setBackground is preserved.
See Also
setBackground, setBackgroundScaled
Definition at line 12252 of file qcustomplot.cpp.
References mBackgroundScaledMode.
void setRangeDrag (Qt::Orientations orientations)
Sets which axis orientation may be range dragged by the user with mouse interaction. What orientation corresponds to which specific axis can be set with setRangeDragAxes(QCPAxis *horizontal, QCPAxis *vertical). By default, the horizontal axis is the bottom axis (xAxis) and the vertical axis is the left axis (yAxis).
To disable range dragging entirely, pass 0 as orientations or remove QCP::iRangeDrag from QCustomPlot::setInteractions. To enable range dragging for both directions, pass Qt::Horizontal | Qt::Vertical as orientations.
In addition to setting orientations to a non-zero value, make sure QCustomPlot::setInteractions contains QCP::iRangeDrag to enable the range dragging interaction.
See Also
setRangeZoom, setRangeDragAxes, QCustomPlot::setNoAntialiasingOnDrag
Definition at line 12303 of file qcustomplot.cpp.
References mRangeDrag.
void setRangeDragAxes (QCPAxis * horizontal, QCPAxis * vertical)
Sets the axes whose range will be dragged when setRangeDrag enables mouse range dragging on the QCustomPlot widget.
See Also
setRangeZoomAxes
Definition at line 12334 of file qcustomplot.cpp.
References mRangeDragHorzAxis, and mRangeDragVertAxis.
Referenced by QCPAxisRect().
void setRangeZoom (Qt::Orientations orientations)
Sets which axis orientation may be zoomed by the user with the mouse wheel. What orientation corresponds to which specific axis can be set with setRangeZoomAxes(QCPAxis *horizontal, QCPAxis *vertical). By default, the horizontal axis is the bottom axis (xAxis) and the vertical axis is the left axis (yAxis).
To disable range zooming entirely, pass 0 as orientations or remove QCP::iRangeZoom from QCustomPlot::setInteractions. To enable range zooming for both directions, pass Qt::Horizontal | Qt::Vertical as orientations.
In addition to setting orientations to a non-zero value, make sure QCustomPlot::setInteractions contains QCP::iRangeZoom to enable the range zooming interaction.
See Also
setRangeZoomFactor, setRangeZoomAxes, setRangeDrag
Definition at line 12323 of file qcustomplot.cpp.
References mRangeZoom.
void setRangeZoomAxes (QCPAxis * horizontal, QCPAxis * vertical)
Sets the axes whose range will be zoomed when setRangeZoom enables mouse wheel zooming on the QCustomPlot widget. The two axes can be zoomed with different strengths, when different factors are passed to setRangeZoomFactor(double horizontalFactor, double verticalFactor).
See Also
setRangeDragAxes
Definition at line 12347 of file qcustomplot.cpp.
References mRangeZoomHorzAxis, and mRangeZoomVertAxis.
Referenced by QCPAxisRect().
void setRangeZoomFactor (double horizontalFactor, double verticalFactor)
Sets how strong one rotation step of the mouse wheel zooms, when range zoom was activated with setRangeZoom. The two parameters horizontalFactor and verticalFactor provide a way to let the horizontal axis zoom at different rates than the vertical axis. Which axis is horizontal and which is vertical, can be set with setRangeZoomAxes.
When the zoom factor is greater than one, scrolling the mouse wheel backwards (towards the user) will zoom in (make the currently visible range smaller). For zoom factors smaller than one, the same scrolling direction will zoom out.
Definition at line 12363 of file qcustomplot.cpp.
References mRangeZoomFactorHorz, and mRangeZoomFactorVert.
void setRangeZoomFactor (double factor)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Sets both the horizontal and vertical zoom factor.
Definition at line 12373 of file qcustomplot.cpp.
References mRangeZoomFactorHorz, and mRangeZoomFactorVert.
void setupFullAxesBox (bool connectRanges = false)
Convenience function to create an axis on each side that doesn't have any axes yet and set their visibility to true. Further, the top/right axes are assigned the following properties of the bottom/left axes:
range (QCPAxis::setRange)
range reversed (QCPAxis::setRangeReversed)
scale type (QCPAxis::setScaleType)
scale log base (QCPAxis::setScaleLogBase)
ticks (QCPAxis::setTicks)
auto (major) tick count (QCPAxis::setAutoTickCount)
sub tick count (QCPAxis::setSubTickCount)
auto sub ticks (QCPAxis::setAutoSubTicks)
tick step (QCPAxis::setTickStep)
auto tick step (QCPAxis::setAutoTickStep)
number format (QCPAxis::setNumberFormat)
number precision (QCPAxis::setNumberPrecision)
tick label type (QCPAxis::setTickLabelType)
date time format (QCPAxis::setDateTimeFormat)
date time spec (QCPAxis::setDateTimeSpec)
Tick labels (QCPAxis::setTickLabels) of the right and top axes are set to false.
If connectRanges is true, the rangeChanged signals of the bottom and left axes are connected to the QCPAxis::setRange slots of the top and right axes.
Definition at line 11974 of file qcustomplot.cpp.
References addAxis(), QCPAxis::atBottom, QCPAxis::atLeft, QCPAxis::atRight, QCPAxis::atTop, QCPAxis::autoSubTicks(), QCPAxis::autoTickCount(), QCPAxis::autoTickStep(), axis(), axisCount(), QCPAxis::dateTimeFormat(), QCPAxis::dateTimeSpec(), QCPAxis::numberFormat(), QCPAxis::numberPrecision(), QCPAxis::range(), QCPAxis::rangeReversed(), QCPAxis::scaleLogBase(), QCPAxis::scaleType(), QCPAxis::setAutoSubTicks(), QCPAxis::setAutoTickCount(), QCPAxis::setAutoTickStep(), QCPAxis::setDateTimeFormat(), QCPAxis::setDateTimeSpec(), QCPAxis::setNumberFormat(), QCPAxis::setNumberPrecision(), QCPAxis::setRange(), QCPAxis::setRangeReversed(), QCPAxis::setScaleLogBase(), QCPAxis::setScaleType(), QCPAxis::setSubTickCount(), QCPAxis::setTickLabels(), QCPAxis::setTickLabelType(), QCPAxis::setTicks(), QCPAxis::setTickStep(), QCPLayerable::setVisible(), QCPAxis::subTickCount(), QCPAxis::tickLabelType(), QCPAxis::ticks(), and QCPAxis::tickStep().
QSize size () const inline
Returns the pixel size of this axis rect. Margins are not taken into account here, so the returned value is with respect to the inner rect.
Definition at line 2031 of file qcustomplot.h.
Referenced by addAxis().
int top () const inline
Returns the pixel position of the top border of this axis rect. Margins are not taken into account here, so the returned value is with respect to the inner rect.
Definition at line 2027 of file qcustomplot.h.
Referenced by QCPAxis::coordToPixel(), QCPGrid::drawGridLines(), QCPGrid::drawSubGridLines(), QCPGraph::lowerFillBasePoint(), and QCPGraph::upperFillBasePoint().
QPoint topLeft () const inline
Returns the top left corner of this axis rect in pixels. Margins are not taken into account here, so the returned value is with respect to the inner rect.
Definition at line 2032 of file qcustomplot.h.
QPoint topRight () const inline
Returns the top right corner of this axis rect in pixels. Margins are not taken into account here, so the returned value is with respect to the inner rect.
Definition at line 2033 of file qcustomplot.h.
void update (UpdatePhase phase) virtual
This method is called automatically upon replot and doesn't need to be called by users of QCPAxisRect.
Calls the base class implementation to update the margins (see QCPLayoutElement::update), and finally passes the rect to the inset layout (insetLayout) and calls its QCPInsetLayout::update function.
Reimplemented from QCPLayoutElement.
Definition at line 12128 of file qcustomplot.cpp.
References axes(), mInsetLayout, QCPLayoutElement::rect(), QCPLayoutElement::setOuterRect(), QCPLayoutElement::update(), QCPLayout::update(), QCPLayoutElement::upLayout, and QCPLayoutElement::upPreparation.
void updateAxesOffset (QCPAxis::AxisType type) protected
Definition at line 12431 of file qcustomplot.cpp.
References mAxes.
Referenced by calculateAutoMargin().
void wheelEvent (QWheelEvent * event) protected virtual
This event is called, if the mouse wheel is scrolled while the cursor is inside the rect of this layout element.
Reimplemented from QCPLayoutElement.
Definition at line 12578 of file qcustomplot.cpp.
References QCustomPlot::interactions(), QCP::iRangeZoom, QCPLayerable::mParentPlot, mRangeZoom, mRangeZoomFactorHorz, mRangeZoomFactorVert, mRangeZoomHorzAxis, mRangeZoomVertAxis, and QCustomPlot::replot().
int width () const inline
Returns the pixel width of this axis rect. Margins are not taken into account here, so the returned value is with respect to the inner rect.
Definition at line 2029 of file qcustomplot.h.
Referenced by QCPAxis::coordToPixel(), QCPBarsGroup::getPixelSpacing(), QCPAxis::pixelToCoord(), and QCPAxis::setScaleRatio().
Friends And Related Function Documentation
friend class QCustomPlot friend
Definition at line 2077 of file qcustomplot.h.
Member Data Documentation
QCP::AntialiasedElements mAADragBackup protected
Definition at line 2055 of file qcustomplot.h.
Referenced by mousePressEvent(), and mouseReleaseEvent().
QHash<QCPAxis::AxisType, QList<QCPAxis*> > mAxes protected
Definition at line 2058 of file qcustomplot.h.
Referenced by addAxis(), axes(), axis(), axisCount(), calculateAutoMargin(), QCPAxisRect(), removeAxis(), and updateAxesOffset().
QBrush mBackgroundBrush protected
Definition at line 2044 of file qcustomplot.h.
Referenced by drawBackground(), and setBackground().
QPixmap mBackgroundPixmap protected
Definition at line 2045 of file qcustomplot.h.
Referenced by drawBackground(), and setBackground().
bool mBackgroundScaled protected
Definition at line 2047 of file qcustomplot.h.
Referenced by drawBackground(), setBackground(), and setBackgroundScaled().
Qt::AspectRatioMode mBackgroundScaledMode protected
Definition at line 2048 of file qcustomplot.h.
Referenced by drawBackground(), setBackground(), and setBackgroundScaledMode().
bool mDragging protected
Definition at line 2057 of file qcustomplot.h.
Referenced by mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
QPoint mDragStart protected
Definition at line 2056 of file qcustomplot.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
QCPRange mDragStartHorzRange protected
Definition at line 2054 of file qcustomplot.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
QCPRange mDragStartVertRange protected
Definition at line 2054 of file qcustomplot.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
QCPLayoutInset* mInsetLayout protected
Definition at line 2049 of file qcustomplot.h.
Referenced by elements(), QCPAxisRect(), update(), and ~QCPAxisRect().
QCP::AntialiasedElements mNotAADragBackup protected
Definition at line 2055 of file qcustomplot.h.
Referenced by mousePressEvent(), and mouseReleaseEvent().
Qt::Orientations mRangeDrag protected
Definition at line 2050 of file qcustomplot.h.
Referenced by mouseMoveEvent(), and setRangeDrag().
QPointer<QCPAxis> mRangeDragHorzAxis protected
Definition at line 2051 of file qcustomplot.h.
Referenced by mouseMoveEvent(), mousePressEvent(), rangeDragAxis(), and setRangeDragAxes().
QPointer<QCPAxis> mRangeDragVertAxis protected
Definition at line 2051 of file qcustomplot.h.
Referenced by mouseMoveEvent(), mousePressEvent(), rangeDragAxis(), and setRangeDragAxes().
Qt::Orientations mRangeZoom protected
Definition at line 2050 of file qcustomplot.h.
Referenced by setRangeZoom(), and wheelEvent().
double mRangeZoomFactorHorz protected
Definition at line 2052 of file qcustomplot.h.
Referenced by rangeZoomFactor(), setRangeZoomFactor(), and wheelEvent().
double mRangeZoomFactorVert protected
Definition at line 2052 of file qcustomplot.h.
Referenced by rangeZoomFactor(), setRangeZoomFactor(), and wheelEvent().
QPointer<QCPAxis> mRangeZoomHorzAxis protected
Definition at line 2051 of file qcustomplot.h.
Referenced by rangeZoomAxis(), setRangeZoomAxes(), and wheelEvent().
QPointer<QCPAxis> mRangeZoomVertAxis protected
Definition at line 2051 of file qcustomplot.h.
Referenced by rangeZoomAxis(), setRangeZoomAxes(), and wheelEvent().
QPixmap mScaledBackgroundPixmap protected
Definition at line 2046 of file qcustomplot.h.
Referenced by drawBackground(), and setBackground().
The documentation for this class was generated from the following files:
qcustomplot.h
qcustomplot.cpp