SETestKCL: QCPColorGradient Class Reference
QCPColorGradient Class Reference
#include <qcustomplot.h>
Public Types
enum ColorInterpolation { ciRGB, ciHSV }
enum GradientPreset {
gpGrayscale, gpHot, gpCold, gpNight,
gpCandy, gpGeography, gpIon, gpThermal,
gpPolar, gpSpectrum, gpJet, gpHues
}
Public Member Functions
QCPColorGradient (GradientPreset preset=gpCold)
bool operator== (const QCPColorGradient &other) const
bool operator!= (const QCPColorGradient &other) const
int levelCount () const
QMap< double, QColor > colorStops () const
ColorInterpolation colorInterpolation () const
bool periodic () const
void setLevelCount (int n)
void setColorStops (const QMap< double, QColor > &colorStops)
void setColorStopAt (double position, const QColor &color)
void setColorInterpolation (ColorInterpolation interpolation)
void setPeriodic (bool enabled)
void colorize (const double *data, const QCPRange &range, QRgb *scanLine, int n, int dataIndexFactor=1, bool logarithmic=false)
QRgb color (double position, const QCPRange &range, bool logarithmic=false)
void loadPreset (GradientPreset preset)
void clearColorStops ()
QCPColorGradient inverted () const
Protected Member Functions
void updateColorBuffer ()
Protected Attributes
int mLevelCount
QMap< double, QColor > mColorStops
ColorInterpolation mColorInterpolation
bool mPeriodic
QVector< QRgb > mColorBuffer
bool mColorBufferInvalidated
Detailed Description
Defines a color gradient for use with e.g. QCPColorMap.
This class describes a color gradient which can be used to encode data with color. For example, QCPColorMap and QCPColorScale have setGradient methods which take an instance of this class. Colors are set with setColorStopAt(double position, const QColor &color) with a position from 0 to 1. In between these defined color positions, the color will be interpolated linearly either in RGB or HSV space, see setColorInterpolation.
Alternatively, load one of the preset color gradients shown in the image below, with loadPreset, or by directly specifying the preset in the constructor.
The fact that the QCPColorGradient(GradientPreset preset) constructor allows directly converting a GradientPreset to a QCPColorGradient, you can also directly pass GradientPreset to all the setGradient methods, e.g.:
The total number of levels used in the gradient can be set with setLevelCount. Whether the color gradient shall be applied periodically (wrapping around) to data values that lie outside the data range specified on the plottable instance can be controlled with setPeriodic.
Definition at line 1900 of file qcustomplot.h.
Member Enumeration Documentation
enum ColorInterpolation
Defines the color spaces in which color interpolation between gradient stops can be performed.
See Also
setColorInterpolation
Enumerator
ciRGB
Color channels red, green and blue are linearly interpolated.
ciHSV
Color channels hue, saturation and value are linearly interpolated (The hue is interpolated over the shortest angle distance)
Definition at line 1909 of file qcustomplot.h.
enum GradientPreset
Defines the available presets that can be loaded with loadPreset. See the documentation there for an image of the presets.
Enumerator
gpGrayscale
Continuous lightness from black to white (suited for non-biased data representation)
gpHot
Continuous lightness from black over firey colors to white (suited for non-biased data representation)
gpCold
Continuous lightness from black over icey colors to white (suited for non-biased data representation)
gpNight
Continuous lightness from black over weak blueish colors to white (suited for non-biased data representation)
gpCandy
Blue over pink to white.
gpGeography
Colors suitable to represent different elevations on geographical maps.
gpIon
Half hue spectrum from black over purple to blue and finally green (creates banding illusion but allows more precise magnitude estimates)
gpThermal
Colors suitable for thermal imaging, ranging from dark blue over purple to orange, yellow and white.
gpPolar
Colors suitable to emphasize polarity around the center, with blue for negative, black in the middle and red for positive values.
gpSpectrum
An approximation of the visible light spectrum (creates banding illusion but allows more precise magnitude estimates)
gpJet
Hue variation similar to a spectrum, often used in numerical visualization (creates banding illusion but allows more precise magnitude estimates)
gpHues
Full hue cycle, with highest and lowest color red (suitable for periodic data, such as angles and phases, see setPeriodic)
Definition at line 1918 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPColorGradient (GradientPreset preset = gpCold)
Constructs a new QCPColorGradient initialized with the colors and color interpolation according to preset.
The color level count is initialized to 350.
Definition at line 11178 of file qcustomplot.cpp.
References loadPreset(), mColorBuffer, and mLevelCount.
Member Function Documentation
void clearColorStops ()
Clears all color stops.
See Also
setColorStops, setColorStopAt
Definition at line 11509 of file qcustomplot.cpp.
References mColorBufferInvalidated, and mColorStops.
Referenced by inverted(), and loadPreset().
QRgb color (double position, const QCPRange & range, bool logarithmic = false)
Definition at line 11368 of file qcustomplot.cpp.
References QCPRange::lower, mColorBuffer, mColorBufferInvalidated, mLevelCount, mPeriodic, QCPRange::size(), updateColorBuffer(), and QCPRange::upper.
Referenced by QCPColorScaleAxisRectPrivate::updateGradientImage().
ColorInterpolation colorInterpolation () const inline
Definition at line 1940 of file qcustomplot.h.
void colorize (const double * data, const QCPRange & range, QRgb * scanLine, int n, int dataIndexFactor = 1, bool logarithmic = false)
This method is used to quickly convert a data array to colors. The colors will be output in the array scanLine. Both data and scanLine must have the length n when passed to this function. The data range that shall be used for mapping the data value to the gradient is passed in range. logarithmic indicates whether the data values shall be mapped to colors logarithmically.
if data actually contains 2D-data linearized via [row*columnCount + column], you can set dataIndexFactor to columnCount to convert a column instead of a row of the data array, in scanLine. scanLine will remain a regular (1D) array. This works because data is addressed data[i*dataIndexFactor].
Definition at line 11293 of file qcustomplot.cpp.
References QCPRange::lower, mColorBuffer, mColorBufferInvalidated, mLevelCount, mPeriodic, QCPRange::size(), updateColorBuffer(), and QCPRange::upper.
Referenced by QCPColorScaleAxisRectPrivate::updateGradientImage(), and QCPColorMap::updateMapImage().
QMap<double, QColor> colorStops () const inline
Definition at line 1939 of file qcustomplot.h.
Referenced by setColorStops().
QCPColorGradient inverted () const
Returns an inverted gradient. The inverted gradient has all properties as this QCPColorGradient, but the order of the color stops is inverted.
See Also
setColorStops, setColorStopAt
Definition at line 11521 of file qcustomplot.cpp.
References clearColorStops(), mColorStops, and setColorStopAt().
int levelCount () const inline
Definition at line 1938 of file qcustomplot.h.
Referenced by QCPColorScaleAxisRectPrivate::updateGradientImage().
void loadPreset (GradientPreset preset)
Clears the current color stops and loads the specified preset. A preset consists of predefined color stops and the corresponding color interpolation method.
The available presets are:
Definition at line 11400 of file qcustomplot.cpp.
References ciHSV, ciRGB, clearColorStops(), gpCandy, gpCold, gpGeography, gpGrayscale, gpHot, gpHues, gpIon, gpJet, gpNight, gpPolar, gpSpectrum, gpThermal, setColorInterpolation(), and setColorStopAt().
Referenced by QCPColorGradient().
bool operator!= (const QCPColorGradient & other) const inline
Definition at line 1935 of file qcustomplot.h.
bool operator== (const QCPColorGradient & other) const
Definition at line 11189 of file qcustomplot.cpp.
References mColorInterpolation, mColorStops, mLevelCount, and mPeriodic.
bool periodic () const inline
Definition at line 1941 of file qcustomplot.h.
void setColorInterpolation (QCPColorGradient::ColorInterpolation interpolation)
Sets whether the colors in between the configured color stops (see setColorStopAt) shall be interpolated linearly in RGB or in HSV color space.
For example, a sweep in RGB space from red to green will have a muddy brown intermediate color, whereas in HSV space the intermediate color is yellow.
Definition at line 11252 of file qcustomplot.cpp.
References mColorBufferInvalidated, and mColorInterpolation.
Referenced by loadPreset().
void setColorStopAt (double position, const QColor & color)
Sets the color the gradient will have at the specified position (from 0 to 1). In between these color stops, the color is interpolated according to setColorInterpolation.
See Also
setColorStops, clearColorStops
Definition at line 11239 of file qcustomplot.cpp.
References mColorBufferInvalidated, and mColorStops.
Referenced by inverted(), and loadPreset().
void setColorStops (const QMap< double, QColor > & colorStops)
Sets at which positions from 0 to 1 which color shall occur. The positions are the keys, the colors are the values of the passed QMap colorStops. In between these color stops, the color is interpolated according to setColorInterpolation.
A more convenient way to create a custom gradient may be to clear all color stops with clearColorStops and then adding them one by one with setColorStopAt.
See Also
clearColorStops
Definition at line 11227 of file qcustomplot.cpp.
References colorStops(), mColorBufferInvalidated, and mColorStops.
void setLevelCount (int n)
Sets the number of discretization levels of the color gradient to n. The default is 350 which is typically enough to create a smooth appearance.
Definition at line 11203 of file qcustomplot.cpp.
References mColorBufferInvalidated, and mLevelCount.
void setPeriodic (bool enabled)
Sets whether data points that are outside the configured data range (e.g. QCPColorMap::setDataRange) are colored by periodically repeating the color gradient or whether they all have the same color, corresponding to the respective gradient boundary color.
As shown in the image above, gradients that have the same start and end color are especially suitable for a periodic gradient mapping, since they produce smooth color transitions throughout the color map. A preset that has this property is gpHues.
In practice, using periodic color gradients makes sense when the data corresponds to a periodic dimension, such as an angle or a phase. If this is not the case, the color encoding might become ambiguous, because multiple different data values are shown as the same color.
Definition at line 11276 of file qcustomplot.cpp.
References mPeriodic.
void updateColorBuffer () protected
Definition at line 11535 of file qcustomplot.cpp.
References ciHSV, ciRGB, mColorBuffer, mColorBufferInvalidated, mColorInterpolation, mColorStops, and mLevelCount.
Referenced by color(), and colorize().
Member Data Documentation
QVector<QRgb> mColorBuffer protected
Definition at line 1967 of file qcustomplot.h.
Referenced by color(), colorize(), QCPColorGradient(), and updateColorBuffer().
bool mColorBufferInvalidated protected
Definition at line 1968 of file qcustomplot.h.
Referenced by clearColorStops(), color(), colorize(), setColorInterpolation(), setColorStopAt(), setColorStops(), setLevelCount(), and updateColorBuffer().
ColorInterpolation mColorInterpolation protected
Definition at line 1963 of file qcustomplot.h.
Referenced by operator==(), setColorInterpolation(), and updateColorBuffer().
QMap<double, QColor> mColorStops protected
Definition at line 1962 of file qcustomplot.h.
Referenced by clearColorStops(), inverted(), operator==(), setColorStopAt(), setColorStops(), and updateColorBuffer().
int mLevelCount protected
Definition at line 1961 of file qcustomplot.h.
Referenced by color(), colorize(), operator==(), QCPColorGradient(), setLevelCount(), and updateColorBuffer().
bool mPeriodic protected
Definition at line 1964 of file qcustomplot.h.
Referenced by color(), colorize(), operator==(), and setPeriodic().
The documentation for this class was generated from the following files:
qcustomplot.h
qcustomplot.cpp