SETestKCL: QCPItemCurve Class Reference
QCPItemCurve Class Reference
#include <qcustomplot.h>
Public Member Functions
QCPItemCurve (QCustomPlot *parentPlot)
virtual ~QCPItemCurve ()
QPen pen () const
QPen selectedPen () const
QCPLineEnding head () const
QCPLineEnding tail () const
void setPen (const QPen &pen)
void setSelectedPen (const QPen &pen)
void setHead (const QCPLineEnding &head)
void setTail (const QCPLineEnding &tail)
virtual double selectTest (const QPointF &pos, bool onlySelectable, QVariant *details=0) const
Public Member Functions inherited from QCPAbstractItem
QCPAbstractItem (QCustomPlot *parentPlot)
virtual ~QCPAbstractItem ()
bool clipToAxisRect () const
QCPAxisRect * clipAxisRect () const
bool selectable () const
bool selected () const
void setClipToAxisRect (bool clip)
void setClipAxisRect (QCPAxisRect *rect)
Q_SLOT void setSelectable (bool selectable)
Q_SLOT void setSelected (bool selected)
QList< QCPItemPosition * > positions () const
QList< QCPItemAnchor * > anchors () const
QCPItemPosition * position (const QString &name) const
QCPItemAnchor * anchor (const QString &name) const
bool hasAnchor (const QString &name) const
Public Member Functions inherited from QCPLayerable
QCPLayerable (QCustomPlot *plot, QString targetLayer=QString(), QCPLayerable *parentLayerable=0)
~QCPLayerable ()
bool visible () const
QCustomPlot * parentPlot () const
QCPLayerable * parentLayerable () const
QCPLayer * layer () const
bool antialiased () const
void setVisible (bool on)
Q_SLOT bool setLayer (QCPLayer *layer)
bool setLayer (const QString &layerName)
void setAntialiased (bool enabled)
bool realVisibility () const
Public Attributes
QCPItemPosition *const start
QCPItemPosition *const startDir
QCPItemPosition *const endDir
QCPItemPosition *const end
Protected Member Functions
virtual void draw (QCPPainter *painter)
QPen mainPen () const
Protected Member Functions inherited from QCPAbstractItem
virtual QCP::Interaction selectionCategory () const
virtual QRect clipRect () const
virtual void applyDefaultAntialiasingHint (QCPPainter *painter) const
virtual void selectEvent (QMouseEvent *event, bool additive, const QVariant &details, bool *selectionStateChanged)
virtual void deselectEvent (bool *selectionStateChanged)
virtual QPointF anchorPixelPoint (int anchorId) const
double distSqrToLine (const QPointF &start, const QPointF &end, const QPointF &point) const
double rectSelectTest (const QRectF &rect, const QPointF &pos, bool filledRect) const
QCPItemPosition * createPosition (const QString &name)
QCPItemAnchor * createAnchor (const QString &name, int anchorId)
Protected Member Functions inherited from QCPLayerable
virtual void parentPlotInitialized (QCustomPlot *parentPlot)
void initializeParentPlot (QCustomPlot *parentPlot)
void setParentLayerable (QCPLayerable *parentLayerable)
bool moveToLayer (QCPLayer *layer, bool prepend)
void applyAntialiasingHint (QCPPainter *painter, bool localAntialiased, QCP::AntialiasedElement overrideElement) const
Protected Attributes
QPen mPen
QPen mSelectedPen
QCPLineEnding mHead
QCPLineEnding mTail
Protected Attributes inherited from QCPAbstractItem
bool mClipToAxisRect
QPointer< QCPAxisRect > mClipAxisRect
QList< QCPItemPosition * > mPositions
QList< QCPItemAnchor * > mAnchors
bool mSelectable
bool mSelected
Protected Attributes inherited from QCPLayerable
bool mVisible
QCustomPlot * mParentPlot
QPointer< QCPLayerable > mParentLayerable
QCPLayer * mLayer
bool mAntialiased
Additional Inherited Members
Signals inherited from QCPAbstractItem
void selectionChanged (bool selected)
void selectableChanged (bool selectable)
Signals inherited from QCPLayerable
void layerChanged (QCPLayer *newLayer)
Detailed Description
A curved line from one point to another.
Curve example. Blue dotted circles are anchors, solid blue discs are positions.
It has four positions, start and end, which define the end points of the line, and two control points which define the direction the line exits from the start and the direction from which it approaches the end: startDir and endDir.
With setHead and setTail you may set different line ending styles, e.g. to create an arrow.
Often it is desirable for the control points to stay at fixed relative positions to the start/end point. This can be achieved by setting the parent anchor e.g. of startDir simply to start, and then specify the desired pixel offset with QCPItemPosition::setCoords on startDir.
Definition at line 3321 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPItemCurve (QCustomPlot * parentPlot)
Creates a curve item and sets default values.
The constructed item can be added to the plot with QCustomPlot::addItem.
Definition at line 21896 of file qcustomplot.cpp.
References end, endDir, QCPItemPosition::setCoords(), setPen(), setSelectedPen(), start, and startDir.
~QCPItemCurve () virtual
Definition at line 21912 of file qcustomplot.cpp.
Member Function Documentation
void draw (QCPPainter * painter) protected virtual
Implements QCPAbstractItem.
Definition at line 21989 of file qcustomplot.cpp.
References QCPAbstractItem::clipRect(), QCPLineEnding::draw(), end, endDir, QCPLineEnding::esNone, mainPen(), mHead, mTail, QCPItemPosition::pixelPoint(), QCPPainter::setPen(), start, startDir, and QCPLineEnding::style().
QCPLineEnding head () const inline
Definition at line 3337 of file qcustomplot.h.
Referenced by setHead().
QPen mainPen () const protected
Definition at line 22023 of file qcustomplot.cpp.
References mPen, QCPAbstractItem::mSelected, and mSelectedPen.
Referenced by draw().
QPen pen () const inline
Definition at line 3335 of file qcustomplot.h.
Referenced by setPen(), and setSelectedPen().
QPen selectedPen () const inline
Definition at line 3336 of file qcustomplot.h.
double selectTest (const QPointF & pos, bool onlySelectable, QVariant * details = 0) const virtual
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
You may pass 0 as details to indicate that you are not interested in those selection details.
See Also
selectEvent, deselectEvent, QCustomPlot::setInteractions
Implements QCPAbstractItem.
Definition at line 21963 of file qcustomplot.cpp.
References QCPAbstractItem::distSqrToLine(), end, endDir, QCPAbstractItem::mSelectable, QCPItemPosition::pixelPoint(), start, and startDir.
void setHead (const QCPLineEnding & head)
Sets the line ending style of the head. The head corresponds to the end position.
Note that due to the overloaded QCPLineEnding constructor, you may directly specify a QCPLineEnding::EndingStyle here, e.g.
setHead(QCPLineEnding::esSpikeArrow)
See Also
setTail
Definition at line 21944 of file qcustomplot.cpp.
References head(), and mHead.
void setPen (const QPen & pen)
Sets the pen that will be used to draw the line
See Also
setSelectedPen
Definition at line 21921 of file qcustomplot.cpp.
References mPen, and pen().
Referenced by QCPItemCurve().
void setSelectedPen (const QPen & pen)
Sets the pen that will be used to draw the line when selected
See Also
setPen, setSelected
Definition at line 21931 of file qcustomplot.cpp.
References mSelectedPen, and pen().
Referenced by QCPItemCurve().
void setTail (const QCPLineEnding & tail)
Sets the line ending style of the tail. The tail corresponds to the start position.
Note that due to the overloaded QCPLineEnding constructor, you may directly specify a QCPLineEnding::EndingStyle here, e.g.
setTail(QCPLineEnding::esSpikeArrow)
See Also
setHead
Definition at line 21957 of file qcustomplot.cpp.
References mTail, and tail().
QCPLineEnding tail () const inline
Definition at line 3338 of file qcustomplot.h.
Referenced by setTail().
Member Data Documentation
QCPItemPosition* const end
Definition at line 3352 of file qcustomplot.h.
Referenced by draw(), QCPItemCurve(), and selectTest().
QCPItemPosition* const endDir
Definition at line 3351 of file qcustomplot.h.
Referenced by draw(), QCPItemCurve(), and selectTest().
QCPLineEnding mHead protected
Definition at line 3357 of file qcustomplot.h.
Referenced by draw(), and setHead().
QPen mPen protected
Definition at line 3356 of file qcustomplot.h.
Referenced by mainPen(), and setPen().
QPen mSelectedPen protected
Definition at line 3356 of file qcustomplot.h.
Referenced by mainPen(), and setSelectedPen().
QCPLineEnding mTail protected
Definition at line 3357 of file qcustomplot.h.
Referenced by draw(), and setTail().
QCPItemPosition* const start
Definition at line 3349 of file qcustomplot.h.
Referenced by draw(), QCPItemCurve(), and selectTest().
QCPItemPosition* const startDir
Definition at line 3350 of file qcustomplot.h.
Referenced by draw(), QCPItemCurve(), and selectTest().
The documentation for this class was generated from the following files:
qcustomplot.h
qcustomplot.cpp