SETestKCL: QCPScatterStyle Class Reference
QCPScatterStyle Class Reference
#include <qcustomplot.h>
Public Types
enum ScatterShape {
ssNone, ssDot, ssCross, ssPlus,
ssCircle, ssDisc, ssSquare, ssDiamond,
ssStar, ssTriangle, ssTriangleInverted, ssCrossSquare,
ssPlusSquare, ssCrossCircle, ssPlusCircle, ssPeace,
ssPixmap, ssCustom
}
Public Member Functions
QCPScatterStyle ()
QCPScatterStyle (ScatterShape shape, double size=6)
QCPScatterStyle (ScatterShape shape, const QColor &color, double size)
QCPScatterStyle (ScatterShape shape, const QColor &color, const QColor &fill, double size)
QCPScatterStyle (ScatterShape shape, const QPen &pen, const QBrush &brush, double size)
QCPScatterStyle (const QPixmap &pixmap)
QCPScatterStyle (const QPainterPath &customPath, const QPen &pen, const QBrush &brush=Qt::NoBrush, double size=6)
double size () const
ScatterShape shape () const
QPen pen () const
QBrush brush () const
QPixmap pixmap () const
QPainterPath customPath () const
void setSize (double size)
void setShape (ScatterShape shape)
void setPen (const QPen &pen)
void setBrush (const QBrush &brush)
void setPixmap (const QPixmap &pixmap)
void setCustomPath (const QPainterPath &customPath)
bool isNone () const
bool isPenDefined () const
void applyTo (QCPPainter *painter, const QPen &defaultPen) const
void drawShape (QCPPainter *painter, QPointF pos) const
void drawShape (QCPPainter *painter, double x, double y) const
Protected Attributes
double mSize
ScatterShape mShape
QPen mPen
QBrush mBrush
QPixmap mPixmap
QPainterPath mCustomPath
bool mPenDefined
Detailed Description
Represents the visual appearance of scatter points.
This class holds information about shape, color and size of scatter points. In plottables like QCPGraph it is used to store how scatter points shall be drawn. For example, QCPGraph::setScatterStyle takes a QCPScatterStyle instance.
A scatter style consists of a shape (setShape), a line color (setPen) and possibly a fill (setBrush), if the shape provides a fillable area. Further, the size of the shape can be controlled with setSize.
Specifying a scatter style
You can set all these configurations either by calling the respective functions on an instance:
Or you can use one of the various constructors that take different parameter combinations, making it easy to specify a scatter style in a single call, like so:
Leaving the color/pen up to the plottable
There are two constructors which leave the pen undefined: QCPScatterStyle() and QCPScatterStyle(ScatterShape shape, double size). If those constructors are used, a call to isPenDefined will return false. It leads to scatter points that inherit the pen from the plottable that uses the scatter style. Thus, if such a scatter style is passed to QCPGraph, the line color of the graph (QCPGraph::setPen) will be used by the scatter points. This makes it very convenient to set up typical scatter settings:
Notice that it wasn't even necessary to explicitly call a QCPScatterStyle constructor. This works because QCPScatterStyle provides a constructor that can transform a ScatterShape directly into a QCPScatterStyle instance (that's the QCPScatterStyle(ScatterShape shape, double size) constructor with a default for size). In those cases, C++ allows directly supplying a ScatterShape, where actually a QCPScatterStyle is expected.
Custom shapes and pixmaps
QCPScatterStyle supports drawing custom shapes and arbitrary pixmaps as scatter points.
For custom shapes, you can provide a QPainterPath with the desired shape to the setCustomPath function or call the constructor that takes a painter path. The scatter shape will automatically be set to ssCustom.
For pixmaps, you call setPixmap with the desired QPixmap. Alternatively you can use the constructor that takes a QPixmap. The scatter shape will automatically be set to ssPixmap. Note that setSize does not influence the appearance of the pixmap.
Definition at line 234 of file qcustomplot.h.
Member Enumeration Documentation
enum ScatterShape
Defines the shape used for scatter points.
On plottables/items that draw scatters, the sizes of these visualizations (with exception of ssDot and ssPixmap) can be controlled with the setSize function. Scatters are drawn with the pen and brush specified with setPen and setBrush.
Enumerator
ssNone
no scatter symbols are drawn (e.g. in QCPGraph, data only represented with lines)
ssDot
{ssDot.png} a single pixel (use ssDisc or ssCircle if you want a round shape with a certain radius)
ssCross
{ssCross.png} a cross
ssPlus
{ssPlus.png} a plus
ssCircle
{ssCircle.png} a circle
ssDisc
{ssDisc.png} a circle which is filled with the pen's color (not the brush as with ssCircle)
ssSquare
{ssSquare.png} a square
ssDiamond
{ssDiamond.png} a diamond
ssStar
{ssStar.png} a star with eight arms, i.e. a combination of cross and plus
ssTriangle
{ssTriangle.png} an equilateral triangle, standing on baseline
ssTriangleInverted
{ssTriangleInverted.png} an equilateral triangle, standing on corner
ssCrossSquare
{ssCrossSquare.png} a square with a cross inside
ssPlusSquare
{ssPlusSquare.png} a square with a plus inside
ssCrossCircle
{ssCrossCircle.png} a circle with a cross inside
ssPlusCircle
{ssPlusCircle.png} a circle with a plus inside
ssPeace
{ssPeace.png} a circle, with one vertical and two downward diagonal lines
ssPixmap
a custom pixmap specified by setPixmap, centered on the data point coordinates
ssCustom
custom painter operations are performed per scatter (As QPainterPath, see setCustomPath)
Definition at line 246 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPScatterStyle ()
Creates a new QCPScatterStyle instance with size set to 6. No shape, pen or brush is defined.
Since the pen is undefined (isPenDefined returns false), the scatter color will be inherited from the plottable that uses this scatter style.
Definition at line 331 of file qcustomplot.cpp.
QCPScatterStyle (ScatterShape shape, double size = 6)
Creates a new QCPScatterStyle instance with shape set to shape and size to size. No pen or brush is defined.
Since the pen is undefined (isPenDefined returns false), the scatter color will be inherited from the plottable that uses this scatter style.
Definition at line 347 of file qcustomplot.cpp.
QCPScatterStyle (ScatterShape shape, const QColor & color, double size)
Creates a new QCPScatterStyle instance with shape set to shape, the pen color set to color, and size to size. No brush is defined, i.e. the scatter point will not be filled.
Definition at line 360 of file qcustomplot.cpp.
QCPScatterStyle (ScatterShape shape, const QColor & color, const QColor & fill, double size)
Creates a new QCPScatterStyle instance with shape set to shape, the pen color set to color, the brush color to fill (with a solid pattern), and size to size.
Definition at line 373 of file qcustomplot.cpp.
QCPScatterStyle (ScatterShape shape, const QPen & pen, const QBrush & brush, double size)
Creates a new QCPScatterStyle instance with shape set to shape, the pen set to pen, the brush to brush, and size to size.
Warning
In some cases it might be tempting to directly use a pen style like Qt::NoPen as pen and a color like Qt::blue as brush. Notice however, that the corresponding call
QCPScatterStyle(QCPScatterShape::ssCircle, Qt::NoPen, Qt::blue, 5)
doesn't necessarily lead C++ to use this constructor in some cases, but might mistake Qt::NoPen for a QColor and use the QCPScatterStyle(ScatterShape shape, const QColor &color, const QColor &fill, double size) constructor instead (which will lead to an unexpected look of the scatter points). To prevent this, be more explicit with the parameter types. For example, use QBrush(Qt::blue) instead of just Qt::blue, to clearly point out to the compiler that this constructor is wanted.
Definition at line 397 of file qcustomplot.cpp.
QCPScatterStyle (const QPixmap & pixmap)
Creates a new QCPScatterStyle instance which will show the specified pixmap. The scatter shape is set to ssPixmap.
Definition at line 410 of file qcustomplot.cpp.
QCPScatterStyle (const QPainterPath & customPath, const QPen & pen, const QBrush & brush = Qt::NoBrush, double size = 6)
Creates a new QCPScatterStyle instance with a custom shape that is defined via customPath. The scatter shape is set to ssCustom.
The custom shape line will be drawn with pen and filled with brush. The size has a slightly different meaning than for built-in scatter points: The custom path will be drawn scaled by a factor of size/6.0. Since the default size is 6, the custom path will appear at a its natural size by default. To double the size of the path for example, set size to 12.
Definition at line 429 of file qcustomplot.cpp.
Member Function Documentation
void applyTo (QCPPainter * painter, const QPen & defaultPen) const
Applies the pen and the brush of this scatter style to painter. If this scatter style has an undefined pen (isPenDefined), sets the pen of painter to defaultPen instead.
This function is used by plottables (or any class that wants to draw scatters) just before a number of scatters with this style shall be drawn with the painter.
See Also
drawShape
Definition at line 520 of file qcustomplot.cpp.
References mBrush, mPen, mPenDefined, and QCPPainter::setPen().
Referenced by QCPGraph::drawLegendIcon(), QCPCurve::drawLegendIcon(), QCPStatisticalBox::drawOutliers(), QCPGraph::drawScatterPlot(), and QCPCurve::drawScatterPlot().
QBrush brush () const inline
Definition at line 278 of file qcustomplot.h.
Referenced by setBrush().
QPainterPath customPath () const inline
Definition at line 280 of file qcustomplot.h.
Referenced by setCustomPath().
void drawShape (QCPPainter * painter, QPointF pos) const
Draws the scatter shape with painter at position pos.
This function does not modify the pen or the brush on the painter, as applyTo is meant to be called before scatter points are drawn with drawShape.
See Also
applyTo
Definition at line 534 of file qcustomplot.cpp.
Referenced by QCPGraph::drawLegendIcon(), QCPCurve::drawLegendIcon(), QCPStatisticalBox::drawOutliers(), QCPGraph::drawScatterPlot(), and QCPCurve::drawScatterPlot().
void drawShape (QCPPainter * painter, double x, double y) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Draws the scatter shape with painter at position x and y.
Definition at line 542 of file qcustomplot.cpp.
References QCPPainter::drawLine(), mCustomPath, mPixmap, mShape, mSize, ssCircle, ssCross, ssCrossCircle, ssCrossSquare, ssCustom, ssDiamond, ssDisc, ssDot, ssNone, ssPeace, ssPixmap, ssPlus, ssPlusCircle, ssPlusSquare, ssSquare, ssStar, ssTriangle, and ssTriangleInverted.
bool isNone () const inline
Returns whether the scatter shape is ssNone.
See Also
setShape
Definition at line 291 of file qcustomplot.h.
Referenced by QCPGraph::draw(), QCPCurve::draw(), QCPGraph::drawLegendIcon(), QCPCurve::drawLegendIcon(), QCPCurve::getCurveData(), and QCPGraph::pointDistance().
bool isPenDefined () const inline
Returns whether a pen has been defined for this scatter style.
The pen is undefined if a constructor is called that does not carry pen as parameter. Those are QCPScatterStyle() and QCPScatterStyle(ScatterShape shape, double size). If the pen is left undefined, the scatter color will be inherited from the plottable that uses this scatter style.
See Also
setPen
Definition at line 292 of file qcustomplot.h.
QPen pen () const inline
Definition at line 277 of file qcustomplot.h.
Referenced by setPen().
QPixmap pixmap () const inline
Definition at line 279 of file qcustomplot.h.
Referenced by QCPGraph::drawLegendIcon(), QCPCurve::drawLegendIcon(), and setPixmap().
void setBrush (const QBrush & brush)
Sets the brush that will be used to fill scatter points to brush. Note that not all scatter shapes have fillable areas. For example, ssPlus does not while ssCircle does.
See Also
setPen
Definition at line 482 of file qcustomplot.cpp.
References brush(), and mBrush.
void setCustomPath (const QPainterPath & customPath)
Sets the custom shape that will be drawn as scatter point to customPath.
The scatter shape is automatically set to ssCustom.
Definition at line 505 of file qcustomplot.cpp.
References customPath(), mCustomPath, setShape(), and ssCustom.
void setPen (const QPen & pen)
Sets the pen that will be used to draw scatter points to pen.
If the pen was previously undefined (see isPenDefined), the pen is considered defined after a call to this function, even if pen is Qt::NoPen.
See Also
setBrush
Definition at line 470 of file qcustomplot.cpp.
References mPen, mPenDefined, and pen().
void setPixmap (const QPixmap & pixmap)
Sets the pixmap that will be drawn as scatter point to pixmap.
Note that setSize does not influence the appearance of the pixmap.
The scatter shape is automatically set to ssPixmap.
Definition at line 494 of file qcustomplot.cpp.
References mPixmap, pixmap(), setShape(), and ssPixmap.
Referenced by QCPGraph::drawLegendIcon(), and QCPCurve::drawLegendIcon().
void setShape (QCPScatterStyle::ScatterShape shape)
Sets the shape to shape.
Note that the calls setPixmap and setCustomPath automatically set the shape to ssPixmap and ssCustom, respectively.
See Also
setSize
Definition at line 457 of file qcustomplot.cpp.
References mShape, and shape().
Referenced by setCustomPath(), and setPixmap().
void setSize (double size)
Sets the size (pixel diameter) of the drawn scatter points to size.
See Also
setShape
Definition at line 444 of file qcustomplot.cpp.
References mSize, and size().
ScatterShape shape () const inline
Definition at line 276 of file qcustomplot.h.
Referenced by QCPGraph::drawLegendIcon(), QCPCurve::drawLegendIcon(), and setShape().
double size () const inline
Definition at line 275 of file qcustomplot.h.
Referenced by QCPGraph::drawError(), QCPCurve::getCurveData(), and setSize().
Member Data Documentation
QBrush mBrush protected
Definition at line 302 of file qcustomplot.h.
Referenced by applyTo(), and setBrush().
QPainterPath mCustomPath protected
Definition at line 304 of file qcustomplot.h.
Referenced by drawShape(), and setCustomPath().
QPen mPen protected
Definition at line 301 of file qcustomplot.h.
Referenced by applyTo(), and setPen().
bool mPenDefined protected
Definition at line 307 of file qcustomplot.h.
Referenced by applyTo(), and setPen().
QPixmap mPixmap protected
Definition at line 303 of file qcustomplot.h.
Referenced by drawShape(), and setPixmap().
ScatterShape mShape protected
Definition at line 300 of file qcustomplot.h.
Referenced by drawShape(), and setShape().
double mSize protected
Definition at line 299 of file qcustomplot.h.
Referenced by drawShape(), and setSize().
The documentation for this class was generated from the following files:
qcustomplot.h
qcustomplot.cpp