SETestKCL: QCPColorMapData Class Reference
QCPColorMapData Class Reference
#include <qcustomplot.h>
Public Member Functions
QCPColorMapData (int keySize, int valueSize, const QCPRange &keyRange, const QCPRange &valueRange)
~QCPColorMapData ()
QCPColorMapData (const QCPColorMapData &other)
QCPColorMapData & operator= (const QCPColorMapData &other)
int keySize () const
int valueSize () const
QCPRange keyRange () const
QCPRange valueRange () const
QCPRange dataBounds () const
double data (double key, double value)
double cell (int keyIndex, int valueIndex)
void setSize (int keySize, int valueSize)
void setKeySize (int keySize)
void setValueSize (int valueSize)
void setRange (const QCPRange &keyRange, const QCPRange &valueRange)
void setKeyRange (const QCPRange &keyRange)
void setValueRange (const QCPRange &valueRange)
void setData (double key, double value, double z)
void setCell (int keyIndex, int valueIndex, double z)
void recalculateDataBounds ()
void clear ()
void fill (double z)
bool isEmpty () const
void coordToCell (double key, double value, int *keyIndex, int *valueIndex) const
void cellToCoord (int keyIndex, int valueIndex, double *key, double *value) const
Protected Attributes
int mKeySize
int mValueSize
QCPRange mKeyRange
QCPRange mValueRange
bool mIsEmpty
double * mData
QCPRange mDataBounds
bool mDataModified
Friends
class QCPColorMap
Detailed Description
Holds the two-dimensional data of a QCPColorMap plottable.
This class is a data storage for QCPColorMap. It holds a two-dimensional array, which QCPColorMap then displays as a 2D image in the plot, where the array values are represented by a color, depending on the value.
The size of the array can be controlled via setSize (or setKeySize, setValueSize). Which plot coordinates these cells correspond to can be configured with setRange (or setKeyRange, setValueRange).
The data cells can be accessed in two ways: They can be directly addressed by an integer index with setCell. This is the fastest method. Alternatively, they can be addressed by their plot coordinate with setData. plot coordinate to cell index transformations and vice versa are provided by the functions coordToCell and cellToCoord.
This class also buffers the minimum and maximum values that are in the data set, to provide QCPColorMap::rescaleDataRange with the necessary information quickly. Setting a cell to a value that is greater than the current maximum increases this maximum to the new value. However, setting the cell that currently holds the maximum value to a smaller value doesn't decrease the maximum again, because finding the true new maximum would require going through the entire data array, which might be time consuming. The same holds for the data minimum. This functionality is given by recalculateDataBounds, such that you can decide when it is sensible to find the true current minimum and maximum. The method QCPColorMap::rescaleDataRange offers a convenience parameter recalculateDataBounds which may be set to true to automatically call recalculateDataBounds internally.
Definition at line 2997 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPColorMapData (int keySize, int valueSize, const QCPRange & keyRange, const QCPRange & valueRange)
Constructs a new QCPColorMapData instance. The instance has keySize cells in the key direction and valueSize cells in the value direction. These cells will be displayed by the QCPColorMap at the coordinates keyRange and valueRange.
See Also
setSize, setKeySize, setValueSize, setRange, setKeyRange, setValueRange
Definition at line 19633 of file qcustomplot.cpp.
References fill(), and setSize().
~QCPColorMapData ()
Definition at line 19646 of file qcustomplot.cpp.
References mData.
QCPColorMapData (const QCPColorMapData & other)
Constructs a new QCPColorMapData instance copying the data and range of other.
Definition at line 19655 of file qcustomplot.cpp.
Member Function Documentation
double cell (int keyIndex, int valueIndex)
Definition at line 19696 of file qcustomplot.cpp.
References mData, mKeySize, and mValueSize.
void cellToCoord (int keyIndex, int valueIndex, double * key, double * value) const
Transforms cell indices given by keyIndex and valueIndex to cell indices of this QCPColorMapData instance. The resulting coordinates are returned via the output parameters key and value.
If you are only interested in a key or value coordinate, you may pass 0 as key or value.
Note
The QCPColorMap always displays the data at equal key/value intervals, even if the key or value axis is set to a logarithmic scaling. If you want to use QCPColorMap with logarithmic axes, you shouldn't use the QCPColorMapData::cellToCoord method as it uses a linear transformation to determine the cell index.
See Also
coordToCell, QCPAxis::pixelToCoord
Definition at line 19965 of file qcustomplot.cpp.
References QCPRange::lower, mKeyRange, mKeySize, mValueRange, mValueSize, and QCPRange::upper.
void clear ()
Frees the internal data memory.
This is equivalent to calling setSize(0, 0).
Definition at line 19908 of file qcustomplot.cpp.
References setSize().
Referenced by QCPColorMap::clearData().
void coordToCell (double key, double value, int * keyIndex, int * valueIndex) const
Transforms plot coordinates given by key and value to cell indices of this QCPColorMapData instance. The resulting cell indices are returned via the output parameters keyIndex and valueIndex.
The retrieved key/value cell indices can then be used for example with setCell.
If you are only interested in a key or value index, you may pass 0 as valueIndex or keyIndex.
Note
The QCPColorMap always displays the data at equal key/value intervals, even if the key or value axis is set to a logarithmic scaling. If you want to use QCPColorMap with logarithmic axes, you shouldn't use the QCPColorMapData::coordToCell method as it uses a linear transformation to determine the cell index.
See Also
cellToCoord, QCPAxis::coordToPixel
Definition at line 19942 of file qcustomplot.cpp.
References QCPRange::lower, mKeyRange, mKeySize, mValueRange, mValueSize, and QCPRange::upper.
double data (double key, double value)
Definition at line 19685 of file qcustomplot.cpp.
References QCPRange::lower, mData, mKeyRange, mKeySize, mValueRange, mValueSize, and QCPRange::upper.
QCPRange dataBounds () const inline
Definition at line 3010 of file qcustomplot.h.
Referenced by QCPColorMap::rescaleDataRange().
void fill (double z)
Sets all cells to the value z.
Definition at line 19916 of file qcustomplot.cpp.
References mData, mDataBounds, mDataModified, mKeySize, and mValueSize.
Referenced by QCPColorMapData(), and setSize().
bool isEmpty () const inline
Returns whether this instance carries no data. This is equivalent to having a size where at least one of the dimensions is 0 (see setSize).
Definition at line 3028 of file qcustomplot.h.
Referenced by QCPColorMap::draw(), QCPColorMap::updateLegendIcon(), and QCPColorMap::updateMapImage().
QCPRange keyRange () const inline
Definition at line 3008 of file qcustomplot.h.
Referenced by QCPColorMap::draw(), QCPColorMap::getKeyRange(), operator=(), QCPColorMap::selectTest(), and setKeyRange().
int keySize () const inline
Definition at line 3006 of file qcustomplot.h.
Referenced by QCPColorMap::draw(), operator=(), setSize(), and QCPColorMap::updateMapImage().
QCPColorMapData & operator= (const QCPColorMapData & other)
Overwrites this color map data instance with the data stored in other.
Definition at line 19668 of file qcustomplot.cpp.
References keyRange(), keySize(), mData, mDataBounds, mDataModified, mIsEmpty, setRange(), setSize(), valueRange(), and valueSize().
void recalculateDataBounds ()
Goes through the data and updates the buffered minimum and maximum data values.
Calling this method is only advised if you are about to call QCPColorMap::rescaleDataRange and can not guarantee that the cells holding the maximum or minimum data haven't been overwritten with a smaller or larger value respectively, since the buffered maximum/minimum values have been updated the last time. Why this is the case is explained in the class description (QCPColorMapData).
Note that the method QCPColorMap::rescaleDataRange provides a parameter recalculateDataBounds for convenience. Setting this to true will call this method for you, before doing the rescale.
Definition at line 19884 of file qcustomplot.cpp.
References QCPRange::lower, mData, mDataBounds, mKeySize, mValueSize, and QCPRange::upper.
Referenced by QCPColorMap::rescaleDataRange().
void setCell (int keyIndex, int valueIndex, double z)
Sets the data of the cell with indices keyIndex and valueIndex to z. The indices enumerate the cells starting from zero, up to the map's size-1 in the respective dimension (see setSize).
In the standard plot configuration (horizontal key axis and vertical value axis, both not range-reversed), the cell with indices (0, 0) is in the bottom left corner and the cell with indices (keySize-1, valueSize-1) is in the top right corner of the color map.
See Also
setData, setSize
Definition at line 19858 of file qcustomplot.cpp.
References QCPRange::lower, mData, mDataBounds, mDataModified, mKeySize, mValueSize, and QCPRange::upper.
void setData (double key, double value, double z)
Sets the data of the cell, which lies at the plot coordinates given by key and value, to z.
Note
The QCPColorMap always displays the data at equal key/value intervals, even if the key or value axis is set to a logarithmic scaling. If you want to use QCPColorMap with logarithmic axes, you shouldn't use the QCPColorMapData::setData method as it uses a linear transformation to determine the cell index. Rather directly access the cell index with QCPColorMapData::setCell.
See Also
setCell, setRange
Definition at line 19832 of file qcustomplot.cpp.
References QCPRange::lower, mData, mDataBounds, mDataModified, mKeyRange, mKeySize, mValueRange, mValueSize, and QCPRange::upper.
void setKeyRange (const QCPRange & keyRange)
Sets the coordinate range the data shall be distributed over in the key dimension. Together with the value range, This defines the rectangular area covered by the color map in plot coordinates.
The outer cells will be centered on the range boundaries given to this function. For example, if the key size (setKeySize) is 3 and keyRange is set to QCPRange(2, 3) there will be cells centered on the key coordinates 2, 2.5 and 3.
See Also
setRange, setValueRange, setSize
Definition at line 19800 of file qcustomplot.cpp.
References keyRange(), and mKeyRange.
Referenced by setRange().
void setKeySize (int keySize)
Resizes the data array to have keySize cells in the key dimension.
The current data is discarded and the map cells are set to 0, unless the map had already the requested size.
Setting keySize to zero frees the internal data array and isEmpty returns true.
See Also
setKeyRange, setSize, setValueSize
Definition at line 19754 of file qcustomplot.cpp.
References mValueSize, and setSize().
void setRange (const QCPRange & keyRange, const QCPRange & valueRange)
Sets the coordinate ranges the data shall be distributed over. This defines the rectangular area covered by the color map in plot coordinates.
The outer cells will be centered on the range boundaries given to this function. For example, if the key size (setKeySize) is 3 and keyRange is set to QCPRange(2, 3) there will be cells centered on the key coordinates 2, 2.5 and 3.
See Also
setSize
Definition at line 19784 of file qcustomplot.cpp.
References setKeyRange(), and setValueRange().
Referenced by operator=().
void setSize (int keySize, int valueSize)
Resizes the data array to have keySize cells in the key dimension and valueSize cells in the value dimension.
The current data is discarded and the map cells are set to 0, unless the map had already the requested size.
Setting at least one of keySize or valueSize to zero frees the internal data array and isEmpty returns true.
See Also
setRange, setKeySize, setValueSize
Definition at line 19716 of file qcustomplot.cpp.
References fill(), keySize(), mData, mDataModified, mIsEmpty, mKeySize, mValueSize, and valueSize().
Referenced by clear(), operator=(), QCPColorMapData(), setKeySize(), and setValueSize().
void setValueRange (const QCPRange & valueRange)
Sets the coordinate range the data shall be distributed over in the value dimension. Together with the key range, This defines the rectangular area covered by the color map in plot coordinates.
The outer cells will be centered on the range boundaries given to this function. For example, if the value size (setValueSize) is 3 and valueRange is set to QCPRange(2, 3) there will be cells centered on the value coordinates 2, 2.5 and 3.
See Also
setRange, setKeyRange, setSize
Definition at line 19815 of file qcustomplot.cpp.
References mValueRange, and valueRange().
Referenced by setRange().
void setValueSize (int valueSize)
Resizes the data array to have valueSize cells in the value dimension.
The current data is discarded and the map cells are set to 0, unless the map had already the requested size.
Setting valueSize to zero frees the internal data array and isEmpty returns true.
See Also
setValueRange, setSize, setKeySize
Definition at line 19769 of file qcustomplot.cpp.
References mKeySize, and setSize().
QCPRange valueRange () const inline
Definition at line 3009 of file qcustomplot.h.
Referenced by QCPColorMap::draw(), QCPColorMap::getValueRange(), operator=(), QCPColorMap::selectTest(), and setValueRange().
int valueSize () const inline
Definition at line 3007 of file qcustomplot.h.
Referenced by QCPColorMap::draw(), operator=(), setSize(), and QCPColorMap::updateMapImage().
Friends And Related Function Documentation
friend class QCPColorMap friend
Definition at line 3042 of file qcustomplot.h.
Member Data Documentation
double* mData protected
Definition at line 3038 of file qcustomplot.h.
Referenced by cell(), data(), fill(), operator=(), recalculateDataBounds(), setCell(), setData(), setSize(), QCPColorMap::updateMapImage(), and ~QCPColorMapData().
QCPRange mDataBounds protected
Definition at line 3039 of file qcustomplot.h.
Referenced by fill(), operator=(), recalculateDataBounds(), setCell(), and setData().
bool mDataModified protected
Definition at line 3040 of file qcustomplot.h.
Referenced by QCPColorMap::draw(), fill(), operator=(), setCell(), setData(), setSize(), and QCPColorMap::updateMapImage().
bool mIsEmpty protected
Definition at line 3036 of file qcustomplot.h.
Referenced by operator=(), and setSize().
QCPRange mKeyRange protected
Definition at line 3035 of file qcustomplot.h.
Referenced by cellToCoord(), coordToCell(), data(), setData(), and setKeyRange().
int mKeySize protected
Definition at line 3034 of file qcustomplot.h.
Referenced by cell(), cellToCoord(), coordToCell(), data(), fill(), recalculateDataBounds(), setCell(), setData(), setSize(), and setValueSize().
QCPRange mValueRange protected
Definition at line 3035 of file qcustomplot.h.
Referenced by cellToCoord(), coordToCell(), data(), setData(), and setValueRange().
int mValueSize protected
Definition at line 3034 of file qcustomplot.h.
Referenced by cell(), cellToCoord(), coordToCell(), data(), fill(), recalculateDataBounds(), setCell(), setData(), setKeySize(), and setSize().
The documentation for this class was generated from the following files:
qcustomplot.h
qcustomplot.cpp