SETestKCL: QCPBarsGroup Class Reference
QCPBarsGroup Class Reference
#include <qcustomplot.h>
Public Types
enum SpacingType { stAbsolute, stAxisRectRatio, stPlotCoords }
Public Member Functions
QCPBarsGroup (QCustomPlot *parentPlot)
~QCPBarsGroup ()
SpacingType spacingType () const
double spacing () const
void setSpacingType (SpacingType spacingType)
void setSpacing (double spacing)
QList< QCPBars * > bars () const
QCPBars * bars (int index) const
int size () const
bool isEmpty () const
void clear ()
bool contains (QCPBars *bars) const
void append (QCPBars *bars)
void insert (int i, QCPBars *bars)
void remove (QCPBars *bars)
Protected Member Functions
void registerBars (QCPBars *bars)
void unregisterBars (QCPBars *bars)
double keyPixelOffset (const QCPBars *bars, double keyCoord)
double getPixelSpacing (const QCPBars *bars, double keyCoord)
Protected Attributes
QCustomPlot * mParentPlot
SpacingType mSpacingType
double mSpacing
QList< QCPBars * > mBars
Friends
class QCPBars
Detailed Description
Groups multiple QCPBars together so they appear side by side.
When showing multiple QCPBars in one plot which have bars at identical keys, it may be desirable to have them appearing next to each other at each key. This is what adding the respective QCPBars plottables to a QCPBarsGroup achieves. (An alternative approach is to stack them on top of each other, see QCPBars::moveAbove.)
Usage
To add a QCPBars plottable to the group, create a new group and then add the respective bars intances:
Alternatively to appending to the group like shown above, you can also set the group on the QCPBars plottable via QCPBars::setBarsGroup.
The spacing between the bars can be configured via setSpacingType and setSpacing. The bars in this group appear in the plot in the order they were appended. To insert a bars plottable at a certain index position, or to reposition a bars plottable which is already in the group, use insert.
To remove specific bars from the group, use either remove or call QCPBars::setBarsGroup(0) on the respective bars plottable.
To clear the entire group, call clear, or simply delete the group.
Example
The image above is generated with the following code:
Definition at line 2740 of file qcustomplot.h.
Member Enumeration Documentation
enum SpacingType
Defines the ways the spacing between bars in the group can be specified. Thus it defines what the number passed to setSpacing actually means.
See Also
setSpacingType, setSpacing
Enumerator
stAbsolute
Bar spacing is in absolute pixels.
stAxisRectRatio
Bar spacing is given by a fraction of the axis rect size.
stPlotCoords
Bar spacing is in key coordinates and thus scales with the key axis range.
Definition at line 2754 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPBarsGroup (QCustomPlot * parentPlot)
Constructs a new bars group for the specified QCustomPlot instance.
Definition at line 18086 of file qcustomplot.cpp.
~QCPBarsGroup ()
Definition at line 18094 of file qcustomplot.cpp.
References clear().
Member Function Documentation
void append (QCPBars * bars)
Adds the specified bars plottable to this group. Alternatively, you can also use QCPBars::setBarsGroup on the bars instance.
See Also
insert, remove
Definition at line 18157 of file qcustomplot.cpp.
References bars(), mBars, and QCPBars::setBarsGroup().
QList< QCPBars * > bars () const inline
Returns all bars currently in this group.
See Also
bars(int index)
Definition at line 2770 of file qcustomplot.h.
Referenced by append(), clear(), keyPixelOffset(), and remove().
QCPBars * bars (int index) const
Returns the QCPBars instance with the specified index in this group. If no such QCPBars exists, returns 0.
See Also
bars(), size
Definition at line 18128 of file qcustomplot.cpp.
References mBars.
void clear ()
Removes all QCPBars plottables from this group.
See Also
isEmpty
Definition at line 18145 of file qcustomplot.cpp.
References bars(), mBars, and QCPBars::setBarsGroup().
Referenced by ~QCPBarsGroup().
bool contains (QCPBars * bars) const inline
Returns whether the specified bars plottable is part of this group.
Definition at line 2775 of file qcustomplot.h.
double getPixelSpacing (const QCPBars * bars, double keyCoord) protected
Definition at line 18330 of file qcustomplot.cpp.
References QCPAxis::axisRect(), QCPAxis::coordToPixel(), QCPAxisRect::height(), QCPAbstractPlottable::keyAxis(), mSpacing, mSpacingType, QCPAxis::orientation(), stAbsolute, stAxisRectRatio, stPlotCoords, and QCPAxisRect::width().
Referenced by keyPixelOffset().
void insert (int i, QCPBars * bars)
Inserts the specified bars plottable into this group at the specified index position i. This gives you full control over the ordering of the bars.
bars may already be part of this group. In that case, bars is just moved to the new index position.
See Also
append, remove
Definition at line 18180 of file qcustomplot.cpp.
References mBars, and QCPBars::setBarsGroup().
bool isEmpty () const inline
Returns whether this bars group is empty.
See Also
size
Definition at line 2773 of file qcustomplot.h.
double keyPixelOffset (const QCPBars * bars, double keyCoord) protected
Definition at line 18245 of file qcustomplot.cpp.
References QCPBars::barBelow(), bars(), getPixelSpacing(), and mBars.
Referenced by QCPBars::getBarPolygon(), and QCPBars::getKeyRange().
void registerBars (QCPBars * bars) protected
Definition at line 18221 of file qcustomplot.cpp.
References mBars.
Referenced by QCPBars::setBarsGroup().
void remove (QCPBars * bars)
Removes the specified bars plottable from this group.
See Also
contains, clear
Definition at line 18200 of file qcustomplot.cpp.
References bars(), mBars, and QCPBars::setBarsGroup().
void setSpacing (double spacing)
Sets the spacing between adjacent bars. What the number passed as spacing actually means, is defined by the current SpacingType, which can be set with setSpacingType.
See Also
setSpacingType
Definition at line 18117 of file qcustomplot.cpp.
References mSpacing, and spacing().
void setSpacingType (SpacingType spacingType)
Sets how the spacing between adjacent bars is interpreted. See SpacingType.
The actual spacing can then be specified with setSpacing.
See Also
setSpacing
Definition at line 18106 of file qcustomplot.cpp.
References mSpacingType, and spacingType().
int size () const inline
Returns the number of QCPBars plottables that are part of this group.
Definition at line 2772 of file qcustomplot.h.
double spacing () const inline
Definition at line 2763 of file qcustomplot.h.
Referenced by setSpacing().
SpacingType spacingType () const inline
Definition at line 2762 of file qcustomplot.h.
Referenced by setSpacingType().
void unregisterBars (QCPBars * bars) protected
Definition at line 18234 of file qcustomplot.cpp.
References mBars.
Referenced by QCPBars::setBarsGroup().
Friends And Related Function Documentation
friend class QCPBars friend
Definition at line 2798 of file qcustomplot.h.
Member Data Documentation
QList<QCPBars*> mBars protected
Definition at line 2785 of file qcustomplot.h.
Referenced by append(), bars(), clear(), insert(), keyPixelOffset(), registerBars(), remove(), and unregisterBars().
QCustomPlot* mParentPlot protected
Definition at line 2782 of file qcustomplot.h.
double mSpacing protected
Definition at line 2784 of file qcustomplot.h.
Referenced by getPixelSpacing(), and setSpacing().
SpacingType mSpacingType protected
Definition at line 2783 of file qcustomplot.h.
Referenced by getPixelSpacing(), and setSpacingType().
The documentation for this class was generated from the following files:
qcustomplot.h
qcustomplot.cpp