SETestKCL: QCPItemTracer Class Reference
QCPItemTracer Class Reference
#include <qcustomplot.h>
Public Types
enum TracerStyle {
tsNone, tsPlus, tsCrosshair, tsCircle,
tsSquare
}
Public Member Functions
QCPItemTracer (QCustomPlot *parentPlot)
virtual ~QCPItemTracer ()
QPen pen () const
QPen selectedPen () const
QBrush brush () const
QBrush selectedBrush () const
double size () const
TracerStyle style () const
QCPGraph * graph () const
double graphKey () const
bool interpolating () const
void setPen (const QPen &pen)
void setSelectedPen (const QPen &pen)
void setBrush (const QBrush &brush)
void setSelectedBrush (const QBrush &brush)
void setSize (double size)
void setStyle (TracerStyle style)
void setGraph (QCPGraph *graph)
void setGraphKey (double key)
void setInterpolating (bool enabled)
virtual double selectTest (const QPointF &pos, bool onlySelectable, QVariant *details=0) const
void updatePosition ()
Public Member Functions inherited from QCPAbstractItem
QCPAbstractItem (QCustomPlot *parentPlot)
virtual ~QCPAbstractItem ()
bool clipToAxisRect () const
QCPAxisRect * clipAxisRect () const
bool selectable () const
bool selected () const
void setClipToAxisRect (bool clip)
void setClipAxisRect (QCPAxisRect *rect)
Q_SLOT void setSelectable (bool selectable)
Q_SLOT void setSelected (bool selected)
QList< QCPItemPosition * > positions () const
QList< QCPItemAnchor * > anchors () const
QCPItemPosition * position (const QString &name) const
QCPItemAnchor * anchor (const QString &name) const
bool hasAnchor (const QString &name) const
Public Member Functions inherited from QCPLayerable
QCPLayerable (QCustomPlot *plot, QString targetLayer=QString(), QCPLayerable *parentLayerable=0)
~QCPLayerable ()
bool visible () const
QCustomPlot * parentPlot () const
QCPLayerable * parentLayerable () const
QCPLayer * layer () const
bool antialiased () const
void setVisible (bool on)
Q_SLOT bool setLayer (QCPLayer *layer)
bool setLayer (const QString &layerName)
void setAntialiased (bool enabled)
bool realVisibility () const
Public Attributes
QCPItemPosition *const position
Protected Member Functions
virtual void draw (QCPPainter *painter)
QPen mainPen () const
QBrush mainBrush () const
Protected Member Functions inherited from QCPAbstractItem
virtual QCP::Interaction selectionCategory () const
virtual QRect clipRect () const
virtual void applyDefaultAntialiasingHint (QCPPainter *painter) const
virtual void selectEvent (QMouseEvent *event, bool additive, const QVariant &details, bool *selectionStateChanged)
virtual void deselectEvent (bool *selectionStateChanged)
virtual QPointF anchorPixelPoint (int anchorId) const
double distSqrToLine (const QPointF &start, const QPointF &end, const QPointF &point) const
double rectSelectTest (const QRectF &rect, const QPointF &pos, bool filledRect) const
QCPItemPosition * createPosition (const QString &name)
QCPItemAnchor * createAnchor (const QString &name, int anchorId)
Protected Member Functions inherited from QCPLayerable
virtual void parentPlotInitialized (QCustomPlot *parentPlot)
void initializeParentPlot (QCustomPlot *parentPlot)
void setParentLayerable (QCPLayerable *parentLayerable)
bool moveToLayer (QCPLayer *layer, bool prepend)
void applyAntialiasingHint (QCPPainter *painter, bool localAntialiased, QCP::AntialiasedElement overrideElement) const
Protected Attributes
QPen mPen
QPen mSelectedPen
QBrush mBrush
QBrush mSelectedBrush
double mSize
TracerStyle mStyle
QCPGraph * mGraph
double mGraphKey
bool mInterpolating
Protected Attributes inherited from QCPAbstractItem
bool mClipToAxisRect
QPointer< QCPAxisRect > mClipAxisRect
QList< QCPItemPosition * > mPositions
QList< QCPItemAnchor * > mAnchors
bool mSelectable
bool mSelected
Protected Attributes inherited from QCPLayerable
bool mVisible
QCustomPlot * mParentPlot
QPointer< QCPLayerable > mParentLayerable
QCPLayer * mLayer
bool mAntialiased
Additional Inherited Members
Signals inherited from QCPAbstractItem
void selectionChanged (bool selected)
void selectableChanged (bool selectable)
Signals inherited from QCPLayerable
void layerChanged (QCPLayer *newLayer)
Detailed Description
Item that sticks to QCPGraph data points.
Tracer example. Blue dotted circles are anchors, solid blue discs are positions.
The tracer can be connected with a QCPGraph via setGraph. Then it will automatically adopt the coordinate axes of the graph and update its position to be on the graph's data. This means the key stays controllable via setGraphKey, but the value will follow the graph data. If a QCPGraph is connected, note that setting the coordinates of the tracer item directly via position will have no effect because they will be overriden in the next redraw (this is when the coordinate update happens).
If the specified key in setGraphKey is outside the key bounds of the graph, the tracer will stay at the corresponding end of the graph.
With setInterpolating you may specify whether the tracer may only stay exactly on data points or whether it interpolates data points linearly, if given a key that lies between two data points of the graph.
The tracer has different visual styles, see setStyle. It is also possible to make the tracer have no own visual appearance (set the style to tsNone), and just connect other item positions to the tracer position (used as an anchor) via QCPItemPosition::setParentAnchor.
Note
The tracer position is only automatically updated upon redraws. So when the data of the graph changes and immediately afterwards (without a redraw) the a position coordinates of the tracer are retrieved, they will not reflect the updated data of the graph. In this case updatePosition must be called manually, prior to reading the tracer coordinates.
Definition at line 3634 of file qcustomplot.h.
Member Enumeration Documentation
enum TracerStyle
The different visual appearances a tracer item can have. Some styles size may be controlled with setSize.
See Also
setStyle
Enumerator
tsNone
The tracer is not visible.
tsPlus
A plus shaped crosshair with limited size.
tsCrosshair
A plus shaped crosshair which spans the complete axis rect.
tsCircle
A circle.
tsSquare
A square.
Definition at line 3654 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPItemTracer (QCustomPlot * parentPlot)
Creates a tracer item and sets default values.
The constructed item can be added to the plot with QCustomPlot::addItem.
Definition at line 22994 of file qcustomplot.cpp.
References position, setBrush(), QCPItemPosition::setCoords(), setGraphKey(), setInterpolating(), setPen(), setSelectedBrush(), setSelectedPen(), setSize(), setStyle(), and tsCrosshair.
~QCPItemTracer () virtual
Definition at line 23011 of file qcustomplot.cpp.
Member Function Documentation
QBrush brush () const inline
Definition at line 3668 of file qcustomplot.h.
Referenced by setBrush(), and setSelectedBrush().
void draw (QCPPainter * painter) protected virtual
Implements QCPAbstractItem.
Definition at line 23191 of file qcustomplot.cpp.
References QCPAbstractItem::clipRect(), QCPPainter::drawLine(), mainBrush(), mainPen(), mSize, mStyle, QCPItemPosition::pixelPoint(), position, QCPPainter::setPen(), tsCircle, tsCrosshair, tsNone, tsPlus, tsSquare, and updatePosition().
QCPGraph* graph () const inline
Definition at line 3672 of file qcustomplot.h.
Referenced by setGraph().
double graphKey () const inline
Definition at line 3673 of file qcustomplot.h.
bool interpolating () const inline
Definition at line 3674 of file qcustomplot.h.
QBrush mainBrush () const protected
Definition at line 23312 of file qcustomplot.cpp.
References mBrush, QCPAbstractItem::mSelected, and mSelectedBrush.
Referenced by draw().
QPen mainPen () const protected
Definition at line 23302 of file qcustomplot.cpp.
References mPen, QCPAbstractItem::mSelected, and mSelectedPen.
Referenced by draw().
QPen pen () const inline
Definition at line 3666 of file qcustomplot.h.
Referenced by setPen(), and setSelectedPen().
QBrush selectedBrush () const inline
Definition at line 3669 of file qcustomplot.h.
QPen selectedPen () const inline
Definition at line 3667 of file qcustomplot.h.
double selectTest (const QPointF & pos, bool onlySelectable, QVariant * details = 0) const virtual
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
You may pass 0 as details to indicate that you are not interested in those selection details.
See Also
selectEvent, deselectEvent, QCustomPlot::setInteractions
Implements QCPAbstractItem.
Definition at line 23134 of file qcustomplot.cpp.
References QCPAbstractItem::clipRect(), QCPAbstractItem::distSqrToLine(), mBrush, QCPLayerable::mParentPlot, QCPAbstractItem::mSelectable, mSize, mStyle, QCPItemPosition::pixelPoint(), position, QCPAbstractItem::rectSelectTest(), QCustomPlot::selectionTolerance(), tsCircle, tsCrosshair, tsNone, tsPlus, and tsSquare.
void setBrush (const QBrush & brush)
Sets the brush that will be used to draw any fills of the tracer
See Also
setSelectedBrush, setPen
Definition at line 23040 of file qcustomplot.cpp.
References brush(), and mBrush.
Referenced by QCPItemTracer().
void setGraph (QCPGraph * graph)
Sets the QCPGraph this tracer sticks to. The tracer position will be set to type QCPItemPosition::ptPlotCoords and the axes will be set to the axes of graph.
To free the tracer from any graph, set graph to 0. The tracer position can then be placed freely like any other item position. This is the state the tracer will assume when its graph gets deleted while still attached to it.
See Also
setGraphKey
Definition at line 23085 of file qcustomplot.cpp.
References graph(), QCPAbstractPlottable::keyAxis(), mGraph, QCPLayerable::mParentPlot, QCPLayerable::parentPlot(), position, QCPItemPosition::ptPlotCoords, QCPItemPosition::setAxes(), QCPItemPosition::setType(), updatePosition(), and QCPAbstractPlottable::valueAxis().
void setGraphKey (double key)
Sets the key of the graph's data point the tracer will be positioned at. This is the only free coordinate of a tracer when attached to a graph.
Depending on setInterpolating, the tracer will be either positioned on the data point closest to key, or will stay exactly at key and interpolate the value linearly.
See Also
setGraph, setInterpolating
Definition at line 23112 of file qcustomplot.cpp.
References mGraphKey.
Referenced by QCPItemTracer().
void setInterpolating (bool enabled)
Sets whether the value of the graph's data points shall be interpolated, when positioning the tracer.
If enabled is set to false and a key is given with setGraphKey, the tracer is placed on the data point of the graph which is closest to the key, but which is not necessarily exactly there. If enabled is true, the tracer will be positioned exactly at the specified key, and the appropriate value will be interpolated from the graph's data points linearly.
See Also
setGraph, setGraphKey
Definition at line 23128 of file qcustomplot.cpp.
References mInterpolating.
Referenced by QCPItemTracer().
void setPen (const QPen & pen)
Sets the pen that will be used to draw the line of the tracer
See Also
setSelectedPen, setBrush
Definition at line 23020 of file qcustomplot.cpp.
References mPen, and pen().
Referenced by QCPItemTracer().
void setSelectedBrush (const QBrush & brush)
Sets the brush that will be used to draw any fills of the tracer, when selected.
See Also
setBrush, setSelected
Definition at line 23050 of file qcustomplot.cpp.
References brush(), and mSelectedBrush.
Referenced by QCPItemTracer().
void setSelectedPen (const QPen & pen)
Sets the pen that will be used to draw the line of the tracer when selected
See Also
setPen, setSelected
Definition at line 23030 of file qcustomplot.cpp.
References mSelectedPen, and pen().
Referenced by QCPItemTracer().
void setSize (double size)
Sets the size of the tracer in pixels, if the style supports setting a size (e.g. tsSquare does, tsCrosshair does not).
Definition at line 23059 of file qcustomplot.cpp.
References mSize, and size().
Referenced by QCPItemTracer().
void setStyle (QCPItemTracer::TracerStyle style)
Sets the style/visual appearance of the tracer.
If you only want to use the tracer position as an anchor for other items, set style to tsNone.
Definition at line 23070 of file qcustomplot.cpp.
References mStyle, and style().
Referenced by QCPItemTracer().
double size () const inline
Definition at line 3670 of file qcustomplot.h.
Referenced by setSize().
TracerStyle style () const inline
Definition at line 3671 of file qcustomplot.h.
Referenced by setStyle().
void updatePosition ()
If the tracer is connected with a graph (setGraph), this function updates the tracer's position to reside on the graph data, depending on the configured key (setGraphKey).
It is called automatically on every redraw and normally doesn't need to be called manually. One exception is when you want to read the tracer coordinates via position and are not sure that the graph's data (or the tracer key with setGraphKey) hasn't changed since the last redraw. In that situation, call this function before accessing position, to make sure you don't get out-of-date coordinates.
If there is no graph set on this tracer, this function does nothing.
Definition at line 23249 of file qcustomplot.cpp.
References QCPGraph::data(), QCustomPlot::hasPlottable(), mGraph, mGraphKey, mInterpolating, QCPLayerable::mParentPlot, position, and QCPItemPosition::setCoords().
Referenced by draw(), and setGraph().
Member Data Documentation
QBrush mBrush protected
Definition at line 3698 of file qcustomplot.h.
Referenced by mainBrush(), selectTest(), and setBrush().
QCPGraph* mGraph protected
Definition at line 3701 of file qcustomplot.h.
Referenced by setGraph(), and updatePosition().
double mGraphKey protected
Definition at line 3702 of file qcustomplot.h.
Referenced by setGraphKey(), and updatePosition().
bool mInterpolating protected
Definition at line 3703 of file qcustomplot.h.
Referenced by setInterpolating(), and updatePosition().
QPen mPen protected
Definition at line 3697 of file qcustomplot.h.
Referenced by mainPen(), and setPen().
QBrush mSelectedBrush protected
Definition at line 3698 of file qcustomplot.h.
Referenced by mainBrush(), and setSelectedBrush().
QPen mSelectedPen protected
Definition at line 3697 of file qcustomplot.h.
Referenced by mainPen(), and setSelectedPen().
double mSize protected
Definition at line 3699 of file qcustomplot.h.
Referenced by draw(), selectTest(), and setSize().
TracerStyle mStyle protected
Definition at line 3700 of file qcustomplot.h.
Referenced by draw(), selectTest(), and setStyle().
QCPItemPosition* const position
Definition at line 3693 of file qcustomplot.h.
Referenced by draw(), QCPItemTracer(), selectTest(), setGraph(), and updatePosition().
The documentation for this class was generated from the following files:
qcustomplot.h
qcustomplot.cpp