SETestKCL: QCPLayoutElement Class Reference
QCPLayoutElement Class Reference
#include <qcustomplot.h>
Public Types
enum UpdatePhase { upPreparation, upMargins, upLayout }
Public Member Functions
QCPLayoutElement (QCustomPlot *parentPlot=0)
virtual ~QCPLayoutElement ()
QCPLayout * layout () const
QRect rect () const
QRect outerRect () const
QMargins margins () const
QMargins minimumMargins () const
QCP::MarginSides autoMargins () const
QSize minimumSize () const
QSize maximumSize () const
QCPMarginGroup * marginGroup (QCP::MarginSide side) const
QHash< QCP::MarginSide,
QCPMarginGroup * > marginGroups () const
void setOuterRect (const QRect &rect)
void setMargins (const QMargins &margins)
void setMinimumMargins (const QMargins &margins)
void setAutoMargins (QCP::MarginSides sides)
void setMinimumSize (const QSize &size)
void setMinimumSize (int width, int height)
void setMaximumSize (const QSize &size)
void setMaximumSize (int width, int height)
void setMarginGroup (QCP::MarginSides sides, QCPMarginGroup *group)
virtual void update (UpdatePhase phase)
virtual QSize minimumSizeHint () const
virtual QSize maximumSizeHint () const
virtual QList< QCPLayoutElement * > elements (bool recursive) const
virtual double selectTest (const QPointF &pos, bool onlySelectable, QVariant *details=0) const
Public Member Functions inherited from QCPLayerable
QCPLayerable (QCustomPlot *plot, QString targetLayer=QString(), QCPLayerable *parentLayerable=0)
~QCPLayerable ()
bool visible () const
QCustomPlot * parentPlot () const
QCPLayerable * parentLayerable () const
QCPLayer * layer () const
bool antialiased () const
void setVisible (bool on)
Q_SLOT bool setLayer (QCPLayer *layer)
bool setLayer (const QString &layerName)
void setAntialiased (bool enabled)
bool realVisibility () const
Protected Member Functions
virtual int calculateAutoMargin (QCP::MarginSide side)
virtual void mousePressEvent (QMouseEvent *event)
virtual void mouseMoveEvent (QMouseEvent *event)
virtual void mouseReleaseEvent (QMouseEvent *event)
virtual void mouseDoubleClickEvent (QMouseEvent *event)
virtual void wheelEvent (QWheelEvent *event)
virtual void applyDefaultAntialiasingHint (QCPPainter *painter) const
virtual void draw (QCPPainter *painter)
virtual void parentPlotInitialized (QCustomPlot *parentPlot)
Protected Member Functions inherited from QCPLayerable
virtual QCP::Interaction selectionCategory () const
virtual QRect clipRect () const
virtual void selectEvent (QMouseEvent *event, bool additive, const QVariant &details, bool *selectionStateChanged)
virtual void deselectEvent (bool *selectionStateChanged)
void initializeParentPlot (QCustomPlot *parentPlot)
void setParentLayerable (QCPLayerable *parentLayerable)
bool moveToLayer (QCPLayer *layer, bool prepend)
void applyAntialiasingHint (QCPPainter *painter, bool localAntialiased, QCP::AntialiasedElement overrideElement) const
Protected Attributes
QCPLayout * mParentLayout
QSize mMinimumSize
QSize mMaximumSize
QRect mRect
QRect mOuterRect
QMargins mMargins
QMargins mMinimumMargins
QCP::MarginSides mAutoMargins
QHash< QCP::MarginSide,
QCPMarginGroup * > mMarginGroups
Protected Attributes inherited from QCPLayerable
bool mVisible
QCustomPlot * mParentPlot
QPointer< QCPLayerable > mParentLayerable
QCPLayer * mLayer
bool mAntialiased
Friends
class QCustomPlot
class QCPLayout
class QCPMarginGroup
Additional Inherited Members
Signals inherited from QCPLayerable
void layerChanged (QCPLayer *newLayer)
Detailed Description
The abstract base class for all objects that form the layout system.
This is an abstract base class. As such, it can't be instantiated directly, rather use one of its subclasses.
A Layout element is a rectangular object which can be placed in layouts. It has an outer rect (QCPLayoutElement::outerRect) and an inner rect (QCPLayoutElement::rect). The difference between outer and inner rect is called its margin. The margin can either be set to automatic or manual (setAutoMargins) on a per-side basis. If a side is set to manual, that margin can be set explicitly with setMargins and will stay fixed at that value. If it's set to automatic, the layout element subclass will control the value itself (via calculateAutoMargin).
Layout elements can be placed in layouts (base class QCPLayout) like QCPLayoutGrid. The top level layout is reachable via QCustomPlot::plotLayout, and is a QCPLayoutGrid. Since QCPLayout itself derives from QCPLayoutElement, layouts can be nested.
Thus in QCustomPlot one can divide layout elements into two categories: The ones that are invisible by themselves, because they don't draw anything. Their only purpose is to manage the position and size of other layout elements. This category of layout elements usually use QCPLayout as base class. Then there is the category of layout elements which actually draw something. For example, QCPAxisRect, QCPLegend and QCPPlotTitle are of this category. This does not necessarily mean that the latter category can't have child layout elements. QCPLegend for instance, actually derives from QCPLayoutGrid and the individual legend items are child layout elements in the grid layout.
Definition at line 629 of file qcustomplot.h.
Member Enumeration Documentation
enum UpdatePhase
Defines the phases of the update process, that happens just before a replot. At each phase, update is called with the according UpdatePhase value.
Enumerator
upPreparation
Phase used for any type of preparation that needs to be done before margin calculation and layout.
upMargins
Phase in which the margins are calculated and set.
upLayout
Final phase in which the layout system places the rects of the elements.
Definition at line 646 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPLayoutElement (QCustomPlot * parentPlot = 0) explicit
Creates an instance of QCPLayoutElement and sets default values.
Definition at line 1722 of file qcustomplot.cpp.
~QCPLayoutElement () virtual
Definition at line 1735 of file qcustomplot.cpp.
References mParentLayout, QCP::msAll, setMarginGroup(), and QCPLayout::take().
Member Function Documentation
virtual void applyDefaultAntialiasingHint (QCPPainter * painter) const inline protected virtual
Implements QCPLayerable.
Reimplemented in QCPColorScale, QCPPlotTitle, QCPLegend, QCPAbstractLegendItem, and QCPAxisRect.
Definition at line 706 of file qcustomplot.h.
QCP::MarginSides autoMargins () const inline
Definition at line 661 of file qcustomplot.h.
int calculateAutoMargin (QCP::MarginSide side) protected virtual
Reimplemented in QCPAxisRect.
Definition at line 2036 of file qcustomplot.cpp.
References QCP::getMarginValue(), mMargins, and mMinimumMargins.
Referenced by update().
virtual void draw (QCPPainter * painter) inline protected virtual
Implements QCPLayerable.
Reimplemented in QCPColorScaleAxisRectPrivate, QCPPlotTitle, QCPLegend, QCPPlottableLegendItem, QCPAbstractLegendItem, and QCPAxisRect.
Definition at line 707 of file qcustomplot.h.
QList< QCPLayoutElement * > elements (bool recursive) const virtual
Returns a list of all child elements in this layout element. If recursive is true, all sub-child elements are included in the list, too.
Warning
There may be entries with value 0 in the returned list. (For example, QCPLayoutGrid may have empty cells which yield 0 at the respective index.)
Reimplemented in QCPAxisRect, QCPLayoutGrid, and QCPLayout.
Definition at line 1976 of file qcustomplot.cpp.
Referenced by QCustomPlot::axisRects(), QCustomPlot::layoutElementAt(), parentPlotInitialized(), and QCustomPlot::selectedLegends().
QCPLayout * layout () const inline
Returns the parent layout of this layout element.
Definition at line 656 of file qcustomplot.h.
Referenced by QCPLayoutGrid::addElement(), and QCPLayoutInset::addElement().
QCPMarginGroup* marginGroup (QCP::MarginSide side) const inline
Definition at line 664 of file qcustomplot.h.
Referenced by setMarginGroup().
QHash<QCP::MarginSide, QCPMarginGroup*> marginGroups () const inline
Definition at line 665 of file qcustomplot.h.
QMargins margins () const inline
Definition at line 659 of file qcustomplot.h.
Referenced by setMargins(), setMinimumMargins(), and QCPColorScale::update().
QSize maximumSize () const inline
Definition at line 663 of file qcustomplot.h.
QSize maximumSizeHint () const virtual
Returns the maximum size this layout element (the inner rect) may be expanded to.
if a maximum size (setMaximumSize) was not set manually, parent layouts consult this function to determine the maximum allowed size of this layout element. (A manual maximum size is considered set if it is smaller than Qt's QWIDGETSIZE_MAX.)
Reimplemented in QCPPlotTitle, and QCPLayoutGrid.
Definition at line 1964 of file qcustomplot.cpp.
References mMaximumSize.
QMargins minimumMargins () const inline
Definition at line 660 of file qcustomplot.h.
QSize minimumSize () const inline
Definition at line 662 of file qcustomplot.h.
QSize minimumSizeHint () const virtual
Returns the minimum size this layout element (the inner rect) may be compressed to.
if a minimum size (setMinimumSize) was not set manually, parent layouts consult this function to determine the minimum allowed size of this layout element. (A manual minimum size is considered set if it is non-zero.)
Reimplemented in QCPPlotTitle, QCPPlottableLegendItem, and QCPLayoutGrid.
Definition at line 1952 of file qcustomplot.cpp.
References mMinimumSize.
void mouseDoubleClickEvent (QMouseEvent * event) inline protected virtual
This event is called, if the mouse is double-clicked inside the outer rect of this layout element.
Definition at line 702 of file qcustomplot.h.
void mouseMoveEvent (QMouseEvent * event) inline protected virtual
This event is called, if the mouse is moved inside the outer rect of this layout element.
Reimplemented in QCPColorScale, and QCPAxisRect.
Definition at line 700 of file qcustomplot.h.
void mousePressEvent (QMouseEvent * event) inline protected virtual
This event is called, if the mouse was pressed while being inside the outer rect of this layout element.
Reimplemented in QCPColorScale, and QCPAxisRect.
Definition at line 699 of file qcustomplot.h.
void mouseReleaseEvent (QMouseEvent * event) inline protected virtual
This event is called, if the mouse was previously pressed inside the outer rect of this layout element and is now released.
Reimplemented in QCPColorScale, and QCPAxisRect.
Definition at line 701 of file qcustomplot.h.
QRect outerRect () const inline
Definition at line 658 of file qcustomplot.h.
void parentPlotInitialized (QCustomPlot * parentPlot) protected virtual
Reimplemented from QCPLayerable.
Reimplemented in QCPLegend.
Definition at line 2018 of file qcustomplot.cpp.
References elements(), QCPLayerable::initializeParentPlot(), and QCPLayerable::parentPlot().
QRect rect () const inline
Returns the inner rect of this layout element. The inner rect is the outer rect (setOuterRect) shrinked by the margins (setMargins, setAutoMargins).
In some cases, the area between outer and inner rect is left blank. In other cases the margin area is used to display peripheral graphics while the main content is in the inner rect. This is where automatic margin calculation becomes interesting because it allows the layout element to adapt the margins to the peripheral graphics it wants to draw. For example, QCPAxisRect draws the axis labels and tick labels in the margin area, thus needs to adjust the margins (if setAutoMargins is enabled) according to the space required by the labels of the axes.
Definition at line 657 of file qcustomplot.h.
Referenced by QCPAxis::calculateMargin(), QCPAxis::draw(), QCPColorScaleAxisRectPrivate::draw(), QCustomPlot::plottableAt(), QCPLayoutInset::setInsetRect(), setOuterRect(), QCPAxisRect::update(), QCPColorScale::update(), QCPColorScaleAxisRectPrivate::updateGradientImage(), and QCPLayoutInset::updateLayout().
double selectTest (const QPointF & pos, bool onlySelectable, QVariant * details = 0) const virtual
Layout elements are sensitive to events inside their outer rect. If pos is within the outer rect, this method returns a value corresponding to 0.99 times the parent plot's selection tolerance. However, layout elements are not selectable by default. So if onlySelectable is true, -1.0 is returned.
See QCPLayerable::selectTest for a general explanation of this virtual method.
QCPLayoutElement subclasses may reimplement this method to provide more specific selection test behaviour.
Reimplemented from QCPLayerable.
Reimplemented in QCPPlotTitle, QCPLegend, QCPAbstractLegendItem, and QCPLayoutInset.
Definition at line 1993 of file qcustomplot.cpp.
References mOuterRect, QCPLayerable::mParentPlot, and QCustomPlot::selectionTolerance().
Referenced by QCustomPlot::layoutElementAt().
void setAutoMargins (QCP::MarginSides sides)
Sets on which sides the margin shall be calculated automatically. If a side is calculated automatically, a minimum margin value may be provided with setMinimumMargins. If a side is set to be controlled manually, the value may be specified with setMargins.
Margin sides that are under automatic control may participate in a QCPMarginGroup (see setMarginGroup), to synchronize (align) it with other layout elements in the plot.
See Also
setMinimumMargins, setMargins
Definition at line 1810 of file qcustomplot.cpp.
References mAutoMargins.
void setMarginGroup (QCP::MarginSides sides, QCPMarginGroup * group)
Sets the margin group of the specified margin sides.
Margin groups allow synchronizing specified margins across layout elements, see the documentation of QCPMarginGroup.
To unset the margin group of sides, set group to 0.
Note that margin groups only work for margin sides that are set to automatic (setAutoMargins).
Definition at line 1877 of file qcustomplot.cpp.
References QCPMarginGroup::addChild(), marginGroup(), mMarginGroups, QCP::msBottom, QCP::msLeft, QCP::msRight, QCP::msTop, and QCPMarginGroup::removeChild().
Referenced by ~QCPLayoutElement().
void setMargins (const QMargins & margins)
Sets the margins of this layout element. If setAutoMargins is disabled for some or all sides, this function is used to manually set the margin on those sides. Sides that are still set to be handled automatically are ignored and may have any value in margins.
The margin is the distance between the outer rect (controlled by the parent layout via setOuterRect) and the inner rect (which usually contains the main content of this layout element).
See Also
setAutoMargins
Definition at line 1774 of file qcustomplot.cpp.
References margins(), mMargins, mOuterRect, and mRect.
Referenced by QCPAbstractLegendItem::QCPAbstractLegendItem(), QCPLegend::QCPLegend(), QCPPlotTitle::QCPPlotTitle(), QCustomPlot::QCustomPlot(), and update().
void setMaximumSize (const QSize & size)
Sets the maximum size for the inner rect of this layout element. A parent layout tries to respect the size here by changing row/column sizes in the layout accordingly.
Definition at line 1847 of file qcustomplot.cpp.
References mMaximumSize, mParentLayout, and QCPLayout::sizeConstraintsChanged().
Referenced by setMaximumSize(), and QCPColorScale::update().
void setMaximumSize (int width, int height)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Sets the maximum size for the inner rect of this layout element.
Definition at line 1861 of file qcustomplot.cpp.
References setMaximumSize().
void setMinimumMargins (const QMargins & margins)
If setAutoMargins is enabled on some or all margins, this function is used to provide minimum values for those margins.
The minimum values are not enforced on margin sides that were set to be under manual control via setAutoMargins.
See Also
setAutoMargins
Definition at line 1792 of file qcustomplot.cpp.
References margins(), and mMinimumMargins.
Referenced by QCPAxisRect::QCPAxisRect(), QCPColorScale::QCPColorScale(), and QCPColorScaleAxisRectPrivate::QCPColorScaleAxisRectPrivate().
void setMinimumSize (const QSize & size)
Sets the minimum size for the inner rect of this layout element. A parent layout tries to respect the size here by changing row/column sizes in the layout accordingly.
If the parent layout size is not sufficient to satisfy all minimum size constraints of its child layout elements, the layout may set a size that is actually smaller than size. QCustomPlot propagates the layout's size constraints to the outside by setting its own minimum QWidget size accordingly, so violations of size should be exceptions.
Definition at line 1824 of file qcustomplot.cpp.
References mMinimumSize, mParentLayout, and QCPLayout::sizeConstraintsChanged().
Referenced by QCPAxisRect::QCPAxisRect(), setMinimumSize(), and QCPColorScale::update().
void setMinimumSize (int width, int height)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Sets the minimum size for the inner rect of this layout element.
Definition at line 1838 of file qcustomplot.cpp.
References setMinimumSize().
void setOuterRect (const QRect & rect)
Sets the outer rect of this layout element. If the layout element is inside a layout, the layout sets the position and size of this layout element using this function.
Calling this function externally has no effect, since the layout will overwrite any changes to the outer rect upon the next replot.
The layout element will adapt its inner rect by applying the margins inward to the outer rect.
See Also
rect
Definition at line 1754 of file qcustomplot.cpp.
References mMargins, mOuterRect, mRect, and rect().
Referenced by QCustomPlot::setViewport(), and QCPAxisRect::update().
void update (UpdatePhase phase) virtual
Updates the layout element and sub-elements. This function is automatically called before every replot by the parent layout element. It is called multiple times, once for every UpdatePhase. The phases are run through in the order of the enum values. For details about what happens at the different phases, see the documentation of UpdatePhase.
Layout elements that have child elements should call the update method of their child elements, and pass the current phase unchanged.
The default implementation executes the automatic margin mechanism in the upMargins phase. Subclasses should make sure to call the base class implementation.
Reimplemented in QCPColorScale, QCPAxisRect, and QCPLayout.
Definition at line 1918 of file qcustomplot.cpp.
References calculateAutoMargin(), QCP::getMarginValue(), mAutoMargins, mMarginGroups, mMargins, mMinimumMargins, QCP::msBottom, QCP::msLeft, QCP::msNone, QCP::msRight, QCP::msTop, setMargins(), QCP::setMarginValue(), and upMargins.
Referenced by QCPLayout::update(), QCPAxisRect::update(), and QCPColorScale::update().
void wheelEvent (QWheelEvent * event) inline protected virtual
This event is called, if the mouse wheel is scrolled while the cursor is inside the rect of this layout element.
Reimplemented in QCPColorScale, and QCPAxisRect.
Definition at line 703 of file qcustomplot.h.
Friends And Related Function Documentation
friend class QCPLayout friend
Definition at line 714 of file qcustomplot.h.
friend class QCPMarginGroup friend
Definition at line 715 of file qcustomplot.h.
friend class QCustomPlot friend
Definition at line 713 of file qcustomplot.h.
Member Data Documentation
QCP::MarginSides mAutoMargins protected
Definition at line 693 of file qcustomplot.h.
Referenced by QCPAxisRect::calculateAutoMargin(), setAutoMargins(), and update().
QHash<QCP::MarginSide, QCPMarginGroup*> mMarginGroups protected
Definition at line 694 of file qcustomplot.h.
Referenced by setMarginGroup(), and update().
QMargins mMargins protected
Definition at line 692 of file qcustomplot.h.
Referenced by calculateAutoMargin(), QCPLayoutGrid::maximumSizeHint(), QCPPlotTitle::maximumSizeHint(), QCPLayoutGrid::minimumSizeHint(), QCPPlottableLegendItem::minimumSizeHint(), QCPPlotTitle::minimumSizeHint(), setMargins(), setOuterRect(), and update().
QSize mMaximumSize protected
Definition at line 690 of file qcustomplot.h.
Referenced by maximumSizeHint(), and setMaximumSize().
QMargins mMinimumMargins protected
Definition at line 692 of file qcustomplot.h.
Referenced by calculateAutoMargin(), setMinimumMargins(), and update().
QSize mMinimumSize protected
Definition at line 690 of file qcustomplot.h.
Referenced by minimumSizeHint(), and setMinimumSize().
QRect mOuterRect protected
Definition at line 691 of file qcustomplot.h.
Referenced by QCPAbstractLegendItem::clipRect(), QCPLegend::draw(), selectTest(), QCPLegend::selectTest(), setMargins(), and setOuterRect().
QCPLayout* mParentLayout protected
Definition at line 689 of file qcustomplot.h.
Referenced by QCPLayout::adoptElement(), QCPLayout::releaseElement(), setMaximumSize(), setMinimumSize(), and ~QCPLayoutElement().
QRect mRect protected
Definition at line 691 of file qcustomplot.h.
Referenced by QCPPlottableLegendItem::draw(), QCPPlotTitle::draw(), QCPAxisRect::drawBackground(), QCPAbstractLegendItem::selectTest(), setMargins(), setOuterRect(), and QCPLayoutGrid::updateLayout().
The documentation for this class was generated from the following files:
qcustomplot.h
qcustomplot.cpp