SETestKCL: QCPItemPixmap Class Reference
QCPItemPixmap Class Reference
#include <qcustomplot.h>
Public Member Functions
QCPItemPixmap (QCustomPlot *parentPlot)
virtual ~QCPItemPixmap ()
QPixmap pixmap () const
bool scaled () const
Qt::AspectRatioMode aspectRatioMode () const
Qt::TransformationMode transformationMode () const
QPen pen () const
QPen selectedPen () const
void setPixmap (const QPixmap &pixmap)
void setScaled (bool scaled, Qt::AspectRatioMode aspectRatioMode=Qt::KeepAspectRatio, Qt::TransformationMode transformationMode=Qt::SmoothTransformation)
void setPen (const QPen &pen)
void setSelectedPen (const QPen &pen)
virtual double selectTest (const QPointF &pos, bool onlySelectable, QVariant *details=0) const
Public Member Functions inherited from QCPAbstractItem
QCPAbstractItem (QCustomPlot *parentPlot)
virtual ~QCPAbstractItem ()
bool clipToAxisRect () const
QCPAxisRect * clipAxisRect () const
bool selectable () const
bool selected () const
void setClipToAxisRect (bool clip)
void setClipAxisRect (QCPAxisRect *rect)
Q_SLOT void setSelectable (bool selectable)
Q_SLOT void setSelected (bool selected)
QList< QCPItemPosition * > positions () const
QList< QCPItemAnchor * > anchors () const
QCPItemPosition * position (const QString &name) const
QCPItemAnchor * anchor (const QString &name) const
bool hasAnchor (const QString &name) const
Public Member Functions inherited from QCPLayerable
QCPLayerable (QCustomPlot *plot, QString targetLayer=QString(), QCPLayerable *parentLayerable=0)
~QCPLayerable ()
bool visible () const
QCustomPlot * parentPlot () const
QCPLayerable * parentLayerable () const
QCPLayer * layer () const
bool antialiased () const
void setVisible (bool on)
Q_SLOT bool setLayer (QCPLayer *layer)
bool setLayer (const QString &layerName)
void setAntialiased (bool enabled)
bool realVisibility () const
Public Attributes
QCPItemPosition *const topLeft
QCPItemPosition *const bottomRight
QCPItemAnchor *const top
QCPItemAnchor *const topRight
QCPItemAnchor *const right
QCPItemAnchor *const bottom
QCPItemAnchor *const bottomLeft
QCPItemAnchor *const left
Protected Types
enum AnchorIndex {
aiTop, aiTopRight, aiRight, aiBottom,
aiBottomLeft, aiLeft
}
Protected Member Functions
virtual void draw (QCPPainter *painter)
virtual QPointF anchorPixelPoint (int anchorId) const
void updateScaledPixmap (QRect finalRect=QRect(), bool flipHorz=false, bool flipVert=false)
QRect getFinalRect (bool *flippedHorz=0, bool *flippedVert=0) const
QPen mainPen () const
Protected Member Functions inherited from QCPAbstractItem
virtual QCP::Interaction selectionCategory () const
virtual QRect clipRect () const
virtual void applyDefaultAntialiasingHint (QCPPainter *painter) const
virtual void selectEvent (QMouseEvent *event, bool additive, const QVariant &details, bool *selectionStateChanged)
virtual void deselectEvent (bool *selectionStateChanged)
double distSqrToLine (const QPointF &start, const QPointF &end, const QPointF &point) const
double rectSelectTest (const QRectF &rect, const QPointF &pos, bool filledRect) const
QCPItemPosition * createPosition (const QString &name)
QCPItemAnchor * createAnchor (const QString &name, int anchorId)
Protected Member Functions inherited from QCPLayerable
virtual void parentPlotInitialized (QCustomPlot *parentPlot)
void initializeParentPlot (QCustomPlot *parentPlot)
void setParentLayerable (QCPLayerable *parentLayerable)
bool moveToLayer (QCPLayer *layer, bool prepend)
void applyAntialiasingHint (QCPPainter *painter, bool localAntialiased, QCP::AntialiasedElement overrideElement) const
Protected Attributes
QPixmap mPixmap
QPixmap mScaledPixmap
bool mScaled
bool mScaledPixmapInvalidated
Qt::AspectRatioMode mAspectRatioMode
Qt::TransformationMode mTransformationMode
QPen mPen
QPen mSelectedPen
Protected Attributes inherited from QCPAbstractItem
bool mClipToAxisRect
QPointer< QCPAxisRect > mClipAxisRect
QList< QCPItemPosition * > mPositions
QList< QCPItemAnchor * > mAnchors
bool mSelectable
bool mSelected
Protected Attributes inherited from QCPLayerable
bool mVisible
QCustomPlot * mParentPlot
QPointer< QCPLayerable > mParentLayerable
QCPLayer * mLayer
bool mAntialiased
Additional Inherited Members
Signals inherited from QCPAbstractItem
void selectionChanged (bool selected)
void selectableChanged (bool selectable)
Signals inherited from QCPLayerable
void layerChanged (QCPLayer *newLayer)
Detailed Description
An arbitrary pixmap.
Pixmap example. Blue dotted circles are anchors, solid blue discs are positions.
It has two positions, topLeft and bottomRight, which define the rectangle the pixmap will be drawn in. Depending on the scale setting (setScaled), the pixmap will be either scaled to fit the rectangle or be drawn aligned to the topLeft position.
If scaling is enabled and topLeft is further to the bottom/right than bottomRight (as shown on the right side of the example image), the pixmap will be flipped in the respective orientations.
Definition at line 3570 of file qcustomplot.h.
Member Enumeration Documentation
enum AnchorIndex protected
Enumerator
aiTop
aiTopRight
aiRight
aiBottom
aiBottomLeft
aiLeft
Definition at line 3612 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPItemPixmap (QCustomPlot * parentPlot)
Creates a rectangle item and sets default values.
The constructed item can be added to the plot with QCustomPlot::addItem.
Definition at line 22732 of file qcustomplot.cpp.
References bottomRight, QCPItemPosition::setCoords(), setPen(), setScaled(), setSelectedPen(), and topLeft.
~QCPItemPixmap () virtual
Definition at line 22752 of file qcustomplot.cpp.
Member Function Documentation
QPointF anchorPixelPoint (int anchorId) const protected virtual
Reimplemented from QCPAbstractItem.
Definition at line 22832 of file qcustomplot.cpp.
References aiBottom, aiBottomLeft, aiLeft, aiRight, aiTop, aiTopRight, and getFinalRect().
Qt::AspectRatioMode aspectRatioMode () const inline
Definition at line 3588 of file qcustomplot.h.
Referenced by setScaled().
void draw (QCPPainter * painter) protected virtual
Implements QCPAbstractItem.
Definition at line 22810 of file qcustomplot.cpp.
References QCPAbstractItem::clipRect(), getFinalRect(), mainPen(), mPixmap, mScaled, mScaledPixmap, pen(), QCPPainter::setPen(), and updateScaledPixmap().
QRect getFinalRect (bool * flippedHorz = 0, bool * flippedVert = 0) const protected
Definition at line 22905 of file qcustomplot.cpp.
References bottomRight, mAspectRatioMode, mPixmap, mScaled, QCPItemPosition::pixelPoint(), and topLeft.
Referenced by anchorPixelPoint(), draw(), selectTest(), and updateScaledPixmap().
QPen mainPen () const protected
Definition at line 22949 of file qcustomplot.cpp.
References mPen, QCPAbstractItem::mSelected, and mSelectedPen.
Referenced by draw().
QPen pen () const inline
Definition at line 3590 of file qcustomplot.h.
Referenced by draw(), setPen(), and setSelectedPen().
QPixmap pixmap () const inline
Definition at line 3586 of file qcustomplot.h.
Referenced by setPixmap().
bool scaled () const inline
Definition at line 3587 of file qcustomplot.h.
Referenced by setScaled().
QPen selectedPen () const inline
Definition at line 3591 of file qcustomplot.h.
double selectTest (const QPointF & pos, bool onlySelectable, QVariant * details = 0) const virtual
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
You may pass 0 as details to indicate that you are not interested in those selection details.
See Also
selectEvent, deselectEvent, QCustomPlot::setInteractions
Implements QCPAbstractItem.
Definition at line 22800 of file qcustomplot.cpp.
References getFinalRect(), QCPAbstractItem::mSelectable, and QCPAbstractItem::rectSelectTest().
void setPen (const QPen & pen)
Sets the pen that will be used to draw a border around the pixmap.
See Also
setSelectedPen, setBrush
Definition at line 22784 of file qcustomplot.cpp.
References mPen, and pen().
Referenced by QCPItemPixmap().
void setPixmap (const QPixmap & pixmap)
Sets the pixmap that will be displayed.
Definition at line 22759 of file qcustomplot.cpp.
References mPixmap, mScaledPixmapInvalidated, and pixmap().
void setScaled (bool scaled, Qt::AspectRatioMode aspectRatioMode = Qt::KeepAspectRatio, Qt::TransformationMode transformationMode = Qt::SmoothTransformation)
Sets whether the pixmap will be scaled to fit the rectangle defined by the topLeft and bottomRight positions.
Definition at line 22771 of file qcustomplot.cpp.
References aspectRatioMode(), mAspectRatioMode, mScaled, mScaledPixmapInvalidated, mTransformationMode, scaled(), and transformationMode().
Referenced by QCPItemPixmap().
void setSelectedPen (const QPen & pen)
Sets the pen that will be used to draw a border around the pixmap when selected
See Also
setPen, setSelected
Definition at line 22794 of file qcustomplot.cpp.
References mSelectedPen, and pen().
Referenced by QCPItemPixmap().
Qt::TransformationMode transformationMode () const inline
Definition at line 3589 of file qcustomplot.h.
Referenced by setScaled().
void updateScaledPixmap (QRect finalRect = QRect(), bool flipHorz = false, bool flipVert = false) protected
Definition at line 22871 of file qcustomplot.cpp.
References getFinalRect(), mAspectRatioMode, mPixmap, mScaled, mScaledPixmap, mScaledPixmapInvalidated, and mTransformationMode.
Referenced by draw().
Member Data Documentation
QCPItemAnchor* const bottom
Definition at line 3607 of file qcustomplot.h.
QCPItemAnchor* const bottomLeft
Definition at line 3608 of file qcustomplot.h.
QCPItemPosition* const bottomRight
Definition at line 3603 of file qcustomplot.h.
Referenced by getFinalRect(), and QCPItemPixmap().
QCPItemAnchor* const left
Definition at line 3609 of file qcustomplot.h.
Qt::AspectRatioMode mAspectRatioMode protected
Definition at line 3619 of file qcustomplot.h.
Referenced by getFinalRect(), setScaled(), and updateScaledPixmap().
QPen mPen protected
Definition at line 3621 of file qcustomplot.h.
Referenced by mainPen(), and setPen().
QPixmap mPixmap protected
Definition at line 3615 of file qcustomplot.h.
Referenced by draw(), getFinalRect(), setPixmap(), and updateScaledPixmap().
bool mScaled protected
Definition at line 3617 of file qcustomplot.h.
Referenced by draw(), getFinalRect(), setScaled(), and updateScaledPixmap().
QPixmap mScaledPixmap protected
Definition at line 3616 of file qcustomplot.h.
Referenced by draw(), and updateScaledPixmap().
bool mScaledPixmapInvalidated protected
Definition at line 3618 of file qcustomplot.h.
Referenced by setPixmap(), setScaled(), and updateScaledPixmap().
QPen mSelectedPen protected
Definition at line 3621 of file qcustomplot.h.
Referenced by mainPen(), and setSelectedPen().
Qt::TransformationMode mTransformationMode protected
Definition at line 3620 of file qcustomplot.h.
Referenced by setScaled(), and updateScaledPixmap().
QCPItemAnchor* const right
Definition at line 3606 of file qcustomplot.h.
QCPItemAnchor* const top
Definition at line 3604 of file qcustomplot.h.
QCPItemPosition* const topLeft
Definition at line 3602 of file qcustomplot.h.
Referenced by getFinalRect(), and QCPItemPixmap().
QCPItemAnchor* const topRight
Definition at line 3605 of file qcustomplot.h.
The documentation for this class was generated from the following files:
qcustomplot.h
qcustomplot.cpp