SETestKCL: QCPItemText Class Reference
QCPItemText Class Reference
#include <qcustomplot.h>
Public Member Functions
QCPItemText (QCustomPlot *parentPlot)
virtual ~QCPItemText ()
QColor color () const
QColor selectedColor () const
QPen pen () const
QPen selectedPen () const
QBrush brush () const
QBrush selectedBrush () const
QFont font () const
QFont selectedFont () const
QString text () const
Qt::Alignment positionAlignment () const
Qt::Alignment textAlignment () const
double rotation () const
QMargins padding () const
void setColor (const QColor &color)
void setSelectedColor (const QColor &color)
void setPen (const QPen &pen)
void setSelectedPen (const QPen &pen)
void setBrush (const QBrush &brush)
void setSelectedBrush (const QBrush &brush)
void setFont (const QFont &font)
void setSelectedFont (const QFont &font)
void setText (const QString &text)
void setPositionAlignment (Qt::Alignment alignment)
void setTextAlignment (Qt::Alignment alignment)
void setRotation (double degrees)
void setPadding (const QMargins &padding)
virtual double selectTest (const QPointF &pos, bool onlySelectable, QVariant *details=0) const
Public Member Functions inherited from QCPAbstractItem
QCPAbstractItem (QCustomPlot *parentPlot)
virtual ~QCPAbstractItem ()
bool clipToAxisRect () const
QCPAxisRect * clipAxisRect () const
bool selectable () const
bool selected () const
void setClipToAxisRect (bool clip)
void setClipAxisRect (QCPAxisRect *rect)
Q_SLOT void setSelectable (bool selectable)
Q_SLOT void setSelected (bool selected)
QList< QCPItemPosition * > positions () const
QList< QCPItemAnchor * > anchors () const
QCPItemPosition * position (const QString &name) const
QCPItemAnchor * anchor (const QString &name) const
bool hasAnchor (const QString &name) const
Public Member Functions inherited from QCPLayerable
QCPLayerable (QCustomPlot *plot, QString targetLayer=QString(), QCPLayerable *parentLayerable=0)
~QCPLayerable ()
bool visible () const
QCustomPlot * parentPlot () const
QCPLayerable * parentLayerable () const
QCPLayer * layer () const
bool antialiased () const
void setVisible (bool on)
Q_SLOT bool setLayer (QCPLayer *layer)
bool setLayer (const QString &layerName)
void setAntialiased (bool enabled)
bool realVisibility () const
Public Attributes
QCPItemPosition *const position
QCPItemAnchor *const topLeft
QCPItemAnchor *const top
QCPItemAnchor *const topRight
QCPItemAnchor *const right
QCPItemAnchor *const bottomRight
QCPItemAnchor *const bottom
QCPItemAnchor *const bottomLeft
QCPItemAnchor *const left
Protected Types
enum AnchorIndex {
aiTopLeft, aiTop, aiTopRight, aiRight,
aiBottomRight, aiBottom, aiBottomLeft, aiLeft
}
Protected Member Functions
virtual void draw (QCPPainter *painter)
virtual QPointF anchorPixelPoint (int anchorId) const
QPointF getTextDrawPoint (const QPointF &pos, const QRectF &rect, Qt::Alignment positionAlignment) const
QFont mainFont () const
QColor mainColor () const
QPen mainPen () const
QBrush mainBrush () const
Protected Member Functions inherited from QCPAbstractItem
virtual QCP::Interaction selectionCategory () const
virtual QRect clipRect () const
virtual void applyDefaultAntialiasingHint (QCPPainter *painter) const
virtual void selectEvent (QMouseEvent *event, bool additive, const QVariant &details, bool *selectionStateChanged)
virtual void deselectEvent (bool *selectionStateChanged)
double distSqrToLine (const QPointF &start, const QPointF &end, const QPointF &point) const
double rectSelectTest (const QRectF &rect, const QPointF &pos, bool filledRect) const
QCPItemPosition * createPosition (const QString &name)
QCPItemAnchor * createAnchor (const QString &name, int anchorId)
Protected Member Functions inherited from QCPLayerable
virtual void parentPlotInitialized (QCustomPlot *parentPlot)
void initializeParentPlot (QCustomPlot *parentPlot)
void setParentLayerable (QCPLayerable *parentLayerable)
bool moveToLayer (QCPLayer *layer, bool prepend)
void applyAntialiasingHint (QCPPainter *painter, bool localAntialiased, QCP::AntialiasedElement overrideElement) const
Protected Attributes
QColor mColor
QColor mSelectedColor
QPen mPen
QPen mSelectedPen
QBrush mBrush
QBrush mSelectedBrush
QFont mFont
QFont mSelectedFont
QString mText
Qt::Alignment mPositionAlignment
Qt::Alignment mTextAlignment
double mRotation
QMargins mPadding
Protected Attributes inherited from QCPAbstractItem
bool mClipToAxisRect
QPointer< QCPAxisRect > mClipAxisRect
QList< QCPItemPosition * > mPositions
QList< QCPItemAnchor * > mAnchors
bool mSelectable
bool mSelected
Protected Attributes inherited from QCPLayerable
bool mVisible
QCustomPlot * mParentPlot
QPointer< QCPLayerable > mParentLayerable
QCPLayer * mLayer
bool mAntialiased
Additional Inherited Members
Signals inherited from QCPAbstractItem
void selectionChanged (bool selected)
void selectableChanged (bool selectable)
Signals inherited from QCPLayerable
void layerChanged (QCPLayer *newLayer)
Detailed Description
A text label.
Text example. Blue dotted circles are anchors, solid blue discs are positions.
Its position is defined by the member position and the setting of setPositionAlignment. The latter controls which part of the text rect shall be aligned with position.
The text alignment itself (i.e. left, center, right) can be controlled with setTextAlignment.
The text may be rotated around the position point with setRotation.
Definition at line 3421 of file qcustomplot.h.
Member Enumeration Documentation
enum AnchorIndex protected
Enumerator
aiTopLeft
aiTop
aiTopRight
aiRight
aiBottomRight
aiBottom
aiBottomLeft
aiLeft
Definition at line 3487 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPItemText (QCustomPlot * parentPlot)
Creates a text item and sets default values.
The constructed item can be added to the plot with QCustomPlot::addItem.
Definition at line 22204 of file qcustomplot.cpp.
References position, setBrush(), setColor(), QCPItemPosition::setCoords(), setPen(), setPositionAlignment(), setRotation(), setSelectedBrush(), setSelectedColor(), setSelectedPen(), setText(), and setTextAlignment().
~QCPItemText () virtual
Definition at line 22231 of file qcustomplot.cpp.
Member Function Documentation
QPointF anchorPixelPoint (int anchorId) const protected virtual
Reimplemented from QCPAbstractItem.
Definition at line 22426 of file qcustomplot.cpp.
References aiBottom, aiBottomLeft, aiBottomRight, aiLeft, aiRight, aiTop, aiTopLeft, aiTopRight, getTextDrawPoint(), mainFont(), mPadding, mPositionAlignment, mRotation, mText, mTextAlignment, QCPItemPosition::pixelPoint(), and position.
QBrush brush () const inline
Definition at line 3448 of file qcustomplot.h.
Referenced by setBrush(), and setSelectedBrush().
QColor color () const inline
Definition at line 3444 of file qcustomplot.h.
Referenced by draw(), setColor(), and setSelectedColor().
void draw (QCPPainter * painter) protected virtual
Implements QCPAbstractItem.
Definition at line 22394 of file qcustomplot.cpp.
References QCPAbstractItem::clipRect(), color(), getTextDrawPoint(), mainBrush(), mainColor(), mainFont(), mainPen(), mPadding, mPositionAlignment, mRotation, mText, mTextAlignment, QCPItemPosition::pixelPoint(), position, and QCPPainter::setPen().
QFont font () const inline
Definition at line 3450 of file qcustomplot.h.
Referenced by setFont(), and setSelectedFont().
QPointF getTextDrawPoint (const QPointF & pos, const QRectF & rect, Qt::Alignment positionAlignment) const protected
Definition at line 22467 of file qcustomplot.cpp.
Referenced by anchorPixelPoint(), draw(), and selectTest().
QBrush mainBrush () const protected
Definition at line 22519 of file qcustomplot.cpp.
References mBrush, QCPAbstractItem::mSelected, and mSelectedBrush.
Referenced by draw().
QColor mainColor () const protected
Definition at line 22499 of file qcustomplot.cpp.
References mColor, QCPAbstractItem::mSelected, and mSelectedColor.
Referenced by draw().
QFont mainFont () const protected
Definition at line 22489 of file qcustomplot.cpp.
References mFont, QCPAbstractItem::mSelected, and mSelectedFont.
Referenced by anchorPixelPoint(), and draw().
QPen mainPen () const protected
Definition at line 22509 of file qcustomplot.cpp.
References mPen, QCPAbstractItem::mSelected, and mSelectedPen.
Referenced by draw().
QMargins padding () const inline
Definition at line 3456 of file qcustomplot.h.
Referenced by setPadding().
QPen pen () const inline
Definition at line 3446 of file qcustomplot.h.
Referenced by setPen(), and setSelectedPen().
Qt::Alignment positionAlignment () const inline
Definition at line 3453 of file qcustomplot.h.
double rotation () const inline
Definition at line 3455 of file qcustomplot.h.
QBrush selectedBrush () const inline
Definition at line 3449 of file qcustomplot.h.
QColor selectedColor () const inline
Definition at line 3445 of file qcustomplot.h.
QFont selectedFont () const inline
Definition at line 3451 of file qcustomplot.h.
QPen selectedPen () const inline
Definition at line 3447 of file qcustomplot.h.
double selectTest (const QPointF & pos, bool onlySelectable, QVariant * details = 0) const virtual
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
You may pass 0 as details to indicate that you are not interested in those selection details.
See Also
selectEvent, deselectEvent, QCustomPlot::setInteractions
Implements QCPAbstractItem.
Definition at line 22370 of file qcustomplot.cpp.
References getTextDrawPoint(), mFont, mPadding, mPositionAlignment, mRotation, QCPAbstractItem::mSelectable, mText, mTextAlignment, QCPItemPosition::pixelPoint(), position, and QCPAbstractItem::rectSelectTest().
void setBrush (const QBrush & brush)
Sets the brush that will be used do fill the background of the text. To disable the background, set brush to Qt::NoBrush.
See Also
setSelectedBrush, setPen, setPadding
Definition at line 22279 of file qcustomplot.cpp.
References brush(), and mBrush.
Referenced by QCPItemText().
void setColor (const QColor & color)
Sets the color of the text.
Definition at line 22238 of file qcustomplot.cpp.
References color(), and mColor.
Referenced by QCPItemText().
void setFont (const QFont & font)
Sets the font of the text.
See Also
setSelectedFont, setColor
Definition at line 22300 of file qcustomplot.cpp.
References font(), and mFont.
void setPadding (const QMargins & padding)
Sets the distance between the border of the text rectangle and the text. The appearance (and visibility) of the text rectangle can be controlled with setPen and setBrush.
Definition at line 22364 of file qcustomplot.cpp.
References mPadding, and padding().
void setPen (const QPen & pen)
Sets the pen that will be used do draw a rectangular border around the text. To disable the border, set pen to Qt::NoPen.
See Also
setSelectedPen, setBrush, setPadding
Definition at line 22257 of file qcustomplot.cpp.
References mPen, and pen().
Referenced by QCPItemText().
void setPositionAlignment (Qt::Alignment alignment)
Sets which point of the text rect shall be aligned with position.
Examples:
If alignment is Qt::AlignHCenter | Qt::AlignTop, the text will be positioned such that the top of the text rect will be horizontally centered on position.
If alignment is Qt::AlignLeft | Qt::AlignBottom, position will indicate the bottom left corner of the text rect.
If you want to control the alignment of (multi-lined) text within the text rect, use setTextAlignment.
Definition at line 22338 of file qcustomplot.cpp.
References mPositionAlignment.
Referenced by QCPItemText().
void setRotation (double degrees)
Sets the angle in degrees by which the text (and the text rectangle, if visible) will be rotated around position.
Definition at line 22355 of file qcustomplot.cpp.
References mRotation.
Referenced by QCPItemText().
void setSelectedBrush (const QBrush & brush)
Sets the brush that will be used do fill the background of the text, when the item is selected. To disable the background, set brush to Qt::NoBrush.
See Also
setBrush
Definition at line 22290 of file qcustomplot.cpp.
References brush(), and mSelectedBrush.
Referenced by QCPItemText().
void setSelectedColor (const QColor & color)
Sets the color of the text that will be used when the item is selected.
Definition at line 22246 of file qcustomplot.cpp.
References color(), and mSelectedColor.
Referenced by QCPItemText().
void setSelectedFont (const QFont & font)
Sets the font of the text that will be used when the item is selected.
See Also
setFont
Definition at line 22310 of file qcustomplot.cpp.
References font(), and mSelectedFont.
void setSelectedPen (const QPen & pen)
Sets the pen that will be used do draw a rectangular border around the text, when the item is selected. To disable the border, set pen to Qt::NoPen.
See Also
setPen
Definition at line 22268 of file qcustomplot.cpp.
References mSelectedPen, and pen().
Referenced by QCPItemText().
void setText (const QString & text)
Sets the text that will be displayed. Multi-line texts are supported by inserting a line break character, e.g. '
'.
See Also
setFont, setColor, setTextAlignment
Definition at line 22321 of file qcustomplot.cpp.
References mText, and text().
Referenced by QCPItemText().
void setTextAlignment (Qt::Alignment alignment)
Controls how (multi-lined) text is aligned inside the text rect (typically Qt::AlignLeft, Qt::AlignCenter or Qt::AlignRight).
Definition at line 22346 of file qcustomplot.cpp.
References mTextAlignment.
Referenced by QCPItemText().
QString text () const inline
Definition at line 3452 of file qcustomplot.h.
Referenced by setText().
Qt::Alignment textAlignment () const inline
Definition at line 3454 of file qcustomplot.h.
Member Data Documentation
QCPItemAnchor* const bottom
Definition at line 3482 of file qcustomplot.h.
QCPItemAnchor* const bottomLeft
Definition at line 3483 of file qcustomplot.h.
QCPItemAnchor* const bottomRight
Definition at line 3481 of file qcustomplot.h.
QCPItemAnchor* const left
Definition at line 3484 of file qcustomplot.h.
QBrush mBrush protected
Definition at line 3492 of file qcustomplot.h.
Referenced by mainBrush(), and setBrush().
QColor mColor protected
Definition at line 3490 of file qcustomplot.h.
Referenced by mainColor(), and setColor().
QFont mFont protected
Definition at line 3493 of file qcustomplot.h.
Referenced by mainFont(), selectTest(), and setFont().
QMargins mPadding protected
Definition at line 3498 of file qcustomplot.h.
Referenced by anchorPixelPoint(), draw(), selectTest(), and setPadding().
QPen mPen protected
Definition at line 3491 of file qcustomplot.h.
Referenced by mainPen(), and setPen().
Qt::Alignment mPositionAlignment protected
Definition at line 3495 of file qcustomplot.h.
Referenced by anchorPixelPoint(), draw(), selectTest(), and setPositionAlignment().
double mRotation protected
Definition at line 3497 of file qcustomplot.h.
Referenced by anchorPixelPoint(), draw(), selectTest(), and setRotation().
QBrush mSelectedBrush protected
Definition at line 3492 of file qcustomplot.h.
Referenced by mainBrush(), and setSelectedBrush().
QColor mSelectedColor protected
Definition at line 3490 of file qcustomplot.h.
Referenced by mainColor(), and setSelectedColor().
QFont mSelectedFont protected
Definition at line 3493 of file qcustomplot.h.
Referenced by mainFont(), and setSelectedFont().
QPen mSelectedPen protected
Definition at line 3491 of file qcustomplot.h.
Referenced by mainPen(), and setSelectedPen().
QString mText protected
Definition at line 3494 of file qcustomplot.h.
Referenced by anchorPixelPoint(), draw(), selectTest(), and setText().
Qt::Alignment mTextAlignment protected
Definition at line 3496 of file qcustomplot.h.
Referenced by anchorPixelPoint(), draw(), selectTest(), and setTextAlignment().
QCPItemPosition* const position
Definition at line 3476 of file qcustomplot.h.
Referenced by anchorPixelPoint(), draw(), QCPItemText(), and selectTest().
QCPItemAnchor* const right
Definition at line 3480 of file qcustomplot.h.
QCPItemAnchor* const top
Definition at line 3478 of file qcustomplot.h.
QCPItemAnchor* const topLeft
Definition at line 3477 of file qcustomplot.h.
QCPItemAnchor* const topRight
Definition at line 3479 of file qcustomplot.h.
The documentation for this class was generated from the following files:
qcustomplot.h
qcustomplot.cpp