SETestKCL: QCP Namespace Reference
QCP Namespace Reference
Enumerations
enum MarginSide {
msLeft = 0x01, msRight = 0x02, msTop = 0x04, msBottom = 0x08,
msAll = 0xFF, msNone = 0x00
}
enum AntialiasedElement {
aeAxes = 0x0001, aeGrid = 0x0002, aeSubGrid = 0x0004, aeLegend = 0x0008,
aeLegendItems = 0x0010, aePlottables = 0x0020, aeItems = 0x0040, aeScatters = 0x0080,
aeErrorBars = 0x0100, aeFills = 0x0200, aeZeroLine = 0x0400, aeAll = 0xFFFF,
aeNone = 0x0000
}
enum PlottingHint { phNone = 0x000, phFastPolylines = 0x001, phForceRepaint = 0x002, phCacheLabels = 0x004 }
enum Interaction {
iRangeDrag = 0x001, iRangeZoom = 0x002, iMultiSelect = 0x004, iSelectPlottables = 0x008,
iSelectAxes = 0x010, iSelectLegend = 0x020, iSelectItems = 0x040, iSelectOther = 0x080
}
Functions
bool isInvalidData (double value)
bool isInvalidData (double value1, double value2)
void setMarginValue (QMargins &margins, QCP::MarginSide side, int value)
int getMarginValue (const QMargins &margins, QCP::MarginSide side)
Detailed Description
The QCP Namespace contains general enums and QFlags used throughout the QCustomPlot library
Enumeration Type Documentation
enum AntialiasedElement
Defines what objects of a plot can be forcibly drawn antialiased/not antialiased. If an object is neither forcibly drawn antialiased nor forcibly drawn not antialiased, it is up to the respective element how it is drawn. Typically it provides a setAntialiased function for this.
AntialiasedElements is a flag of or-combined elements of this enum type.
See Also
QCustomPlot::setAntialiasedElements, QCustomPlot::setNotAntialiasedElements
Enumerator
aeAxes
0x0001 Axis base line and tick marks
aeGrid
0x0002 Grid lines
aeSubGrid
0x0004 Sub grid lines
aeLegend
0x0008 Legend box
aeLegendItems
0x0010 Legend items
aePlottables
0x0020 Main lines of plottables (excluding error bars, see element aeErrorBars)
aeItems
0x0040 Main lines of items
aeScatters
0x0080 Scatter symbols of plottables (excluding scatter symbols of type ssPixmap)
aeErrorBars
0x0100 Error bars
aeFills
0x0200 Borders of fills (e.g. under or between graphs)
aeZeroLine
0x0400 Zero-lines, see QCPGrid::setZeroLinePen
aeAll
0xFFFF All elements
aeNone
0x0000 No elements
Definition at line 118 of file qcustomplot.h.
enum Interaction
Defines the mouse interactions possible with QCustomPlot.
Interactions is a flag of or-combined elements of this enum type.
See Also
QCustomPlot::setInteractions
Enumerator
iRangeDrag
0x001 Axis ranges are draggable (see QCPAxisRect::setRangeDrag, QCPAxisRect::setRangeDragAxes)
iRangeZoom
0x002 Axis ranges are zoomable with the mouse wheel (see QCPAxisRect::setRangeZoom, QCPAxisRect::setRangeZoomAxes)
iMultiSelect
0x004 The user can select multiple objects by holding the modifier set by QCustomPlot::setMultiSelectModifier while clicking
iSelectPlottables
0x008 Plottables are selectable (e.g. graphs, curves, bars,... see QCPAbstractPlottable)
iSelectAxes
0x010 Axes are selectable (or parts of them, see QCPAxis::setSelectableParts)
iSelectLegend
0x020 Legends are selectable (or their child items, see QCPLegend::setSelectableParts)
iSelectItems
0x040 Items are selectable (Rectangles, Arrows, Textitems, etc. see QCPAbstractItem)
iSelectOther
0x080 All other objects are selectable (e.g. your own derived layerables, the plot title,...)
Definition at line 155 of file qcustomplot.h.
enum MarginSide
Defines the sides of a rectangular entity to which margins can be applied.
See Also
QCPLayoutElement::setAutoMargins, QCPAxisRect::setAutoMargins
Enumerator
msLeft
0x01 left margin
msRight
0x02 right margin
msTop
0x04 top margin
msBottom
0x08 bottom margin
msAll
0xFF all margins
msNone
0x00 no margin
Definition at line 100 of file qcustomplot.h.
enum PlottingHint
Defines plotting hints that control various aspects of the quality and speed of plotting.
See Also
QCustomPlot::setPlottingHints
Enumerator
phNone
0x000 No hints are set
phFastPolylines
0x001 Graph/Curve lines are drawn with a faster method. This reduces the quality especially of the line segment joins. (Only relevant for solid line pens.)
phForceRepaint
0x002 causes an immediate repaint() instead of a soft update() when QCustomPlot::replot() is called with parameter QCustomPlot::rpHint. This is set by default to prevent the plot from freezing on fast consecutive replots (e.g. user drags ranges with mouse).
phCacheLabels
0x004 axis (tick) labels will be cached as pixmaps, increasing replot performance.
Definition at line 139 of file qcustomplot.h.
Function Documentation
int QCP::getMarginValue (const QMargins & margins, QCP::MarginSide side) inline
Definition at line 213 of file qcustomplot.h.
References msBottom, msLeft, msRight, and msTop.
Referenced by QCPLayoutElement::calculateAutoMargin(), QCPMarginGroup::commonMargin(), and QCPLayoutElement::update().
bool QCP::isInvalidData (double value) inline
Definition at line 172 of file qcustomplot.h.
Referenced by QCPGraph::draw(), QCPCurve::draw(), QCPBars::draw(), QCPStatisticalBox::draw(), and isInvalidData().
bool QCP::isInvalidData (double value1, double value2) inline
Definition at line 182 of file qcustomplot.h.
References isInvalidData().
void QCP::setMarginValue (QMargins & margins, QCP::MarginSide side, int value) inline
Definition at line 193 of file qcustomplot.h.
References msAll, msBottom, msLeft, msRight, and msTop.
Referenced by QCPLayoutElement::update().